-- VectorCAST 25.sp4 (08/19/25)
-- Test Case Script
--
-- Environment    : SWUT_21_EEPROM
-- Unit(s) Under Test: EEPROM
--
-- Script Features
TEST.SCRIPT_FEATURE:C_DIRECT_ARRAY_INDEXING
TEST.SCRIPT_FEATURE:CPP_CLASS_OBJECT_REVISION
TEST.SCRIPT_FEATURE:MULTIPLE_UUT_SUPPORT
TEST.SCRIPT_FEATURE:REMOVED_CL_PREFIX
TEST.SCRIPT_FEATURE:MIXED_CASE_NAMES
TEST.SCRIPT_FEATURE:STATIC_HEADER_FUNCS_IN_UUTS
TEST.SCRIPT_FEATURE:VCAST_MAIN_NOT_RENAMED
--

-- Unit: EEPROM

-- Subprogram: BackupSector

-- Test Case: SwUFn_2104.001
TEST.UNIT:EEPROM
TEST.SUBPROGRAM:BackupSector
TEST.NEW
TEST.NAME:SwUFn_2104.001
TEST.NOTES:
REQ/BA
TEST.END_NOTES:
TEST.STUB:EEPROM.WriteBlock
TEST.STUB:EEPROM.SetupFCCOB
TEST.STUB:EEPROM.EraseSectorInternal
TEST.STUB:EEPROM.WriteWord
TEST.STUB:EEPROM.EEPROM_SetByte
TEST.STUB:EEPROM.EEPROM_GetByte
TEST.STUB:EEPROM.EEPROM_Init
TEST.VALUE:EEPROM.BackupSector.Addr:<<malloc 1>>
TEST.VALUE:EEPROM.BackupSector.Addr[0]:0
TEST.VALUE:EEPROM.BackupSector.From:0
TEST.VALUE:EEPROM.BackupSector.To:0
TEST.EXPECTED:EEPROM.<<GLOBAL>>.BackupArray[0..1]:0
TEST.END

-- Test Case: SwUFn_2104.002
TEST.UNIT:EEPROM
TEST.SUBPROGRAM:BackupSector
TEST.NEW
TEST.NAME:SwUFn_2104.002
TEST.NOTES:
REQ/BA
TEST.END_NOTES:
TEST.STUB:EEPROM.WriteBlock
TEST.STUB:EEPROM.SetupFCCOB
TEST.STUB:EEPROM.EraseSectorInternal
TEST.STUB:EEPROM.WriteWord
TEST.STUB:EEPROM.EEPROM_SetByte
TEST.STUB:EEPROM.EEPROM_GetByte
TEST.STUB:EEPROM.EEPROM_Init
TEST.VALUE:EEPROM.BackupSector.Addr:<<malloc 1>>
TEST.VALUE:EEPROM.BackupSector.Addr[0]:2147483647
TEST.VALUE:EEPROM.BackupSector.From:32767
TEST.VALUE:EEPROM.BackupSector.To:32767
TEST.EXPECTED:EEPROM.<<GLOBAL>>.BackupArray[0..1]:0
TEST.END

-- Test Case: SwUFn_2104.003
TEST.UNIT:EEPROM
TEST.SUBPROGRAM:BackupSector
TEST.NEW
TEST.NAME:SwUFn_2104.003
TEST.NOTES:
REQ/BA
TEST.END_NOTES:
TEST.STUB:EEPROM.WriteBlock
TEST.STUB:EEPROM.SetupFCCOB
TEST.STUB:EEPROM.EraseSectorInternal
TEST.STUB:EEPROM.WriteWord
TEST.STUB:EEPROM.EEPROM_SetByte
TEST.STUB:EEPROM.EEPROM_GetByte
TEST.STUB:EEPROM.EEPROM_Init
TEST.VALUE:EEPROM.BackupSector.Addr:<<malloc 1>>
TEST.VALUE:EEPROM.BackupSector.Addr[0]:4294967295
TEST.VALUE:EEPROM.BackupSector.From:65535
TEST.VALUE:EEPROM.BackupSector.To:65535
TEST.EXPECTED:EEPROM.<<GLOBAL>>.BackupArray[0..1]:0
TEST.END

-- Test Case: SwUFn_2104.004
TEST.UNIT:EEPROM
TEST.SUBPROGRAM:BackupSector
TEST.NEW
TEST.NAME:SwUFn_2104.004
TEST.NOTES:
REQ/FI
TEST.END_NOTES:
TEST.STUB:EEPROM.WriteBlock
TEST.STUB:EEPROM.SetupFCCOB
TEST.STUB:EEPROM.EraseSectorInternal
TEST.STUB:EEPROM.WriteWord
TEST.STUB:EEPROM.EEPROM_SetByte
TEST.STUB:EEPROM.EEPROM_GetByte
TEST.STUB:EEPROM.EEPROM_Init
TEST.VALUE:EEPROM.BackupSector.Addr:<<malloc 1>>
TEST.VALUE:EEPROM.BackupSector.Addr[0]:-1
TEST.VALUE:EEPROM.BackupSector.From:-1
TEST.VALUE:EEPROM.BackupSector.To:-1
TEST.EXPECTED:EEPROM.<<GLOBAL>>.BackupArray[0..1]:0
TEST.END

-- Test Case: SwUFn_2104.005
TEST.UNIT:EEPROM
TEST.SUBPROGRAM:BackupSector
TEST.NEW
TEST.NAME:SwUFn_2104.005
TEST.NOTES:
REQ/FI
TEST.END_NOTES:
TEST.STUB:EEPROM.WriteBlock
TEST.STUB:EEPROM.SetupFCCOB
TEST.STUB:EEPROM.EraseSectorInternal
TEST.STUB:EEPROM.WriteWord
TEST.STUB:EEPROM.EEPROM_SetByte
TEST.STUB:EEPROM.EEPROM_GetByte
TEST.STUB:EEPROM.EEPROM_Init
TEST.VALUE:EEPROM.BackupSector.Addr:<<malloc 1>>
TEST.VALUE:EEPROM.BackupSector.Addr[0]:4294967296
TEST.VALUE:EEPROM.BackupSector.From:65536
TEST.VALUE:EEPROM.BackupSector.To:65536
TEST.EXPECTED:EEPROM.<<GLOBAL>>.BackupArray[0..1]:0
TEST.END

-- Test Case: SwUFn_2104.006
TEST.UNIT:EEPROM
TEST.SUBPROGRAM:BackupSector
TEST.NEW
TEST.NAME:SwUFn_2104.006
TEST.NOTES:
REQ/FI
TEST.END_NOTES:
TEST.STUB:EEPROM.WriteBlock
TEST.STUB:EEPROM.SetupFCCOB
TEST.STUB:EEPROM.EraseSectorInternal
TEST.STUB:EEPROM.WriteWord
TEST.STUB:EEPROM.EEPROM_SetByte
TEST.STUB:EEPROM.EEPROM_GetByte
TEST.STUB:EEPROM.EEPROM_Init
TEST.VALUE:EEPROM.BackupSector.Addr:<<malloc 1>>
TEST.VALUE:EEPROM.BackupSector.Addr[0]:5004924896
TEST.VALUE:EEPROM.BackupSector.From:70154
TEST.VALUE:EEPROM.BackupSector.To:70154
TEST.EXPECTED:EEPROM.<<GLOBAL>>.BackupArray[0..1]:0
TEST.END

-- Test Case: SwUFn_2104.007
TEST.UNIT:EEPROM
TEST.SUBPROGRAM:BackupSector
TEST.NEW
TEST.NAME:SwUFn_2104.007
TEST.NOTES:
REQ/FI
TEST.END_NOTES:
TEST.STUB:EEPROM.WriteBlock
TEST.STUB:EEPROM.SetupFCCOB
TEST.STUB:EEPROM.EraseSectorInternal
TEST.STUB:EEPROM.WriteWord
TEST.STUB:EEPROM.EEPROM_SetByte
TEST.STUB:EEPROM.EEPROM_GetByte
TEST.STUB:EEPROM.EEPROM_Init
TEST.VALUE:EEPROM.BackupSector.Addr:<<malloc 1>>
TEST.VALUE:EEPROM.BackupSector.Addr[0]:5104000765
TEST.VALUE:EEPROM.BackupSector.From:72148
TEST.VALUE:EEPROM.BackupSector.To:72148
TEST.EXPECTED:EEPROM.<<GLOBAL>>.BackupArray[0..1]:0
TEST.END

-- Subprogram: EEPROM_GetByte

-- Test Case: SwUFn_2102.001
TEST.UNIT:EEPROM
TEST.SUBPROGRAM:EEPROM_GetByte
TEST.NEW
TEST.NAME:SwUFn_2102.001
TEST.IMPORT_FAILURES:
(E) @LINE: 182 TEST.VALUE:EEPROM.<<GLOBAL>>.EEPROMaddr:<<malloc 1>>
    >>> Unknown parameter/object name EEPROMaddr
    >>> Value Line Error - Command Ignored
(E) @LINE: 183 TEST.VALUE:EEPROM.<<GLOBAL>>.REG_FSTAT.Bits.CCIF:-1
    >>> Unknown parameter/object name REG_FSTAT
    >>> Value Line Error - Command Ignored
(E) @LINE: 184 TEST.EXPECTED:EEPROM.<<GLOBAL>>.EEPROMaddr[0]:65535
    >>> Unknown parameter/object name EEPROMaddr
    >>> Value Line Error - Command Ignored
TEST.END_IMPORT_FAILURES:
TEST.END

-- Test Case: SwUFn_2102.001
TEST.UNIT:EEPROM
TEST.SUBPROGRAM:EEPROM_GetByte
TEST.ADD
TEST.NAME:SwUFn_2102.001
TEST.VALUE:EEPROM.<<GLOBAL>>.EEPROMaddr:<<malloc 1>>
TEST.VALUE:EEPROM.<<GLOBAL>>.REG_FSTAT.Bits.CCIF:-1
TEST.EXPECTED:EEPROM.<<GLOBAL>>.EEPROMaddr[0]:65535
TEST.END

-- Test Case: SwUFn_2102.002
TEST.UNIT:EEPROM
TEST.SUBPROGRAM:EEPROM_GetByte
TEST.NEW
TEST.NAME:SwUFn_2102.002
TEST.IMPORT_FAILURES:
(E) @LINE: 192 TEST.VALUE:EEPROM.<<GLOBAL>>.EEPROMaddr:<<malloc 1>>
    >>> Unknown parameter/object name EEPROMaddr
    >>> Value Line Error - Command Ignored
(E) @LINE: 193 TEST.VALUE:EEPROM.<<GLOBAL>>.REG_FSTAT.Bits.CCIF:0
    >>> Unknown parameter/object name REG_FSTAT
    >>> Value Line Error - Command Ignored
(E) @LINE: 194 TEST.EXPECTED:EEPROM.<<GLOBAL>>.EEPROMaddr[0]:0
    >>> Unknown parameter/object name EEPROMaddr
    >>> Value Line Error - Command Ignored
TEST.END_IMPORT_FAILURES:
TEST.END

-- Test Case: SwUFn_2102.002
TEST.UNIT:EEPROM
TEST.SUBPROGRAM:EEPROM_GetByte
TEST.ADD
TEST.NAME:SwUFn_2102.002
TEST.VALUE:EEPROM.<<GLOBAL>>.EEPROMaddr:<<malloc 1>>
TEST.VALUE:EEPROM.<<GLOBAL>>.REG_FSTAT.Bits.CCIF:0
TEST.EXPECTED:EEPROM.<<GLOBAL>>.EEPROMaddr[0]:0
TEST.END

-- Test Case: SwUFn_2102.003
TEST.UNIT:EEPROM
TEST.SUBPROGRAM:EEPROM_GetByte
TEST.NEW
TEST.NAME:SwUFn_2102.003
TEST.IMPORT_FAILURES:
(E) @LINE: 263 TEST.VALUE:EEPROM.<<GLOBAL>>.EEPROMaddr:<<malloc 1>>
    >>> Unknown parameter/object name EEPROMaddr
    >>> Value Line Error - Command Ignored
(E) @LINE: 264 TEST.VALUE:EEPROM.<<GLOBAL>>.REG_FSTAT.Bits.CCIF:64
    >>> Unknown parameter/object name REG_FSTAT
    >>> Value Line Error - Command Ignored
(E) @LINE: 265 TEST.EXPECTED:EEPROM.<<GLOBAL>>.EEPROMaddr[0]:0
    >>> Unknown parameter/object name EEPROMaddr
    >>> Value Line Error - Command Ignored
TEST.END_IMPORT_FAILURES:
TEST.END

-- Test Case: SwUFn_2102.003
TEST.UNIT:EEPROM
TEST.SUBPROGRAM:EEPROM_GetByte
TEST.ADD
TEST.NAME:SwUFn_2102.003
TEST.VALUE:EEPROM.<<GLOBAL>>.EEPROMaddr:<<malloc 1>>
TEST.VALUE:EEPROM.<<GLOBAL>>.REG_FSTAT.Bits.CCIF:64
TEST.EXPECTED:EEPROM.<<GLOBAL>>.EEPROMaddr[0]:0
TEST.END

-- Test Case: SwUFn_2102.004
TEST.UNIT:EEPROM
TEST.SUBPROGRAM:EEPROM_GetByte
TEST.NEW
TEST.NAME:SwUFn_2102.004
TEST.IMPORT_FAILURES:
(E) @LINE: 294 TEST.VALUE:EEPROM.<<GLOBAL>>.EEPROMaddr:<<malloc 1>>
    >>> Unknown parameter/object name EEPROMaddr
    >>> Value Line Error - Command Ignored
(E) @LINE: 295 TEST.VALUE:EEPROM.<<GLOBAL>>.REG_FSTAT.Bits.CCIF:128
    >>> Unknown parameter/object name REG_FSTAT
    >>> Value Line Error - Command Ignored
(E) @LINE: 296 TEST.EXPECTED:EEPROM.<<GLOBAL>>.EEPROMaddr[0]:0
    >>> Unknown parameter/object name EEPROMaddr
    >>> Value Line Error - Command Ignored
TEST.END_IMPORT_FAILURES:
TEST.END

-- Test Case: SwUFn_2102.004
TEST.UNIT:EEPROM
TEST.SUBPROGRAM:EEPROM_GetByte
TEST.ADD
TEST.NAME:SwUFn_2102.004
TEST.VALUE:EEPROM.<<GLOBAL>>.EEPROMaddr:<<malloc 1>>
TEST.VALUE:EEPROM.<<GLOBAL>>.REG_FSTAT.Bits.CCIF:128
TEST.EXPECTED:EEPROM.<<GLOBAL>>.EEPROMaddr[0]:0
TEST.END

-- Test Case: SwUFn_2102.005
TEST.UNIT:EEPROM
TEST.SUBPROGRAM:EEPROM_GetByte
TEST.NEW
TEST.NAME:SwUFn_2102.005
TEST.IMPORT_FAILURES:
(E) @LINE: 325 TEST.VALUE:EEPROM.<<GLOBAL>>.EEPROMaddr:<<malloc 1>>
    >>> Unknown parameter/object name EEPROMaddr
    >>> Value Line Error - Command Ignored
(E) @LINE: 326 TEST.VALUE:EEPROM.<<GLOBAL>>.REG_FSTAT.Bits.CCIF:129
    >>> Unknown parameter/object name REG_FSTAT
    >>> Value Line Error - Command Ignored
(E) @LINE: 327 TEST.EXPECTED:EEPROM.<<GLOBAL>>.EEPROMaddr[0]:65535
    >>> Unknown parameter/object name EEPROMaddr
    >>> Value Line Error - Command Ignored
TEST.END_IMPORT_FAILURES:
TEST.END

-- Test Case: SwUFn_2102.005
TEST.UNIT:EEPROM
TEST.SUBPROGRAM:EEPROM_GetByte
TEST.ADD
TEST.NAME:SwUFn_2102.005
TEST.VALUE:EEPROM.<<GLOBAL>>.EEPROMaddr:<<malloc 1>>
TEST.VALUE:EEPROM.<<GLOBAL>>.REG_FSTAT.Bits.CCIF:129
TEST.EXPECTED:EEPROM.<<GLOBAL>>.EEPROMaddr[0]:65535
TEST.END

-- Test Case: SwUFn_2102.006
TEST.UNIT:EEPROM
TEST.SUBPROGRAM:EEPROM_GetByte
TEST.NEW
TEST.NAME:SwUFn_2102.006
TEST.IMPORT_FAILURES:
(E) @LINE: 356 TEST.VALUE:EEPROM.<<GLOBAL>>.EEPROMaddr:<<malloc 1>>
    >>> Unknown parameter/object name EEPROMaddr
    >>> Value Line Error - Command Ignored
(E) @LINE: 357 TEST.VALUE:EEPROM.<<GLOBAL>>.REG_FSTAT.Bits.CCIF:0
    >>> Unknown parameter/object name REG_FSTAT
    >>> Value Line Error - Command Ignored
(E) @LINE: 358 TEST.EXPECTED:EEPROM.<<GLOBAL>>.EEPROMaddr[0]:0
    >>> Unknown parameter/object name EEPROMaddr
    >>> Value Line Error - Command Ignored
TEST.END_IMPORT_FAILURES:
TEST.END

-- Test Case: SwUFn_2102.006
TEST.UNIT:EEPROM
TEST.SUBPROGRAM:EEPROM_GetByte
TEST.ADD
TEST.NAME:SwUFn_2102.006
TEST.VALUE:EEPROM.<<GLOBAL>>.EEPROMaddr:<<malloc 1>>
TEST.VALUE:EEPROM.<<GLOBAL>>.REG_FSTAT.Bits.CCIF:0
TEST.EXPECTED:EEPROM.<<GLOBAL>>.EEPROMaddr[0]:0
TEST.END

-- Test Case: SwUFn_2201.001
TEST.UNIT:EEPROM
TEST.SUBPROGRAM:EEPROM_GetByte
TEST.NEW
TEST.NAME:SwUFn_2201.001
TEST.NOTES:
REQ/BA
TEST.END_NOTES:
TEST.STUB:EEPROM.BackupSector
TEST.STUB:EEPROM.WriteBlock
TEST.STUB:EEPROM.SetupFCCOB
TEST.STUB:EEPROM.EraseSectorInternal
TEST.STUB:EEPROM.WriteWord
TEST.STUB:EEPROM.EEPROM_SetByte
TEST.STUB:EEPROM.EEPROM_Init
TEST.VALUE:EEPROM.<<GLOBAL>>._FSTAT.Bits.CCIF:0
TEST.VALUE:EEPROM.EEPROM_GetByte.Addr:<<malloc 1>>
TEST.VALUE:EEPROM.EEPROM_GetByte.Addr[0]:0
TEST.EXPECTED:EEPROM.EEPROM_GetByte.return:2
TEST.END

-- Test Case: SwUFn_2201.002
TEST.UNIT:EEPROM
TEST.SUBPROGRAM:EEPROM_GetByte
TEST.NEW
TEST.NAME:SwUFn_2201.002
TEST.IMPORT_FAILURES:
(E) @LINE: 418 TEST.VALUE:EEPROM.<<GLOBAL>>.EEPROMaddr:<<malloc 1>>
    >>> Unknown parameter/object name EEPROMaddr
    >>> Value Line Error - Command Ignored
(E) @LINE: 419 TEST.EXPECTED:EEPROM.<<GLOBAL>>.EEPROMaddr[0]:0
    >>> Unknown parameter/object name EEPROMaddr
    >>> Value Line Error - Command Ignored
(E) @LINE: 420 TEST.EXPECTED:EEPROM.<<GLOBAL>>.REG_FCLKDIV.Byte:0x1D
    >>> Unknown parameter/object name REG_FCLKDIV
    >>> Value Line Error - Command Ignored
TEST.END_IMPORT_FAILURES:
TEST.NOTES:
REQ/BA
TEST.END_NOTES:
TEST.STUB:EEPROM.BackupSector
TEST.STUB:EEPROM.WriteBlock
TEST.STUB:EEPROM.SetupFCCOB
TEST.STUB:EEPROM.EraseSectorInternal
TEST.STUB:EEPROM.WriteWord
TEST.STUB:EEPROM.EEPROM_SetByte
TEST.STUB:EEPROM.EEPROM_Init
TEST.VALUE:EEPROM.<<GLOBAL>>._FSTAT.Bits.CCIF:0
TEST.VALUE:EEPROM.EEPROM_GetByte.Addr:<<malloc 1>>
TEST.VALUE:EEPROM.EEPROM_GetByte.Addr[0]:2147483647
TEST.EXPECTED:EEPROM.EEPROM_GetByte.return:2
TEST.END

-- Test Case: SwUFn_2201.003
TEST.UNIT:EEPROM
TEST.SUBPROGRAM:EEPROM_GetByte
TEST.NEW
TEST.NAME:SwUFn_2201.003
TEST.IMPORT_FAILURES:
(E) @LINE: 460 TEST.VALUE:EEPROM.<<GLOBAL>>.REG_FSTAT.Bits.CCIF:-1
    >>> Unknown parameter/object name REG_FSTAT
    >>> Value Line Error - Command Ignored
TEST.END_IMPORT_FAILURES:
TEST.NOTES:
REQ/BA
TEST.END_NOTES:
TEST.STUB:EEPROM.BackupSector
TEST.STUB:EEPROM.WriteBlock
TEST.STUB:EEPROM.SetupFCCOB
TEST.STUB:EEPROM.EraseSectorInternal
TEST.STUB:EEPROM.WriteWord
TEST.STUB:EEPROM.EEPROM_SetByte
TEST.STUB:EEPROM.EEPROM_Init
TEST.VALUE:EEPROM.<<GLOBAL>>._FSTAT.Bits.CCIF:1
TEST.VALUE:EEPROM.EEPROM_GetByte.Addr:<<malloc 1>>
TEST.VALUE:EEPROM.EEPROM_GetByte.Addr[0]:4294967295
TEST.EXPECTED:EEPROM.EEPROM_GetByte.return:2
TEST.END

-- Test Case: SwUFn_2201.004
TEST.UNIT:EEPROM
TEST.SUBPROGRAM:EEPROM_GetByte
TEST.NEW
TEST.NAME:SwUFn_2201.004
TEST.IMPORT_FAILURES:
(E) @LINE: 497 TEST.VALUE:EEPROM.<<GLOBAL>>.REG_FSTAT.Bits.CCIF:0
    >>> Unknown parameter/object name REG_FSTAT
    >>> Value Line Error - Command Ignored
TEST.END_IMPORT_FAILURES:
TEST.NOTES:
REQ/FI
TEST.END_NOTES:
TEST.STUB:EEPROM.BackupSector
TEST.STUB:EEPROM.WriteBlock
TEST.STUB:EEPROM.SetupFCCOB
TEST.STUB:EEPROM.EraseSectorInternal
TEST.STUB:EEPROM.WriteWord
TEST.STUB:EEPROM.EEPROM_SetByte
TEST.STUB:EEPROM.EEPROM_Init
TEST.VALUE:EEPROM.<<GLOBAL>>._FSTAT.Bits.CCIF:-1
TEST.VALUE:EEPROM.EEPROM_GetByte.Addr:<<malloc 1>>
TEST.VALUE:EEPROM.EEPROM_GetByte.Addr[0]:-1
TEST.EXPECTED:EEPROM.EEPROM_GetByte.return:2
TEST.END

-- Test Case: SwUFn_2201.005
TEST.UNIT:EEPROM
TEST.SUBPROGRAM:EEPROM_GetByte
TEST.NEW
TEST.NAME:SwUFn_2201.005
TEST.IMPORT_FAILURES:
(E) @LINE: 534 TEST.VALUE:EEPROM.<<GLOBAL>>.REG_FSTAT.Bits.CCIF:1
    >>> Unknown parameter/object name REG_FSTAT
    >>> Value Line Error - Command Ignored
TEST.END_IMPORT_FAILURES:
TEST.NOTES:
REQ/BA
TEST.END_NOTES:
TEST.STUB:EEPROM.BackupSector
TEST.STUB:EEPROM.WriteBlock
TEST.STUB:EEPROM.SetupFCCOB
TEST.STUB:EEPROM.EraseSectorInternal
TEST.STUB:EEPROM.WriteWord
TEST.STUB:EEPROM.EEPROM_SetByte
TEST.STUB:EEPROM.EEPROM_Init
TEST.VALUE:EEPROM.<<GLOBAL>>._FSTAT.Bits.CCIF:2
TEST.VALUE:EEPROM.EEPROM_GetByte.Addr:<<malloc 1>>
TEST.VALUE:EEPROM.EEPROM_GetByte.Addr[0]:4294967296
TEST.EXPECTED:EEPROM.EEPROM_GetByte.return:2
TEST.END

-- Test Case: SwUFn_2201.006
TEST.UNIT:EEPROM
TEST.SUBPROGRAM:EEPROM_GetByte
TEST.NEW
TEST.NAME:SwUFn_2201.006
TEST.IMPORT_FAILURES:
(E) @LINE: 571 TEST.VALUE:EEPROM.<<GLOBAL>>.REG_FSTAT.Bits.CCIF:1
    >>> Unknown parameter/object name REG_FSTAT
    >>> Value Line Error - Command Ignored
TEST.END_IMPORT_FAILURES:
TEST.NOTES:
REQ/BA
TEST.END_NOTES:
TEST.STUB:EEPROM.BackupSector
TEST.STUB:EEPROM.WriteBlock
TEST.STUB:EEPROM.SetupFCCOB
TEST.STUB:EEPROM.EraseSectorInternal
TEST.STUB:EEPROM.WriteWord
TEST.STUB:EEPROM.EEPROM_SetByte
TEST.STUB:EEPROM.EEPROM_Init
TEST.VALUE:EEPROM.<<GLOBAL>>._FSTAT.Bits.CCIF:5
TEST.VALUE:EEPROM.EEPROM_GetByte.Addr:<<malloc 1>>
TEST.VALUE:EEPROM.EEPROM_GetByte.Addr[0]:5000067296
TEST.EXPECTED:EEPROM.EEPROM_GetByte.return:2
TEST.END

-- Test Case: SwUFn_2201.007
TEST.UNIT:EEPROM
TEST.SUBPROGRAM:EEPROM_GetByte
TEST.NEW
TEST.NAME:SwUFn_2201.007
TEST.IMPORT_FAILURES:
(E) @LINE: 608 TEST.VALUE:EEPROM.<<GLOBAL>>.REG_FSTAT.Bits.CCIF:2
    >>> Unknown parameter/object name REG_FSTAT
    >>> Value Line Error - Command Ignored
TEST.END_IMPORT_FAILURES:
TEST.NOTES:
REQ/BA
TEST.END_NOTES:
TEST.STUB:EEPROM.BackupSector
TEST.STUB:EEPROM.WriteBlock
TEST.STUB:EEPROM.SetupFCCOB
TEST.STUB:EEPROM.EraseSectorInternal
TEST.STUB:EEPROM.WriteWord
TEST.STUB:EEPROM.EEPROM_SetByte
TEST.STUB:EEPROM.EEPROM_Init
TEST.VALUE:EEPROM.<<GLOBAL>>._FSTAT.Bits.CCIF:10
TEST.VALUE:EEPROM.EEPROM_GetByte.Addr:<<malloc 1>>
TEST.VALUE:EEPROM.EEPROM_GetByte.Addr[0]:4900069496
TEST.EXPECTED:EEPROM.EEPROM_GetByte.return:2
TEST.END

-- Subprogram: EEPROM_Init

-- Test Case: SwUFn_2103.001
TEST.UNIT:EEPROM
TEST.SUBPROGRAM:EEPROM_Init
TEST.NEW
TEST.NAME:SwUFn_2103.001
TEST.IMPORT_FAILURES:
(E) @LINE: 645 TEST.VALUE:EEPROM.<<GLOBAL>>.REG_FSTAT.Bits.CCIF:1
    >>> Unknown parameter/object name REG_FSTAT
    >>> Value Line Error - Command Ignored
TEST.END_IMPORT_FAILURES:
TEST.NOTES:
REQ/EC
TEST.END_NOTES:
TEST.STUB:EEPROM.BackupSector
TEST.STUB:EEPROM.WriteBlock
TEST.STUB:EEPROM.SetupFCCOB
TEST.STUB:EEPROM.EraseSectorInternal
TEST.STUB:EEPROM.WriteWord
TEST.STUB:EEPROM.EEPROM_SetByte
TEST.STUB:EEPROM.EEPROM_GetByte
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FCLKDIV.Byte:29
TEST.END

-- Test Case: SwUFn_2103.001
TEST.UNIT:EEPROM
TEST.SUBPROGRAM:EEPROM_Init
TEST.ADD
TEST.NAME:SwUFn_2103.001
TEST.VALUE:EEPROM.<<GLOBAL>>.EEPROMaddr:<<malloc 1>>
TEST.EXPECTED:EEPROM.<<GLOBAL>>.EEPROMaddr[0]:0
TEST.EXPECTED:EEPROM.<<GLOBAL>>.REG_FCLKDIV.Byte:0x1D
TEST.END

-- Subprogram: EEPROM_SetByte

-- Test Case: SwUFn_2101.001
TEST.UNIT:EEPROM
TEST.SUBPROGRAM:EEPROM_SetByte
TEST.NEW
TEST.NAME:SwUFn_2101.001
TEST.IMPORT_FAILURES:
(E) @LINE: 682 TEST.VALUE:EEPROM.<<GLOBAL>>.REG_FSTAT.Bits.CCIF:1
    >>> Unknown parameter/object name REG_FSTAT
    >>> Value Line Error - Command Ignored
TEST.END_IMPORT_FAILURES:
TEST.NOTES:
REQ/BA
TEST.END_NOTES:
TEST.STUB:EEPROM.BackupSector
TEST.STUB:EEPROM.WriteBlock
TEST.STUB:EEPROM.SetupFCCOB
TEST.STUB:EEPROM.EraseSectorInternal
TEST.STUB:EEPROM.WriteWord
TEST.STUB:EEPROM.EEPROM_GetByte
TEST.STUB:EEPROM.EEPROM_Init
TEST.VALUE:EEPROM.<<GLOBAL>>.BackupArray[0..1]:0
TEST.VALUE:EEPROM.<<GLOBAL>>._FSTAT.Bits.CCIF:0
TEST.VALUE:EEPROM.EEPROM_SetByte.Addr:<<malloc 2>>
TEST.VALUE:EEPROM.EEPROM_SetByte.Addr[0]:0
TEST.VALUE:EEPROM.EEPROM_SetByte.Addr[1]:0
TEST.VALUE:EEPROM.EEPROM_SetByte.Data:0
TEST.EXPECTED:EEPROM.<<GLOBAL>>.BackupArray[0..1]:0
TEST.EXPECTED:EEPROM.EEPROM_SetByte.return:2
TEST.END

-- Test Case: SwUFn_2101.001
TEST.UNIT:EEPROM
TEST.SUBPROGRAM:EEPROM_SetByte
TEST.ADD
TEST.NAME:SwUFn_2101.001
TEST.VALUE:EEPROM.<<GLOBAL>>.REG_FSTAT.Bits.CCIF:-1
TEST.END

-- Test Case: SwUFn_2101.002
TEST.UNIT:EEPROM
TEST.SUBPROGRAM:EEPROM_SetByte
TEST.NEW
TEST.NAME:SwUFn_2101.002
TEST.NOTES:
REQ/BA
TEST.END_NOTES:
TEST.STUB:EEPROM.BackupSector
TEST.STUB:EEPROM.WriteBlock
TEST.STUB:EEPROM.SetupFCCOB
TEST.STUB:EEPROM.EraseSectorInternal
TEST.STUB:EEPROM.WriteWord
TEST.STUB:EEPROM.EEPROM_GetByte
TEST.STUB:EEPROM.EEPROM_Init
TEST.VALUE:EEPROM.<<GLOBAL>>.BackupArray[0..1]:32767
TEST.VALUE:EEPROM.<<GLOBAL>>._FSTAT.Bits.CCIF:0
TEST.VALUE:EEPROM.EEPROM_SetByte.Addr:<<malloc 1>>
TEST.VALUE:EEPROM.EEPROM_SetByte.Addr[0]:2147483647
TEST.VALUE:EEPROM.EEPROM_SetByte.Data:127
TEST.EXPECTED:EEPROM.<<GLOBAL>>.BackupArray[0..1]:32767
TEST.EXPECTED:EEPROM.EEPROM_SetByte.return:2
TEST.VALUE_USER_CODE:EEPROM.EEPROM_SetByte.Addr
<<EEPROM.EEPROM_SetByte.Addr>> = ( (word *)0x00100300UL );
TEST.END_VALUE_USER_CODE:
TEST.END

-- Test Case: SwUFn_2101.002
TEST.UNIT:EEPROM
TEST.SUBPROGRAM:EEPROM_SetByte
TEST.ADD
TEST.NAME:SwUFn_2101.002
TEST.VALUE:EEPROM.<<GLOBAL>>.REG_FSTAT.Bits.CCIF:0
TEST.END

-- Test Case: SwUFn_2101.003
TEST.UNIT:EEPROM
TEST.SUBPROGRAM:EEPROM_SetByte
TEST.NEW
TEST.NAME:SwUFn_2101.003
TEST.NOTES:
REQ/BA
TEST.END_NOTES:
TEST.STUB:EEPROM.BackupSector
TEST.STUB:EEPROM.WriteBlock
TEST.STUB:EEPROM.SetupFCCOB
TEST.STUB:EEPROM.EraseSectorInternal
TEST.STUB:EEPROM.WriteWord
TEST.STUB:EEPROM.EEPROM_GetByte
TEST.STUB:EEPROM.EEPROM_Init
TEST.VALUE:EEPROM.<<GLOBAL>>.BackupArray[0..1]:65535
TEST.VALUE:EEPROM.<<GLOBAL>>._FSTAT.Bits.CCIF:1
TEST.VALUE:EEPROM.EEPROM_SetByte.Addr:<<malloc 1>>
TEST.VALUE:EEPROM.EEPROM_SetByte.Addr[0]:4294967295
TEST.VALUE:EEPROM.EEPROM_SetByte.Data:255
TEST.EXPECTED:EEPROM.<<GLOBAL>>.BackupArray[0..1]:65535
TEST.EXPECTED:EEPROM.EEPROM_SetByte.return:2
TEST.VALUE_USER_CODE:EEPROM.EEPROM_SetByte.Addr
<<EEPROM.EEPROM_SetByte.Addr>> = ( (word *)0x001003FFUL );
TEST.END_VALUE_USER_CODE:
TEST.END

-- Test Case: SwUFn_2101.003
TEST.UNIT:EEPROM
TEST.SUBPROGRAM:EEPROM_SetByte
TEST.ADD
TEST.NAME:SwUFn_2101.003
TEST.VALUE:EEPROM.<<GLOBAL>>.REG_FSTAT.Bits.CCIF:1
TEST.END

-- Test Case: SwUFn_2101.004
TEST.UNIT:EEPROM
TEST.SUBPROGRAM:EEPROM_SetByte
TEST.NEW
TEST.NAME:SwUFn_2101.004
TEST.NOTES:
REQ/FI
TEST.END_NOTES:
TEST.STUB:EEPROM.BackupSector
TEST.STUB:EEPROM.WriteBlock
TEST.STUB:EEPROM.SetupFCCOB
TEST.STUB:EEPROM.EraseSectorInternal
TEST.STUB:EEPROM.WriteWord
TEST.STUB:EEPROM.EEPROM_GetByte
TEST.STUB:EEPROM.EEPROM_Init
TEST.VALUE:EEPROM.<<GLOBAL>>.BackupArray[0..1]:-1
TEST.VALUE:EEPROM.<<GLOBAL>>._FSTAT.Bits.CCIF:-1
TEST.VALUE:EEPROM.EEPROM_SetByte.Addr:<<malloc 1>>
TEST.VALUE:EEPROM.EEPROM_SetByte.Addr[0]:-1
TEST.VALUE:EEPROM.EEPROM_SetByte.Data:-1
TEST.EXPECTED:EEPROM.<<GLOBAL>>.BackupArray[0..1]:65535
TEST.EXPECTED:EEPROM.EEPROM_SetByte.return:2
TEST.VALUE_USER_CODE:EEPROM.EEPROM_SetByte.Addr
<<EEPROM.EEPROM_SetByte.Addr>> = ( (word *)0x001003F0UL );
TEST.END_VALUE_USER_CODE:
TEST.END

-- Test Case: SwUFn_2101.004
TEST.UNIT:EEPROM
TEST.SUBPROGRAM:EEPROM_SetByte
TEST.ADD
TEST.NAME:SwUFn_2101.004
TEST.VALUE:EEPROM.<<GLOBAL>>.REG_FSTAT.Bits.CCIF:1
TEST.END

-- Test Case: SwUFn_2101.005
TEST.UNIT:EEPROM
TEST.SUBPROGRAM:EEPROM_SetByte
TEST.NEW
TEST.NAME:SwUFn_2101.005
TEST.IMPORT_FAILURES:
(E) @LINE: 815 TEST.VALUE:EEPROM.<<GLOBAL>>.REG_FSTAT.Bits.CCIF:-1
    >>> Unknown parameter/object name REG_FSTAT
    >>> Value Line Error - Command Ignored
(E) @LINE: 816 TEST.EXPECTED:EEPROM.<<GLOBAL>>.REG_FCCOBIX.Byte:1
    >>> Unknown parameter/object name REG_FCCOBIX
    >>> Value Line Error - Command Ignored
(E) @LINE: 817 TEST.EXPECTED:EEPROM.<<GLOBAL>>.REG_FSTAT.Byte:0x80
    >>> Unknown parameter/object name REG_FSTAT
    >>> Value Line Error - Command Ignored
(E) @LINE: 818 TEST.EXPECTED:EEPROM.<<GLOBAL>>.REG_FCCOB0.Overlap_STR.FCCOB0HISTR.Byte:0x12
    >>> Unknown parameter/object name REG_FCCOB0
    >>> Value Line Error - Command Ignored
(E) @LINE: 819 TEST.EXPECTED:EEPROM.<<GLOBAL>>.REG_FCCOB0.Overlap_STR.FCCOB0LOSTR.Byte:0
    >>> Unknown parameter/object name REG_FCCOB0
    >>> Value Line Error - Command Ignored
(E) @LINE: 820 TEST.EXPECTED:EEPROM.<<GLOBAL>>.REG_FCCOB1.Word:10314
    >>> Unknown parameter/object name REG_FCCOB1
    >>> Value Line Error - Command Ignored
TEST.END_IMPORT_FAILURES:
TEST.NOTES:
REQ/BA
TEST.END_NOTES:
TEST.STUB:EEPROM.BackupSector
TEST.STUB:EEPROM.WriteBlock
TEST.STUB:EEPROM.SetupFCCOB
TEST.STUB:EEPROM.EraseSectorInternal
TEST.STUB:EEPROM.WriteWord
TEST.STUB:EEPROM.EEPROM_GetByte
TEST.STUB:EEPROM.EEPROM_Init
TEST.VALUE:EEPROM.<<GLOBAL>>.BackupArray[0..1]:65536
TEST.VALUE:EEPROM.<<GLOBAL>>._FSTAT.Bits.CCIF:2
TEST.VALUE:EEPROM.EEPROM_SetByte.Addr:<<malloc 1>>
TEST.VALUE:EEPROM.EEPROM_SetByte.Addr[0]:4294967296
TEST.VALUE:EEPROM.EEPROM_SetByte.Data:256
TEST.EXPECTED:EEPROM.<<GLOBAL>>.BackupArray[0..1]:0
TEST.EXPECTED:EEPROM.EEPROM_SetByte.return:2
TEST.END

-- Test Case: SwUFn_2101.005
TEST.UNIT:EEPROM
TEST.SUBPROGRAM:EEPROM_SetByte
TEST.ADD
TEST.NAME:SwUFn_2101.005
TEST.VALUE:EEPROM.<<GLOBAL>>.REG_FSTAT.Bits.CCIF:2
TEST.END

-- Test Case: SwUFn_2101.006
TEST.UNIT:EEPROM
TEST.SUBPROGRAM:EEPROM_SetByte
TEST.NEW
TEST.NAME:SwUFn_2101.006
TEST.IMPORT_FAILURES:
(E) @LINE: 875 TEST.VALUE:EEPROM.<<GLOBAL>>.REG_FSTAT.Bits.CCIF:0
    >>> Unknown parameter/object name REG_FSTAT
    >>> Value Line Error - Command Ignored
(E) @LINE: 876 TEST.EXPECTED:EEPROM.<<GLOBAL>>.REG_FCCOBIX.Byte:0
    >>> Unknown parameter/object name REG_FCCOBIX
    >>> Value Line Error - Command Ignored
(E) @LINE: 877 TEST.EXPECTED:EEPROM.<<GLOBAL>>.REG_FSTAT.Byte:0x0
    >>> Unknown parameter/object name REG_FSTAT
    >>> Value Line Error - Command Ignored
(E) @LINE: 878 TEST.EXPECTED:EEPROM.<<GLOBAL>>.REG_FCCOB0.Overlap_STR.FCCOB0HISTR.Byte:0x0
    >>> Unknown parameter/object name REG_FCCOB0
    >>> Value Line Error - Command Ignored
(E) @LINE: 879 TEST.EXPECTED:EEPROM.<<GLOBAL>>.REG_FCCOB0.Overlap_STR.FCCOB0LOSTR.Byte:0
    >>> Unknown parameter/object name REG_FCCOB0
    >>> Value Line Error - Command Ignored
(E) @LINE: 880 TEST.EXPECTED:EEPROM.<<GLOBAL>>.REG_FCCOB1.Word:0
    >>> Unknown parameter/object name REG_FCCOB1
    >>> Value Line Error - Command Ignored
TEST.END_IMPORT_FAILURES:
TEST.NOTES:
REQ/BA
TEST.END_NOTES:
TEST.STUB:EEPROM.BackupSector
TEST.STUB:EEPROM.WriteBlock
TEST.STUB:EEPROM.SetupFCCOB
TEST.STUB:EEPROM.EraseSectorInternal
TEST.STUB:EEPROM.WriteWord
TEST.STUB:EEPROM.EEPROM_GetByte
TEST.STUB:EEPROM.EEPROM_Init
TEST.VALUE:EEPROM.<<GLOBAL>>.BackupArray[0..1]:70000
TEST.VALUE:EEPROM.<<GLOBAL>>._FSTAT.Bits.CCIF:5
TEST.VALUE:EEPROM.EEPROM_SetByte.Addr:<<malloc 1>>
TEST.VALUE:EEPROM.EEPROM_SetByte.Addr[0]:5000000000
TEST.VALUE:EEPROM.EEPROM_SetByte.Data:300
TEST.EXPECTED:EEPROM.<<GLOBAL>>.BackupArray[0..1]:4464
TEST.EXPECTED:EEPROM.EEPROM_SetByte.return:2
TEST.END

-- Test Case: SwUFn_2101.006
TEST.UNIT:EEPROM
TEST.SUBPROGRAM:EEPROM_SetByte
TEST.ADD
TEST.NAME:SwUFn_2101.006
TEST.VALUE:EEPROM.<<GLOBAL>>.REG_FSTAT.Bits.CCIF:1
TEST.END

-- Test Case: SwUFn_2101.007
TEST.UNIT:EEPROM
TEST.SUBPROGRAM:EEPROM_SetByte
TEST.NEW
TEST.NAME:SwUFn_2101.007
TEST.IMPORT_FAILURES:
(E) @LINE: 935 TEST.VALUE:EEPROM.<<GLOBAL>>.REG_FSTAT.Bits.CCIF:1
    >>> Unknown parameter/object name REG_FSTAT
    >>> Value Line Error - Command Ignored
(E) @LINE: 936 TEST.EXPECTED:EEPROM.<<GLOBAL>>.REG_FCCOBIX.Byte:1
    >>> Unknown parameter/object name REG_FCCOBIX
    >>> Value Line Error - Command Ignored
(E) @LINE: 937 TEST.EXPECTED:EEPROM.<<GLOBAL>>.REG_FSTAT.Byte:0x80
    >>> Unknown parameter/object name REG_FSTAT
    >>> Value Line Error - Command Ignored
(E) @LINE: 938 TEST.EXPECTED:EEPROM.<<GLOBAL>>.REG_FCCOB0.Overlap_STR.FCCOB0HISTR.Byte:0x12
    >>> Unknown parameter/object name REG_FCCOB0
    >>> Value Line Error - Command Ignored
(E) @LINE: 939 TEST.EXPECTED:EEPROM.<<GLOBAL>>.REG_FCCOB0.Overlap_STR.FCCOB0LOSTR.Byte:0
    >>> Unknown parameter/object name REG_FCCOB0
    >>> Value Line Error - Command Ignored
(E) @LINE: 940 TEST.EXPECTED:EEPROM.<<GLOBAL>>.REG_FCCOB1.Word:10322
    >>> Unknown parameter/object name REG_FCCOB1
    >>> Value Line Error - Command Ignored
TEST.END_IMPORT_FAILURES:
TEST.NOTES:
REQ/FI
TEST.END_NOTES:
TEST.STUB:EEPROM.BackupSector
TEST.STUB:EEPROM.WriteBlock
TEST.STUB:EEPROM.SetupFCCOB
TEST.STUB:EEPROM.EraseSectorInternal
TEST.STUB:EEPROM.WriteWord
TEST.STUB:EEPROM.EEPROM_GetByte
TEST.STUB:EEPROM.EEPROM_Init
TEST.VALUE:EEPROM.<<GLOBAL>>.BackupArray[0..1]:84266
TEST.VALUE:EEPROM.<<GLOBAL>>._FSTAT.Bits.CCIF:12
TEST.VALUE:EEPROM.EEPROM_SetByte.Addr:<<malloc 1>>
TEST.VALUE:EEPROM.EEPROM_SetByte.Addr[0]:5458712357
TEST.VALUE:EEPROM.EEPROM_SetByte.Data:452
TEST.EXPECTED:EEPROM.<<GLOBAL>>.BackupArray[0..1]:18730
TEST.EXPECTED:EEPROM.EEPROM_SetByte.return:2
TEST.END

-- Test Case: SwUFn_2101.007
TEST.UNIT:EEPROM
TEST.SUBPROGRAM:EEPROM_SetByte
TEST.ADD
TEST.NAME:SwUFn_2101.007
TEST.VALUE:EEPROM.<<GLOBAL>>.REG_FSTAT.Bits.CCIF:1
TEST.END

-- Test Case: SwUFn_2101.008
TEST.UNIT:EEPROM
TEST.SUBPROGRAM:EEPROM_SetByte
TEST.NEW
TEST.NAME:SwUFn_2101.008
TEST.IMPORT_FAILURES:
(E) @LINE: 995 TEST.VALUE:EEPROM.<<GLOBAL>>.REG_FSTAT.Bits.CCIF:1
    >>> Unknown parameter/object name REG_FSTAT
    >>> Value Line Error - Command Ignored
(E) @LINE: 996 TEST.EXPECTED:EEPROM.<<GLOBAL>>.REG_FCCOBIX.Byte:1
    >>> Unknown parameter/object name REG_FCCOBIX
    >>> Value Line Error - Command Ignored
(E) @LINE: 997 TEST.EXPECTED:EEPROM.<<GLOBAL>>.REG_FSTAT.Byte:0x80
    >>> Unknown parameter/object name REG_FSTAT
    >>> Value Line Error - Command Ignored
(E) @LINE: 998 TEST.EXPECTED:EEPROM.<<GLOBAL>>.REG_FCCOB0.Overlap_STR.FCCOB0HISTR.Byte:0x12
    >>> Unknown parameter/object name REG_FCCOB0
    >>> Value Line Error - Command Ignored
(E) @LINE: 999 TEST.EXPECTED:EEPROM.<<GLOBAL>>.REG_FCCOB0.Overlap_STR.FCCOB0LOSTR.Byte:0
    >>> Unknown parameter/object name REG_FCCOB0
    >>> Value Line Error - Command Ignored
(E) @LINE: 1000 TEST.EXPECTED:EEPROM.<<GLOBAL>>.REG_FCCOB1.Word:10322
    >>> Unknown parameter/object name REG_FCCOB1
    >>> Value Line Error - Command Ignored
TEST.END_IMPORT_FAILURES:
TEST.NOTES:
REQ/FI
TEST.END_NOTES:
TEST.STUB:EEPROM.BackupSector
TEST.STUB:EEPROM.WriteBlock
TEST.STUB:EEPROM.SetupFCCOB
TEST.STUB:EEPROM.EraseSectorInternal
TEST.STUB:EEPROM.WriteWord
TEST.STUB:EEPROM.EEPROM_GetByte
TEST.STUB:EEPROM.EEPROM_Init
TEST.VALUE:EEPROM.<<GLOBAL>>.BackupArray[0..1]:0
TEST.VALUE:EEPROM.<<GLOBAL>>._FSTAT.Bits.CCIF:0
TEST.VALUE:EEPROM.EEPROM_SetByte.Data:0
TEST.EXPECTED:EEPROM.<<GLOBAL>>.BackupArray[0..1]:0
TEST.EXPECTED:EEPROM.EEPROM_SetByte.return:8
TEST.VALUE_USER_CODE:EEPROM.EEPROM_SetByte.Addr
<<EEPROM.EEPROM_SetByte.Addr>> = ( (word *)0x00100300UL );
TEST.END_VALUE_USER_CODE:
TEST.END

-- Test Case: SwUFn_2101.009
TEST.UNIT:EEPROM
TEST.SUBPROGRAM:EEPROM_SetByte
TEST.NEW
TEST.NAME:SwUFn_2101.009
TEST.IMPORT_FAILURES:
(E) @LINE: 1055 TEST.VALUE:EEPROM.<<GLOBAL>>.REG_FSTAT.Bits.CCIF:1
    >>> Unknown parameter/object name REG_FSTAT
    >>> Value Line Error - Command Ignored
(E) @LINE: 1056 TEST.EXPECTED:EEPROM.<<GLOBAL>>.REG_FCCOBIX.Byte:1
    >>> Unknown parameter/object name REG_FCCOBIX
    >>> Value Line Error - Command Ignored
(E) @LINE: 1057 TEST.EXPECTED:EEPROM.<<GLOBAL>>.REG_FSTAT.Byte:0x80
    >>> Unknown parameter/object name REG_FSTAT
    >>> Value Line Error - Command Ignored
(E) @LINE: 1058 TEST.EXPECTED:EEPROM.<<GLOBAL>>.REG_FCCOB0.Overlap_STR.FCCOB0HISTR.Byte:0x12
    >>> Unknown parameter/object name REG_FCCOB0
    >>> Value Line Error - Command Ignored
(E) @LINE: 1059 TEST.EXPECTED:EEPROM.<<GLOBAL>>.REG_FCCOB0.Overlap_STR.FCCOB0LOSTR.Byte:0
    >>> Unknown parameter/object name REG_FCCOB0
    >>> Value Line Error - Command Ignored
(E) @LINE: 1060 TEST.EXPECTED:EEPROM.<<GLOBAL>>.REG_FCCOB1.Word:10322
    >>> Unknown parameter/object name REG_FCCOB1
    >>> Value Line Error - Command Ignored
TEST.END_IMPORT_FAILURES:
TEST.NOTES:
REQ/FI
TEST.END_NOTES:
TEST.STUB:EEPROM.BackupSector
TEST.STUB:EEPROM.WriteBlock
TEST.STUB:EEPROM.SetupFCCOB
TEST.STUB:EEPROM.EraseSectorInternal
TEST.STUB:EEPROM.WriteWord
TEST.STUB:EEPROM.EEPROM_GetByte
TEST.STUB:EEPROM.EEPROM_Init
TEST.VALUE:EEPROM.<<GLOBAL>>.BackupArray[0..1]:0
TEST.VALUE:EEPROM.<<GLOBAL>>._FSTAT.Bits.CCIF:1
TEST.VALUE:EEPROM.EEPROM_SetByte.Data:0
TEST.EXPECTED:EEPROM.<<GLOBAL>>.BackupArray[0..1]:0
TEST.EXPECTED:EEPROM.EEPROM_SetByte.return:0
TEST.VALUE_USER_CODE:EEPROM.EEPROM_SetByte.Addr
<<EEPROM.EEPROM_SetByte.Addr>> = ( (word *)0x001003FFUL );
TEST.END_VALUE_USER_CODE:
TEST.END

-- Test Case: SwUFn_2101.010
TEST.UNIT:EEPROM
TEST.SUBPROGRAM:EEPROM_SetByte
TEST.NEW
TEST.NAME:SwUFn_2101.010
TEST.NOTES:
REQ/FI
TEST.END_NOTES:
TEST.STUB:EEPROM.BackupSector
TEST.STUB:EEPROM.WriteBlock
TEST.STUB:EEPROM.SetupFCCOB
TEST.STUB:EEPROM.EraseSectorInternal
TEST.STUB:EEPROM.WriteWord
TEST.STUB:EEPROM.EEPROM_GetByte
TEST.STUB:EEPROM.EEPROM_Init
TEST.VALUE:EEPROM.<<GLOBAL>>.BackupArray[0..1]:0
TEST.VALUE:EEPROM.<<GLOBAL>>._FSTAT.Bits.CCIF:1
TEST.VALUE:EEPROM.EraseSectorInternal.return:1
TEST.VALUE:EEPROM.EEPROM_SetByte.Data:0
TEST.EXPECTED:EEPROM.<<GLOBAL>>.BackupArray[0..1]:0
TEST.EXPECTED:EEPROM.EEPROM_SetByte.return:1
TEST.VALUE_USER_CODE:EEPROM.EEPROM_SetByte.Addr
<<EEPROM.EEPROM_SetByte.Addr>> = ( (word *)0x001003F0UL );
TEST.END_VALUE_USER_CODE:
TEST.END

-- Subprogram: EraseSectorInternal

-- Test Case: SwUFn_2106.001
TEST.UNIT:EEPROM
TEST.SUBPROGRAM:EraseSectorInternal
TEST.NEW
TEST.NAME:SwUFn_2106.001
TEST.NOTES:
REQ/BA
TEST.END_NOTES:
TEST.STUB:EEPROM.BackupSector
TEST.STUB:EEPROM.WriteBlock
TEST.STUB:EEPROM.SetupFCCOB
TEST.STUB:EEPROM.WriteWord
TEST.STUB:EEPROM.EEPROM_SetByte
TEST.STUB:EEPROM.EEPROM_GetByte
TEST.STUB:EEPROM.EEPROM_Init
TEST.VALUE:EEPROM.<<GLOBAL>>._FSTAT.Byte:0
TEST.VALUE:EEPROM.<<GLOBAL>>._FSTAT.Bits.CCIF:0
TEST.VALUE:EEPROM.EraseSectorInternal.Addr:<<malloc 1>>
TEST.VALUE:EEPROM.EraseSectorInternal.Addr[0]:0
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FCCOBIX.Byte:0
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FSTAT.Byte:0
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FCCOB0.Overlap_STR.FCCOB0HISTR.Byte:0
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FCCOB0.Overlap_STR.FCCOB0LOSTR.Byte:0
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FCCOB1.Word:0
TEST.EXPECTED:EEPROM.EraseSectorInternal.return:8
TEST.END

-- Test Case: SwUFn_2106.001
TEST.UNIT:EEPROM
TEST.SUBPROGRAM:EraseSectorInternal
TEST.ADD
TEST.NAME:SwUFn_2106.001
TEST.VALUE:EEPROM.<<GLOBAL>>.REG_FSTAT.Bits.CCIF:-1
TEST.EXPECTED:EEPROM.<<GLOBAL>>.REG_FCCOBIX.Byte:1
TEST.EXPECTED:EEPROM.<<GLOBAL>>.REG_FSTAT.Byte:0x80
TEST.EXPECTED:EEPROM.<<GLOBAL>>.REG_FCCOB0.Overlap_STR.FCCOB0HISTR.Byte:0x12
TEST.EXPECTED:EEPROM.<<GLOBAL>>.REG_FCCOB0.Overlap_STR.FCCOB0LOSTR.Byte:0
TEST.EXPECTED:EEPROM.<<GLOBAL>>.REG_FCCOB1.Word:10314
TEST.END

-- Test Case: SwUFn_2106.002
TEST.UNIT:EEPROM
TEST.SUBPROGRAM:EraseSectorInternal
TEST.NEW
TEST.NAME:SwUFn_2106.002
TEST.NOTES:
REQ/BA
TEST.END_NOTES:
TEST.STUB:EEPROM.BackupSector
TEST.STUB:EEPROM.WriteBlock
TEST.STUB:EEPROM.SetupFCCOB
TEST.STUB:EEPROM.WriteWord
TEST.STUB:EEPROM.EEPROM_SetByte
TEST.STUB:EEPROM.EEPROM_GetByte
TEST.STUB:EEPROM.EEPROM_Init
TEST.VALUE:EEPROM.<<GLOBAL>>._FSTAT.Byte:127
TEST.VALUE:EEPROM.<<GLOBAL>>._FSTAT.Bits.CCIF:0
TEST.VALUE:EEPROM.EraseSectorInternal.Addr:<<malloc 1>>
TEST.VALUE:EEPROM.EraseSectorInternal.Addr[0]:2147483647
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FCCOBIX.Byte:0
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FSTAT.Byte:127
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FCCOB0.Overlap_STR.FCCOB0HISTR.Byte:0
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FCCOB0.Overlap_STR.FCCOB0LOSTR.Byte:0
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FCCOB1.Word:0
TEST.EXPECTED:EEPROM.EraseSectorInternal.return:8
TEST.END

-- Test Case: SwUFn_2106.002
TEST.UNIT:EEPROM
TEST.SUBPROGRAM:EraseSectorInternal
TEST.ADD
TEST.NAME:SwUFn_2106.002
TEST.VALUE:EEPROM.<<GLOBAL>>.REG_FSTAT.Bits.CCIF:0
TEST.EXPECTED:EEPROM.<<GLOBAL>>.REG_FCCOBIX.Byte:0
TEST.EXPECTED:EEPROM.<<GLOBAL>>.REG_FSTAT.Byte:0x0
TEST.EXPECTED:EEPROM.<<GLOBAL>>.REG_FCCOB0.Overlap_STR.FCCOB0HISTR.Byte:0x0
TEST.EXPECTED:EEPROM.<<GLOBAL>>.REG_FCCOB0.Overlap_STR.FCCOB0LOSTR.Byte:0
TEST.EXPECTED:EEPROM.<<GLOBAL>>.REG_FCCOB1.Word:0
TEST.END

-- Test Case: SwUFn_2106.003
TEST.UNIT:EEPROM
TEST.SUBPROGRAM:EraseSectorInternal
TEST.NEW
TEST.NAME:SwUFn_2106.003
TEST.NOTES:
REQ/BA
TEST.END_NOTES:
TEST.STUB:EEPROM.BackupSector
TEST.STUB:EEPROM.WriteBlock
TEST.STUB:EEPROM.SetupFCCOB
TEST.STUB:EEPROM.WriteWord
TEST.STUB:EEPROM.EEPROM_SetByte
TEST.STUB:EEPROM.EEPROM_GetByte
TEST.STUB:EEPROM.EEPROM_Init
TEST.VALUE:EEPROM.<<GLOBAL>>._FSTAT.Byte:255
TEST.VALUE:EEPROM.<<GLOBAL>>._FSTAT.Bits.CCIF:1
TEST.VALUE:EEPROM.EraseSectorInternal.Addr:<<malloc 1>>
TEST.VALUE:EEPROM.EraseSectorInternal.Addr[0]:4294967295
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FCCOBIX.Byte:1
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FSTAT.Byte:128
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FCCOB0.Overlap_STR.FCCOB0HISTR.Byte:18
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FCCOB0.Overlap_STR.FCCOB0LOSTR.Byte:0
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FCCOB1.Word:7188
TEST.EXPECTED:EEPROM.EraseSectorInternal.return:0
TEST.END

-- Test Case: SwUFn_2106.003
TEST.UNIT:EEPROM
TEST.SUBPROGRAM:EraseSectorInternal
TEST.ADD
TEST.NAME:SwUFn_2106.003
TEST.VALUE:EEPROM.<<GLOBAL>>.REG_FSTAT.Bits.CCIF:1
TEST.EXPECTED:EEPROM.<<GLOBAL>>.REG_FCCOBIX.Byte:1
TEST.EXPECTED:EEPROM.<<GLOBAL>>.REG_FSTAT.Byte:0x80
TEST.EXPECTED:EEPROM.<<GLOBAL>>.REG_FCCOB0.Overlap_STR.FCCOB0HISTR.Byte:0x12
TEST.EXPECTED:EEPROM.<<GLOBAL>>.REG_FCCOB0.Overlap_STR.FCCOB0LOSTR.Byte:0
TEST.EXPECTED:EEPROM.<<GLOBAL>>.REG_FCCOB1.Word:10322
TEST.END

-- Test Case: SwUFn_2106.004
TEST.UNIT:EEPROM
TEST.SUBPROGRAM:EraseSectorInternal
TEST.NEW
TEST.NAME:SwUFn_2106.004
TEST.NOTES:
REQ/FI
TEST.END_NOTES:
TEST.STUB:EEPROM.BackupSector
TEST.STUB:EEPROM.WriteBlock
TEST.STUB:EEPROM.SetupFCCOB
TEST.STUB:EEPROM.WriteWord
TEST.STUB:EEPROM.EEPROM_SetByte
TEST.STUB:EEPROM.EEPROM_GetByte
TEST.STUB:EEPROM.EEPROM_Init
TEST.VALUE:EEPROM.<<GLOBAL>>._FSTAT.Byte:-1
TEST.VALUE:EEPROM.<<GLOBAL>>._FSTAT.Bits.CCIF:-1
TEST.VALUE:EEPROM.EraseSectorInternal.Addr:<<malloc 1>>
TEST.VALUE:EEPROM.EraseSectorInternal.Addr[0]:-1
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FCCOBIX.Byte:1
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FSTAT.Byte:128
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FCCOB0.Overlap_STR.FCCOB0HISTR.Byte:18
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FCCOB0.Overlap_STR.FCCOB0LOSTR.Byte:0
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FCCOB1.Word:7180
TEST.EXPECTED:EEPROM.EraseSectorInternal.return:0
TEST.END

-- Test Case: SwUFn_2106.004
TEST.UNIT:EEPROM
TEST.SUBPROGRAM:EraseSectorInternal
TEST.ADD
TEST.NAME:SwUFn_2106.004
TEST.VALUE:EEPROM.<<GLOBAL>>.REG_FSTAT.Bits.CCIF:1
TEST.EXPECTED:EEPROM.<<GLOBAL>>.REG_FCCOBIX.Byte:1
TEST.EXPECTED:EEPROM.<<GLOBAL>>.REG_FSTAT.Byte:0x80
TEST.EXPECTED:EEPROM.<<GLOBAL>>.REG_FCCOB0.Overlap_STR.FCCOB0HISTR.Byte:0x12
TEST.EXPECTED:EEPROM.<<GLOBAL>>.REG_FCCOB0.Overlap_STR.FCCOB0LOSTR.Byte:0
TEST.EXPECTED:EEPROM.<<GLOBAL>>.REG_FCCOB1.Word:10322
TEST.END

-- Test Case: SwUFn_2106.005
TEST.UNIT:EEPROM
TEST.SUBPROGRAM:EraseSectorInternal
TEST.NEW
TEST.NAME:SwUFn_2106.005
TEST.NOTES:
REQ/FI
TEST.END_NOTES:
TEST.STUB:EEPROM.BackupSector
TEST.STUB:EEPROM.WriteBlock
TEST.STUB:EEPROM.SetupFCCOB
TEST.STUB:EEPROM.WriteWord
TEST.STUB:EEPROM.EEPROM_SetByte
TEST.STUB:EEPROM.EEPROM_GetByte
TEST.STUB:EEPROM.EEPROM_Init
TEST.VALUE:EEPROM.<<GLOBAL>>._FSTAT.Byte:256
TEST.VALUE:EEPROM.<<GLOBAL>>._FSTAT.Bits.CCIF:2
TEST.VALUE:EEPROM.EraseSectorInternal.Addr:<<malloc 1>>
TEST.VALUE:EEPROM.EraseSectorInternal.Addr[0]:4294967296
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FCCOBIX.Byte:0
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FSTAT.Byte:0
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FCCOB0.Overlap_STR.FCCOB0HISTR.Byte:0
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FCCOB0.Overlap_STR.FCCOB0LOSTR.Byte:0
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FCCOB1.Word:0
TEST.EXPECTED:EEPROM.EraseSectorInternal.return:8
TEST.END

-- Test Case: SwUFn_2106.005
TEST.UNIT:EEPROM
TEST.SUBPROGRAM:EraseSectorInternal
TEST.ADD
TEST.NAME:SwUFn_2106.005
TEST.VALUE:EEPROM.<<GLOBAL>>.REG_FSTAT.Bits.CCIF:1
TEST.EXPECTED:EEPROM.<<GLOBAL>>.REG_FCCOBIX.Byte:1
TEST.EXPECTED:EEPROM.<<GLOBAL>>.REG_FSTAT.Byte:0x80
TEST.EXPECTED:EEPROM.<<GLOBAL>>.REG_FCCOB0.Overlap_STR.FCCOB0HISTR.Byte:0x12
TEST.EXPECTED:EEPROM.<<GLOBAL>>.REG_FCCOB0.Overlap_STR.FCCOB0LOSTR.Byte:0
TEST.EXPECTED:EEPROM.<<GLOBAL>>.REG_FCCOB1.Word:10322
TEST.END

-- Test Case: SwUFn_2106.006
TEST.UNIT:EEPROM
TEST.SUBPROGRAM:EraseSectorInternal
TEST.NEW
TEST.NAME:SwUFn_2106.006
TEST.NOTES:
REQ/FI
TEST.END_NOTES:
TEST.STUB:EEPROM.BackupSector
TEST.STUB:EEPROM.WriteBlock
TEST.STUB:EEPROM.SetupFCCOB
TEST.STUB:EEPROM.WriteWord
TEST.STUB:EEPROM.EEPROM_SetByte
TEST.STUB:EEPROM.EEPROM_GetByte
TEST.STUB:EEPROM.EEPROM_Init
TEST.VALUE:EEPROM.<<GLOBAL>>._FSTAT.Byte:300
TEST.VALUE:EEPROM.<<GLOBAL>>._FSTAT.Bits.CCIF:100
TEST.VALUE:EEPROM.EraseSectorInternal.Addr:<<malloc 1>>
TEST.VALUE:EEPROM.EraseSectorInternal.Addr[0]:5421851548
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FCCOBIX.Byte:0
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FSTAT.Byte:44
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FCCOB0.Overlap_STR.FCCOB0HISTR.Byte:0
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FCCOB0.Overlap_STR.FCCOB0LOSTR.Byte:0
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FCCOB1.Word:0
TEST.EXPECTED:EEPROM.EraseSectorInternal.return:8
TEST.END

-- Test Case: SwUFn_2106.007
TEST.UNIT:EEPROM
TEST.SUBPROGRAM:EraseSectorInternal
TEST.NEW
TEST.NAME:SwUFn_2106.007
TEST.NOTES:
REQ/FI
TEST.END_NOTES:
TEST.STUB:EEPROM.BackupSector
TEST.STUB:EEPROM.WriteBlock
TEST.STUB:EEPROM.SetupFCCOB
TEST.STUB:EEPROM.WriteWord
TEST.STUB:EEPROM.EEPROM_SetByte
TEST.STUB:EEPROM.EEPROM_GetByte
TEST.STUB:EEPROM.EEPROM_Init
TEST.VALUE:EEPROM.<<GLOBAL>>._FSTAT.Byte:451
TEST.VALUE:EEPROM.<<GLOBAL>>._FSTAT.Bits.CCIF:150
TEST.VALUE:EEPROM.EraseSectorInternal.Addr:<<malloc 1>>
TEST.VALUE:EEPROM.EraseSectorInternal.Addr[0]:7236942574
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FCCOBIX.Byte:0
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FSTAT.Byte:67
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FCCOB0.Overlap_STR.FCCOB0HISTR.Byte:0
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FCCOB0.Overlap_STR.FCCOB0LOSTR.Byte:0
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FCCOB1.Word:0
TEST.EXPECTED:EEPROM.EraseSectorInternal.return:8
TEST.END

-- Subprogram: SetupFCCOB

-- Test Case: SwUFn_2108.001
TEST.UNIT:EEPROM
TEST.SUBPROGRAM:SetupFCCOB
TEST.NEW
TEST.NAME:SwUFn_2108.001
TEST.NOTES:
REQ/EC
TEST.END_NOTES:
TEST.VALUE:<<OPTIONS>>.EVENT_LIMIT:10
TEST.STUB:EEPROM.BackupSector
TEST.STUB:EEPROM.WriteBlock
TEST.STUB:EEPROM.EraseSectorInternal
TEST.STUB:EEPROM.WriteWord
TEST.STUB:EEPROM.EEPROM_SetByte
TEST.STUB:EEPROM.EEPROM_GetByte
TEST.STUB:EEPROM.EEPROM_Init
TEST.VALUE:EEPROM.SetupFCCOB.PhraseAddr:0
TEST.VALUE:EEPROM.SetupFCCOB.From:0
TEST.VALUE:EEPROM.SetupFCCOB.To:0
TEST.VALUE:EEPROM.SetupFCCOB.Data:<<malloc 1>>
TEST.VALUE:EEPROM.SetupFCCOB.Data[0]:0x0
TEST.VALUE:EEPROM.SetupFCCOB.pIndex:<<malloc 1>>
TEST.VALUE:EEPROM.SetupFCCOB.pIndex[0]:0x0
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FCCOBIX.Byte:2
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FSTAT.Byte:48
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FCCOB0.Overlap_STR.FCCOB0HISTR.Byte:17
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FCCOB0.Overlap_STR.FCCOB0LOSTR.Byte:0
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FCCOB1.Word:0
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FCCOB2.Word:0
TEST.EXPECTED:EEPROM.SetupFCCOB.pIndex[0]:0x2
TEST.EXPECTED:EEPROM.SetupFCCOB.return:0
TEST.END

-- Test Case: SwUFn_2108.002
TEST.UNIT:EEPROM
TEST.SUBPROGRAM:SetupFCCOB
TEST.NEW
TEST.NAME:SwUFn_2108.002
TEST.NOTES:
REQ/EC
TEST.END_NOTES:
TEST.VALUE:<<OPTIONS>>.EVENT_LIMIT:10
TEST.STUB:EEPROM.BackupSector
TEST.STUB:EEPROM.WriteBlock
TEST.STUB:EEPROM.EraseSectorInternal
TEST.STUB:EEPROM.WriteWord
TEST.STUB:EEPROM.EEPROM_SetByte
TEST.STUB:EEPROM.EEPROM_GetByte
TEST.STUB:EEPROM.EEPROM_Init
TEST.VALUE:EEPROM.SetupFCCOB.PhraseAddr:0x7FFFFFFF
TEST.VALUE:EEPROM.SetupFCCOB.From:0x7FFF
TEST.VALUE:EEPROM.SetupFCCOB.To:0x7FFF
TEST.VALUE:EEPROM.SetupFCCOB.Data:<<malloc 1>>
TEST.VALUE:EEPROM.SetupFCCOB.Data[0]:0x7FFF
TEST.VALUE:EEPROM.SetupFCCOB.pIndex:<<malloc 1>>
TEST.VALUE:EEPROM.SetupFCCOB.pIndex[0]:0x7FFFF
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FCCOBIX.Byte:2
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FSTAT.Byte:48
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FCCOB0.Overlap_STR.FCCOB0HISTR.Byte:17
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FCCOB0.Overlap_STR.FCCOB0LOSTR.Byte:255
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FCCOB1.Word:65535
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FCCOB2.Word:0
TEST.EXPECTED:EEPROM.SetupFCCOB.pIndex[0]:0x7FFF
TEST.EXPECTED:EEPROM.SetupFCCOB.return:0
TEST.END

-- Test Case: SwUFn_2108.003
TEST.UNIT:EEPROM
TEST.SUBPROGRAM:SetupFCCOB
TEST.NEW
TEST.NAME:SwUFn_2108.003
TEST.NOTES:
REQ/BA
TEST.END_NOTES:
TEST.VALUE:<<OPTIONS>>.EVENT_LIMIT:10
TEST.STUB:EEPROM.BackupSector
TEST.STUB:EEPROM.WriteBlock
TEST.STUB:EEPROM.EraseSectorInternal
TEST.STUB:EEPROM.WriteWord
TEST.STUB:EEPROM.EEPROM_SetByte
TEST.STUB:EEPROM.EEPROM_GetByte
TEST.STUB:EEPROM.EEPROM_Init
TEST.VALUE:EEPROM.SetupFCCOB.PhraseAddr:0xFFFFFFFF
TEST.VALUE:EEPROM.SetupFCCOB.From:0xFFFF
TEST.VALUE:EEPROM.SetupFCCOB.To:0xFFFF
TEST.VALUE:EEPROM.SetupFCCOB.Data:<<malloc 1>>
TEST.VALUE:EEPROM.SetupFCCOB.Data[0]:0xFFFF
TEST.VALUE:EEPROM.SetupFCCOB.pIndex:<<malloc 1>>
TEST.VALUE:EEPROM.SetupFCCOB.pIndex[0]:0xFFFF
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FCCOBIX.Byte:2
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FSTAT.Byte:48
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FCCOB0.Overlap_STR.FCCOB0HISTR.Byte:17
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FCCOB0.Overlap_STR.FCCOB0LOSTR.Byte:255
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FCCOB1.Word:65535
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FCCOB2.Word:0
TEST.EXPECTED:EEPROM.SetupFCCOB.pIndex[0]:0xFFFF
TEST.EXPECTED:EEPROM.SetupFCCOB.return:0
TEST.END

-- Subprogram: WriteBlock

-- Test Case: SwUFn_2105.001
TEST.UNIT:EEPROM
TEST.SUBPROGRAM:WriteBlock
TEST.NEW
TEST.NAME:SwUFn_2105.001
TEST.IMPORT_FAILURES:
(E) @LINE: 1402 TEST.VALUE:EEPROM.<<GLOBAL>>.REG_FSTAT.Bits.CCIF:-1
    >>> Unknown parameter/object name REG_FSTAT
    >>> Value Line Error - Command Ignored
(E) @LINE: 1403 TEST.VALUE:EEPROM.<<GLOBAL>>.REG_FSTAT.MergedBits.grpMGSTAT:-1
    >>> Unknown parameter/object name REG_FSTAT
    >>> Value Line Error - Command Ignored
(E) @LINE: 1404 TEST.EXPECTED:EEPROM.<<GLOBAL>>.REG_FCCOBIX.Byte:0
    >>> Unknown parameter/object name REG_FCCOBIX
    >>> Value Line Error - Command Ignored
(E) @LINE: 1405 TEST.EXPECTED:EEPROM.<<GLOBAL>>.REG_FSTAT.Byte:0x83
    >>> Unknown parameter/object name REG_FSTAT
    >>> Value Line Error - Command Ignored
(E) @LINE: 1406 TEST.EXPECTED:EEPROM.<<GLOBAL>>.REG_FCCOB0.Overlap_STR.FCCOB0HISTR.Byte:0
    >>> Unknown parameter/object name REG_FCCOB0
    >>> Value Line Error - Command Ignored
(E) @LINE: 1407 TEST.EXPECTED:EEPROM.<<GLOBAL>>.REG_FCCOB0.Overlap_STR.FCCOB0LOSTR.Byte:0
    >>> Unknown parameter/object name REG_FCCOB0
    >>> Value Line Error - Command Ignored
(E) @LINE: 1408 TEST.EXPECTED:EEPROM.<<GLOBAL>>.REG_FCCOB1.Word:0
    >>> Unknown parameter/object name REG_FCCOB1
    >>> Value Line Error - Command Ignored
(E) @LINE: 1409 TEST.EXPECTED:EEPROM.<<GLOBAL>>.REG_FCCOB2.Word:0
    >>> Unknown parameter/object name REG_FCCOB2
    >>> Value Line Error - Command Ignored
TEST.END_IMPORT_FAILURES:
TEST.NOTES:
REQ/BA
TEST.END_NOTES:
TEST.STUB:EEPROM.BackupSector
TEST.STUB:EEPROM.SetupFCCOB
TEST.STUB:EEPROM.EraseSectorInternal
TEST.STUB:EEPROM.WriteWord
TEST.STUB:EEPROM.EEPROM_SetByte
TEST.STUB:EEPROM.EEPROM_GetByte
TEST.STUB:EEPROM.EEPROM_Init
TEST.VALUE:EEPROM.<<GLOBAL>>._FSTAT.Byte:0
TEST.VALUE:EEPROM.<<GLOBAL>>._FSTAT.Bits.CCIF:0
TEST.VALUE:EEPROM.<<GLOBAL>>._FSTAT.MergedBits.grpMGSTAT:0
TEST.VALUE:EEPROM.WriteBlock.Addr:<<malloc 1>>
TEST.VALUE:EEPROM.WriteBlock.Addr[0]:0
TEST.VALUE:EEPROM.WriteBlock.From:0
TEST.VALUE:EEPROM.WriteBlock.To:0
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FSTAT.Byte:0
TEST.EXPECTED:EEPROM.WriteBlock.return:0
TEST.END

-- Test Case: SwUFn_2105.001
TEST.UNIT:EEPROM
TEST.SUBPROGRAM:WriteBlock
TEST.ADD
TEST.NAME:SwUFn_2105.001
TEST.VALUE:EEPROM.<<GLOBAL>>.REG_FSTAT.Bits.CCIF:-1
TEST.VALUE:EEPROM.<<GLOBAL>>.REG_FSTAT.MergedBits.grpMGSTAT:-1
TEST.EXPECTED:EEPROM.<<GLOBAL>>.REG_FCCOBIX.Byte:0
TEST.EXPECTED:EEPROM.<<GLOBAL>>.REG_FSTAT.Byte:0x83
TEST.EXPECTED:EEPROM.<<GLOBAL>>.REG_FCCOB0.Overlap_STR.FCCOB0HISTR.Byte:0
TEST.EXPECTED:EEPROM.<<GLOBAL>>.REG_FCCOB0.Overlap_STR.FCCOB0LOSTR.Byte:0
TEST.EXPECTED:EEPROM.<<GLOBAL>>.REG_FCCOB1.Word:0
TEST.EXPECTED:EEPROM.<<GLOBAL>>.REG_FCCOB2.Word:0
TEST.END

-- Test Case: SwUFn_2105.002
TEST.UNIT:EEPROM
TEST.SUBPROGRAM:WriteBlock
TEST.NEW
TEST.NAME:SwUFn_2105.002
TEST.IMPORT_FAILURES:
(E) @LINE: 1469 TEST.VALUE:EEPROM.<<GLOBAL>>.REG_FSTAT.Bits.CCIF:0
    >>> Unknown parameter/object name REG_FSTAT
    >>> Value Line Error - Command Ignored
(E) @LINE: 1470 TEST.VALUE:EEPROM.<<GLOBAL>>.REG_FSTAT.MergedBits.grpMGSTAT:0
    >>> Unknown parameter/object name REG_FSTAT
    >>> Value Line Error - Command Ignored
(E) @LINE: 1471 TEST.EXPECTED:EEPROM.<<GLOBAL>>.REG_FCCOBIX.Byte:0
    >>> Unknown parameter/object name REG_FCCOBIX
    >>> Value Line Error - Command Ignored
(E) @LINE: 1472 TEST.EXPECTED:EEPROM.<<GLOBAL>>.REG_FSTAT.Byte:0x0
    >>> Unknown parameter/object name REG_FSTAT
    >>> Value Line Error - Command Ignored
(E) @LINE: 1473 TEST.EXPECTED:EEPROM.<<GLOBAL>>.REG_FCCOB0.Overlap_STR.FCCOB0HISTR.Byte:0
    >>> Unknown parameter/object name REG_FCCOB0
    >>> Value Line Error - Command Ignored
(E) @LINE: 1474 TEST.EXPECTED:EEPROM.<<GLOBAL>>.REG_FCCOB0.Overlap_STR.FCCOB0LOSTR.Byte:0
    >>> Unknown parameter/object name REG_FCCOB0
    >>> Value Line Error - Command Ignored
(E) @LINE: 1475 TEST.EXPECTED:EEPROM.<<GLOBAL>>.REG_FCCOB1.Word:0
    >>> Unknown parameter/object name REG_FCCOB1
    >>> Value Line Error - Command Ignored
(E) @LINE: 1476 TEST.EXPECTED:EEPROM.<<GLOBAL>>.REG_FCCOB2.Word:0
    >>> Unknown parameter/object name REG_FCCOB2
    >>> Value Line Error - Command Ignored
TEST.END_IMPORT_FAILURES:
TEST.NOTES:
REQ/BA
TEST.END_NOTES:
TEST.STUB:EEPROM.BackupSector
TEST.STUB:EEPROM.SetupFCCOB
TEST.STUB:EEPROM.EraseSectorInternal
TEST.STUB:EEPROM.WriteWord
TEST.STUB:EEPROM.EEPROM_SetByte
TEST.STUB:EEPROM.EEPROM_GetByte
TEST.STUB:EEPROM.EEPROM_Init
TEST.VALUE:EEPROM.<<GLOBAL>>._FSTAT.Byte:127
TEST.VALUE:EEPROM.<<GLOBAL>>._FSTAT.Bits.CCIF:0
TEST.VALUE:EEPROM.<<GLOBAL>>._FSTAT.MergedBits.grpMGSTAT:1
TEST.VALUE:EEPROM.WriteBlock.Addr:<<malloc 1>>
TEST.VALUE:EEPROM.WriteBlock.Addr[0]:2147483647
TEST.VALUE:EEPROM.WriteBlock.From:32767
TEST.VALUE:EEPROM.WriteBlock.To:32767
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FSTAT.Byte:125
TEST.EXPECTED:EEPROM.WriteBlock.return:0
TEST.END

-- Test Case: SwUFn_2105.002
TEST.UNIT:EEPROM
TEST.SUBPROGRAM:WriteBlock
TEST.ADD
TEST.NAME:SwUFn_2105.002
TEST.VALUE:EEPROM.<<GLOBAL>>.REG_FSTAT.Bits.CCIF:0
TEST.VALUE:EEPROM.<<GLOBAL>>.REG_FSTAT.MergedBits.grpMGSTAT:0
TEST.EXPECTED:EEPROM.<<GLOBAL>>.REG_FCCOBIX.Byte:0
TEST.EXPECTED:EEPROM.<<GLOBAL>>.REG_FSTAT.Byte:0x0
TEST.EXPECTED:EEPROM.<<GLOBAL>>.REG_FCCOB0.Overlap_STR.FCCOB0HISTR.Byte:0
TEST.EXPECTED:EEPROM.<<GLOBAL>>.REG_FCCOB0.Overlap_STR.FCCOB0LOSTR.Byte:0
TEST.EXPECTED:EEPROM.<<GLOBAL>>.REG_FCCOB1.Word:0
TEST.EXPECTED:EEPROM.<<GLOBAL>>.REG_FCCOB2.Word:0
TEST.END

-- Test Case: SwUFn_2105.003
TEST.UNIT:EEPROM
TEST.SUBPROGRAM:WriteBlock
TEST.NEW
TEST.NAME:SwUFn_2105.003
TEST.IMPORT_FAILURES:
(E) @LINE: 1536 TEST.VALUE:EEPROM.<<GLOBAL>>.REG_FSTAT.Bits.CCIF:1
    >>> Unknown parameter/object name REG_FSTAT
    >>> Value Line Error - Command Ignored
(E) @LINE: 1537 TEST.VALUE:EEPROM.<<GLOBAL>>.REG_FSTAT.MergedBits.grpMGSTAT:1
    >>> Unknown parameter/object name REG_FSTAT
    >>> Value Line Error - Command Ignored
(E) @LINE: 1538 TEST.EXPECTED:EEPROM.<<GLOBAL>>.REG_FCCOBIX.Byte:0
    >>> Unknown parameter/object name REG_FCCOBIX
    >>> Value Line Error - Command Ignored
(E) @LINE: 1539 TEST.EXPECTED:EEPROM.<<GLOBAL>>.REG_FSTAT.Byte:0x81
    >>> Unknown parameter/object name REG_FSTAT
    >>> Value Line Error - Command Ignored
(E) @LINE: 1540 TEST.EXPECTED:EEPROM.<<GLOBAL>>.REG_FCCOB0.Overlap_STR.FCCOB0HISTR.Byte:0
    >>> Unknown parameter/object name REG_FCCOB0
    >>> Value Line Error - Command Ignored
(E) @LINE: 1541 TEST.EXPECTED:EEPROM.<<GLOBAL>>.REG_FCCOB0.Overlap_STR.FCCOB0LOSTR.Byte:0
    >>> Unknown parameter/object name REG_FCCOB0
    >>> Value Line Error - Command Ignored
(E) @LINE: 1542 TEST.EXPECTED:EEPROM.<<GLOBAL>>.REG_FCCOB1.Word:0
    >>> Unknown parameter/object name REG_FCCOB1
    >>> Value Line Error - Command Ignored
(E) @LINE: 1543 TEST.EXPECTED:EEPROM.<<GLOBAL>>.REG_FCCOB2.Word:0
    >>> Unknown parameter/object name REG_FCCOB2
    >>> Value Line Error - Command Ignored
TEST.END_IMPORT_FAILURES:
TEST.NOTES:
REQ/BA
TEST.END_NOTES:
TEST.STUB:EEPROM.BackupSector
TEST.STUB:EEPROM.SetupFCCOB
TEST.STUB:EEPROM.EraseSectorInternal
TEST.STUB:EEPROM.WriteWord
TEST.STUB:EEPROM.EEPROM_SetByte
TEST.STUB:EEPROM.EEPROM_GetByte
TEST.STUB:EEPROM.EEPROM_Init
TEST.VALUE:EEPROM.<<GLOBAL>>._FSTAT.Byte:255
TEST.VALUE:EEPROM.<<GLOBAL>>._FSTAT.Bits.CCIF:1
TEST.VALUE:EEPROM.<<GLOBAL>>._FSTAT.MergedBits.grpMGSTAT:3
TEST.VALUE:EEPROM.WriteBlock.Addr:<<malloc 1>>
TEST.VALUE:EEPROM.WriteBlock.Addr[0]:4294967295
TEST.VALUE:EEPROM.WriteBlock.From:65535
TEST.VALUE:EEPROM.WriteBlock.To:65535
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FSTAT.Byte:255
TEST.EXPECTED:EEPROM.WriteBlock.return:0
TEST.END

-- Test Case: SwUFn_2105.003
TEST.UNIT:EEPROM
TEST.SUBPROGRAM:WriteBlock
TEST.ADD
TEST.NAME:SwUFn_2105.003
TEST.VALUE:EEPROM.<<GLOBAL>>.REG_FSTAT.Bits.CCIF:1
TEST.VALUE:EEPROM.<<GLOBAL>>.REG_FSTAT.MergedBits.grpMGSTAT:1
TEST.EXPECTED:EEPROM.<<GLOBAL>>.REG_FCCOBIX.Byte:0
TEST.EXPECTED:EEPROM.<<GLOBAL>>.REG_FSTAT.Byte:0x81
TEST.EXPECTED:EEPROM.<<GLOBAL>>.REG_FCCOB0.Overlap_STR.FCCOB0HISTR.Byte:0
TEST.EXPECTED:EEPROM.<<GLOBAL>>.REG_FCCOB0.Overlap_STR.FCCOB0LOSTR.Byte:0
TEST.EXPECTED:EEPROM.<<GLOBAL>>.REG_FCCOB1.Word:0
TEST.EXPECTED:EEPROM.<<GLOBAL>>.REG_FCCOB2.Word:0
TEST.END

-- Test Case: SwUFn_2105.004
TEST.UNIT:EEPROM
TEST.SUBPROGRAM:WriteBlock
TEST.NEW
TEST.NAME:SwUFn_2105.004
TEST.IMPORT_FAILURES:
(E) @LINE: 1604 TEST.VALUE:EEPROM.<<GLOBAL>>.REG_FSTAT.Bits.CCIF:1
    >>> Unknown parameter/object name REG_FSTAT
    >>> Value Line Error - Command Ignored
(E) @LINE: 1605 TEST.VALUE:EEPROM.<<GLOBAL>>.REG_FSTAT.MergedBits.grpMGSTAT:3
    >>> Unknown parameter/object name REG_FSTAT
    >>> Value Line Error - Command Ignored
(E) @LINE: 1606 TEST.EXPECTED:EEPROM.<<GLOBAL>>.REG_FCCOBIX.Byte:0
    >>> Unknown parameter/object name REG_FCCOBIX
    >>> Value Line Error - Command Ignored
(E) @LINE: 1607 TEST.EXPECTED:EEPROM.<<GLOBAL>>.REG_FSTAT.Byte:0x83
    >>> Unknown parameter/object name REG_FSTAT
    >>> Value Line Error - Command Ignored
(E) @LINE: 1608 TEST.EXPECTED:EEPROM.<<GLOBAL>>.REG_FCCOB0.Overlap_STR.FCCOB0HISTR.Byte:0x0
    >>> Unknown parameter/object name REG_FCCOB0
    >>> Value Line Error - Command Ignored
(E) @LINE: 1609 TEST.EXPECTED:EEPROM.<<GLOBAL>>.REG_FCCOB0.Overlap_STR.FCCOB0LOSTR.Byte:0
    >>> Unknown parameter/object name REG_FCCOB0
    >>> Value Line Error - Command Ignored
(E) @LINE: 1610 TEST.EXPECTED:EEPROM.<<GLOBAL>>.REG_FCCOB1.Word:0
    >>> Unknown parameter/object name REG_FCCOB1
    >>> Value Line Error - Command Ignored
(E) @LINE: 1611 TEST.EXPECTED:EEPROM.<<GLOBAL>>.REG_FCCOB2.Word:0
    >>> Unknown parameter/object name REG_FCCOB2
    >>> Value Line Error - Command Ignored
TEST.END_IMPORT_FAILURES:
TEST.NOTES:
REQ/FI

TEST.END_NOTES:
TEST.STUB:EEPROM.BackupSector
TEST.STUB:EEPROM.SetupFCCOB
TEST.STUB:EEPROM.EraseSectorInternal
TEST.STUB:EEPROM.WriteWord
TEST.STUB:EEPROM.EEPROM_SetByte
TEST.STUB:EEPROM.EEPROM_GetByte
TEST.STUB:EEPROM.EEPROM_Init
TEST.VALUE:EEPROM.<<GLOBAL>>._FSTAT.Byte:-1
TEST.VALUE:EEPROM.<<GLOBAL>>._FSTAT.Bits.CCIF:-1
TEST.VALUE:EEPROM.<<GLOBAL>>._FSTAT.MergedBits.grpMGSTAT:-1
TEST.VALUE:EEPROM.WriteBlock.Addr:<<malloc 1>>
TEST.VALUE:EEPROM.WriteBlock.Addr[0]:-1
TEST.VALUE:EEPROM.WriteBlock.From:-1
TEST.VALUE:EEPROM.WriteBlock.To:-1
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FSTAT.Byte:255
TEST.EXPECTED:EEPROM.WriteBlock.return:0
TEST.END

-- Test Case: SwUFn_2105.004
TEST.UNIT:EEPROM
TEST.SUBPROGRAM:WriteBlock
TEST.ADD
TEST.NAME:SwUFn_2105.004
TEST.VALUE:EEPROM.<<GLOBAL>>.REG_FSTAT.Bits.CCIF:1
TEST.VALUE:EEPROM.<<GLOBAL>>.REG_FSTAT.MergedBits.grpMGSTAT:3
TEST.EXPECTED:EEPROM.<<GLOBAL>>.REG_FCCOBIX.Byte:0
TEST.EXPECTED:EEPROM.<<GLOBAL>>.REG_FSTAT.Byte:0x83
TEST.EXPECTED:EEPROM.<<GLOBAL>>.REG_FCCOB0.Overlap_STR.FCCOB0HISTR.Byte:0x0
TEST.EXPECTED:EEPROM.<<GLOBAL>>.REG_FCCOB0.Overlap_STR.FCCOB0LOSTR.Byte:0
TEST.EXPECTED:EEPROM.<<GLOBAL>>.REG_FCCOB1.Word:0
TEST.EXPECTED:EEPROM.<<GLOBAL>>.REG_FCCOB2.Word:0
TEST.END

-- Test Case: SwUFn_2105.005
TEST.UNIT:EEPROM
TEST.SUBPROGRAM:WriteBlock
TEST.NEW
TEST.NAME:SwUFn_2105.005
TEST.IMPORT_FAILURES:
(E) @LINE: 1672 TEST.VALUE:EEPROM.<<GLOBAL>>.REG_FSTAT.Bits.CCIF:2
    >>> Unknown parameter/object name REG_FSTAT
    >>> Value Line Error - Command Ignored
(E) @LINE: 1673 TEST.VALUE:EEPROM.<<GLOBAL>>.REG_FSTAT.MergedBits.grpMGSTAT:4
    >>> Unknown parameter/object name REG_FSTAT
    >>> Value Line Error - Command Ignored
(E) @LINE: 1674 TEST.EXPECTED:EEPROM.<<GLOBAL>>.REG_FCCOBIX.Byte:0
    >>> Unknown parameter/object name REG_FCCOBIX
    >>> Value Line Error - Command Ignored
(E) @LINE: 1675 TEST.EXPECTED:EEPROM.<<GLOBAL>>.REG_FSTAT.Byte:0x0
    >>> Unknown parameter/object name REG_FSTAT
    >>> Value Line Error - Command Ignored
(E) @LINE: 1676 TEST.EXPECTED:EEPROM.<<GLOBAL>>.REG_FCCOB0.Overlap_STR.FCCOB0HISTR.Byte:0x0
    >>> Unknown parameter/object name REG_FCCOB0
    >>> Value Line Error - Command Ignored
(E) @LINE: 1677 TEST.EXPECTED:EEPROM.<<GLOBAL>>.REG_FCCOB0.Overlap_STR.FCCOB0LOSTR.Byte:0
    >>> Unknown parameter/object name REG_FCCOB0
    >>> Value Line Error - Command Ignored
(E) @LINE: 1678 TEST.EXPECTED:EEPROM.<<GLOBAL>>.REG_FCCOB1.Word:0
    >>> Unknown parameter/object name REG_FCCOB1
    >>> Value Line Error - Command Ignored
(E) @LINE: 1679 TEST.EXPECTED:EEPROM.<<GLOBAL>>.REG_FCCOB2.Word:0
    >>> Unknown parameter/object name REG_FCCOB2
    >>> Value Line Error - Command Ignored
TEST.END_IMPORT_FAILURES:
TEST.NOTES:
REQ/FI

TEST.END_NOTES:
TEST.STUB:EEPROM.BackupSector
TEST.STUB:EEPROM.SetupFCCOB
TEST.STUB:EEPROM.EraseSectorInternal
TEST.STUB:EEPROM.WriteWord
TEST.STUB:EEPROM.EEPROM_SetByte
TEST.STUB:EEPROM.EEPROM_GetByte
TEST.STUB:EEPROM.EEPROM_Init
TEST.VALUE:EEPROM.<<GLOBAL>>._FSTAT.Byte:256
TEST.VALUE:EEPROM.<<GLOBAL>>._FSTAT.Bits.CCIF:2
TEST.VALUE:EEPROM.<<GLOBAL>>._FSTAT.MergedBits.grpMGSTAT:4
TEST.VALUE:EEPROM.WriteBlock.Addr:<<malloc 1>>
TEST.VALUE:EEPROM.WriteBlock.Addr[0]:4294967296
TEST.VALUE:EEPROM.WriteBlock.From:65536
TEST.VALUE:EEPROM.WriteBlock.To:65536
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FSTAT.Byte:0
TEST.EXPECTED:EEPROM.WriteBlock.return:0
TEST.END

-- Test Case: SwUFn_2105.005
TEST.UNIT:EEPROM
TEST.SUBPROGRAM:WriteBlock
TEST.ADD
TEST.NAME:SwUFn_2105.005
TEST.VALUE:EEPROM.<<GLOBAL>>.REG_FSTAT.Bits.CCIF:2
TEST.VALUE:EEPROM.<<GLOBAL>>.REG_FSTAT.MergedBits.grpMGSTAT:4
TEST.EXPECTED:EEPROM.<<GLOBAL>>.REG_FCCOBIX.Byte:0
TEST.EXPECTED:EEPROM.<<GLOBAL>>.REG_FSTAT.Byte:0x0
TEST.EXPECTED:EEPROM.<<GLOBAL>>.REG_FCCOB0.Overlap_STR.FCCOB0HISTR.Byte:0x0
TEST.EXPECTED:EEPROM.<<GLOBAL>>.REG_FCCOB0.Overlap_STR.FCCOB0LOSTR.Byte:0
TEST.EXPECTED:EEPROM.<<GLOBAL>>.REG_FCCOB1.Word:0
TEST.EXPECTED:EEPROM.<<GLOBAL>>.REG_FCCOB2.Word:0
TEST.END

-- Test Case: SwUFn_2105.006
TEST.UNIT:EEPROM
TEST.SUBPROGRAM:WriteBlock
TEST.NEW
TEST.NAME:SwUFn_2105.006
TEST.IMPORT_FAILURES:
(E) @LINE: 1740 TEST.VALUE:EEPROM.<<GLOBAL>>.REG_FSTAT.Bits.CCIF:0
    >>> Unknown parameter/object name REG_FSTAT
    >>> Value Line Error - Command Ignored
(E) @LINE: 1741 TEST.VALUE:EEPROM.<<GLOBAL>>.REG_FSTAT.MergedBits.grpMGSTAT:0
    >>> Unknown parameter/object name REG_FSTAT
    >>> Value Line Error - Command Ignored
(E) @LINE: 1742 TEST.EXPECTED:EEPROM.<<GLOBAL>>.REG_FCCOBIX.Byte:2
    >>> Unknown parameter/object name REG_FCCOBIX
    >>> Value Line Error - Command Ignored
(E) @LINE: 1743 TEST.EXPECTED:EEPROM.<<GLOBAL>>.REG_FSTAT.Byte:0x80
    >>> Unknown parameter/object name REG_FSTAT
    >>> Value Line Error - Command Ignored
(E) @LINE: 1744 TEST.EXPECTED:EEPROM.<<GLOBAL>>.REG_FCCOB0.Overlap_STR.FCCOB0HISTR.Byte:17
    >>> Unknown parameter/object name REG_FCCOB0
    >>> Value Line Error - Command Ignored
(E) @LINE: 1745 TEST.EXPECTED:EEPROM.<<GLOBAL>>.REG_FCCOB0.Overlap_STR.FCCOB0LOSTR.Byte:0
    >>> Unknown parameter/object name REG_FCCOB0
    >>> Value Line Error - Command Ignored
(E) @LINE: 1746 TEST.EXPECTED:EEPROM.<<GLOBAL>>.REG_FCCOB1.Word:10437
    >>> Unknown parameter/object name REG_FCCOB1
    >>> Value Line Error - Command Ignored
(E) @LINE: 1747 TEST.EXPECTED:EEPROM.<<GLOBAL>>.REG_FCCOB2.Word:0
    >>> Unknown parameter/object name REG_FCCOB2
    >>> Value Line Error - Command Ignored
TEST.END_IMPORT_FAILURES:
TEST.NOTES:
REQ/FI

TEST.END_NOTES:
TEST.STUB:EEPROM.BackupSector
TEST.STUB:EEPROM.SetupFCCOB
TEST.STUB:EEPROM.EraseSectorInternal
TEST.STUB:EEPROM.WriteWord
TEST.STUB:EEPROM.EEPROM_SetByte
TEST.STUB:EEPROM.EEPROM_GetByte
TEST.STUB:EEPROM.EEPROM_Init
TEST.VALUE:EEPROM.<<GLOBAL>>._FSTAT.Byte:345
TEST.VALUE:EEPROM.<<GLOBAL>>._FSTAT.Bits.CCIF:10
TEST.VALUE:EEPROM.<<GLOBAL>>._FSTAT.MergedBits.grpMGSTAT:15
TEST.VALUE:EEPROM.WriteBlock.Addr:<<malloc 1>>
TEST.VALUE:EEPROM.WriteBlock.Addr[0]:5781426894
TEST.VALUE:EEPROM.WriteBlock.From:75426
TEST.VALUE:EEPROM.WriteBlock.To:75426
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FSTAT.Byte:91
TEST.EXPECTED:EEPROM.WriteBlock.return:0
TEST.END

-- Test Case: SwUFn_2105.006
TEST.UNIT:EEPROM
TEST.SUBPROGRAM:WriteBlock
TEST.ADD
TEST.NAME:SwUFn_2105.006
TEST.VALUE:EEPROM.<<GLOBAL>>.REG_FSTAT.Bits.CCIF:0
TEST.VALUE:EEPROM.<<GLOBAL>>.REG_FSTAT.MergedBits.grpMGSTAT:0
TEST.EXPECTED:EEPROM.<<GLOBAL>>.REG_FCCOBIX.Byte:2
TEST.EXPECTED:EEPROM.<<GLOBAL>>.REG_FSTAT.Byte:0x80
TEST.EXPECTED:EEPROM.<<GLOBAL>>.REG_FCCOB0.Overlap_STR.FCCOB0HISTR.Byte:17
TEST.EXPECTED:EEPROM.<<GLOBAL>>.REG_FCCOB0.Overlap_STR.FCCOB0LOSTR.Byte:0
TEST.EXPECTED:EEPROM.<<GLOBAL>>.REG_FCCOB1.Word:10437
TEST.EXPECTED:EEPROM.<<GLOBAL>>.REG_FCCOB2.Word:0
TEST.END

-- Test Case: SwUFn_2105.007
TEST.UNIT:EEPROM
TEST.SUBPROGRAM:WriteBlock
TEST.NEW
TEST.NAME:SwUFn_2105.007
TEST.IMPORT_FAILURES:
(E) @LINE: 1808 TEST.VALUE:EEPROM.<<GLOBAL>>.REG_FSTAT.Bits.CCIF:0
    >>> Unknown parameter/object name REG_FSTAT
    >>> Value Line Error - Command Ignored
(E) @LINE: 1809 TEST.VALUE:EEPROM.<<GLOBAL>>.REG_FSTAT.MergedBits.grpMGSTAT:1
    >>> Unknown parameter/object name REG_FSTAT
    >>> Value Line Error - Command Ignored
(E) @LINE: 1810 TEST.EXPECTED:EEPROM.<<GLOBAL>>.REG_FCCOBIX.Byte:2
    >>> Unknown parameter/object name REG_FCCOBIX
    >>> Value Line Error - Command Ignored
(E) @LINE: 1811 TEST.EXPECTED:EEPROM.<<GLOBAL>>.REG_FSTAT.Byte:0x80
    >>> Unknown parameter/object name REG_FSTAT
    >>> Value Line Error - Command Ignored
(E) @LINE: 1812 TEST.EXPECTED:EEPROM.<<GLOBAL>>.REG_FCCOB0.Overlap_STR.FCCOB0HISTR.Byte:17
    >>> Unknown parameter/object name REG_FCCOB0
    >>> Value Line Error - Command Ignored
(E) @LINE: 1813 TEST.EXPECTED:EEPROM.<<GLOBAL>>.REG_FCCOB0.Overlap_STR.FCCOB0LOSTR.Byte:0
    >>> Unknown parameter/object name REG_FCCOB0
    >>> Value Line Error - Command Ignored
(E) @LINE: 1814 TEST.EXPECTED:EEPROM.<<GLOBAL>>.REG_FCCOB1.Word:10446
    >>> Unknown parameter/object name REG_FCCOB1
    >>> Value Line Error - Command Ignored
(E) @LINE: 1815 TEST.EXPECTED:EEPROM.<<GLOBAL>>.REG_FCCOB2.Word:256
    >>> Unknown parameter/object name REG_FCCOB2
    >>> Value Line Error - Command Ignored
TEST.END_IMPORT_FAILURES:
TEST.NOTES:
REQ/FI

TEST.END_NOTES:
TEST.STUB:EEPROM.BackupSector
TEST.STUB:EEPROM.SetupFCCOB
TEST.STUB:EEPROM.EraseSectorInternal
TEST.STUB:EEPROM.WriteWord
TEST.STUB:EEPROM.EEPROM_SetByte
TEST.STUB:EEPROM.EEPROM_GetByte
TEST.STUB:EEPROM.EEPROM_Init
TEST.VALUE:EEPROM.<<GLOBAL>>._FSTAT.Byte:400
TEST.VALUE:EEPROM.<<GLOBAL>>._FSTAT.Bits.CCIF:180
TEST.VALUE:EEPROM.<<GLOBAL>>._FSTAT.MergedBits.grpMGSTAT:152
TEST.VALUE:EEPROM.WriteBlock.Addr:<<malloc 1>>
TEST.VALUE:EEPROM.WriteBlock.Addr[0]:5000000000
TEST.VALUE:EEPROM.WriteBlock.From:70000
TEST.VALUE:EEPROM.WriteBlock.To:70000
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FSTAT.Byte:16
TEST.EXPECTED:EEPROM.WriteBlock.return:0
TEST.END

-- Test Case: SwUFn_2105.007
TEST.UNIT:EEPROM
TEST.SUBPROGRAM:WriteBlock
TEST.ADD
TEST.NAME:SwUFn_2105.007
TEST.VALUE:EEPROM.<<GLOBAL>>.REG_FSTAT.Bits.CCIF:0
TEST.VALUE:EEPROM.<<GLOBAL>>.REG_FSTAT.MergedBits.grpMGSTAT:1
TEST.EXPECTED:EEPROM.<<GLOBAL>>.REG_FCCOBIX.Byte:2
TEST.EXPECTED:EEPROM.<<GLOBAL>>.REG_FSTAT.Byte:0x80
TEST.EXPECTED:EEPROM.<<GLOBAL>>.REG_FCCOB0.Overlap_STR.FCCOB0HISTR.Byte:17
TEST.EXPECTED:EEPROM.<<GLOBAL>>.REG_FCCOB0.Overlap_STR.FCCOB0LOSTR.Byte:0
TEST.EXPECTED:EEPROM.<<GLOBAL>>.REG_FCCOB1.Word:10446
TEST.EXPECTED:EEPROM.<<GLOBAL>>.REG_FCCOB2.Word:256
TEST.END

-- Test Case: SwUFn_2105.008
TEST.UNIT:EEPROM
TEST.SUBPROGRAM:WriteBlock
TEST.NEW
TEST.NAME:SwUFn_2105.008
TEST.NOTES:
REQ/EC
TEST.END_NOTES:
TEST.STUB:EEPROM.BackupSector
TEST.STUB:EEPROM.SetupFCCOB
TEST.STUB:EEPROM.EraseSectorInternal
TEST.STUB:EEPROM.WriteWord
TEST.STUB:EEPROM.EEPROM_SetByte
TEST.STUB:EEPROM.EEPROM_GetByte
TEST.STUB:EEPROM.EEPROM_Init
TEST.VALUE:EEPROM.<<GLOBAL>>._FSTAT.Byte:127
TEST.VALUE:EEPROM.<<GLOBAL>>._FSTAT.Bits.CCIF:1
TEST.VALUE:EEPROM.<<GLOBAL>>._FSTAT.MergedBits.grpMGSTAT:1
TEST.VALUE:EEPROM.WriteBlock.Addr:<<malloc 1>>
TEST.VALUE:EEPROM.WriteBlock.Addr[0]:2147483647
TEST.VALUE:EEPROM.WriteBlock.From:1
TEST.VALUE:EEPROM.WriteBlock.To:2
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FSTAT.Byte:128
TEST.EXPECTED:EEPROM.WriteBlock.return:0
TEST.STUB_VAL_USER_CODE:EEPROM.SetupFCCOB.pIndex
word *temp = <<EEPROM.SetupFCCOB.pIndex>>;
*temp = 3;
TEST.END_STUB_VAL_USER_CODE:
TEST.END

-- Subprogram: WriteWord

-- Test Case: SwUFn_2106.001
TEST.UNIT:EEPROM
TEST.SUBPROGRAM:WriteWord
TEST.NEW
TEST.NAME:SwUFn_2106.001
TEST.NOTES:
REQ/BA
TEST.END_NOTES:
TEST.STUB:EEPROM.BackupSector
TEST.STUB:EEPROM.WriteBlock
TEST.STUB:EEPROM.SetupFCCOB
TEST.STUB:EEPROM.EraseSectorInternal
TEST.STUB:EEPROM.EEPROM_SetByte
TEST.STUB:EEPROM.EEPROM_GetByte
TEST.STUB:EEPROM.EEPROM_Init
TEST.VALUE:EEPROM.<<GLOBAL>>._FSTAT.Byte:0
TEST.VALUE:EEPROM.<<GLOBAL>>._FSTAT.Bits.CCIF:0
TEST.VALUE:EEPROM.<<GLOBAL>>._FSTAT.MergedBits.grpMGSTAT:0
TEST.VALUE:EEPROM.WriteWord.AddrRow:<<malloc 1>>
TEST.VALUE:EEPROM.WriteWord.AddrRow[0]:0
TEST.VALUE:EEPROM.WriteWord.Data16:0
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FCCOBIX.Byte:0
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FSTAT.Byte:0
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FCCOB0.Overlap_STR.FCCOB0HISTR.Byte:0
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FCCOB0.Overlap_STR.FCCOB0LOSTR.Byte:0
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FCCOB1.Word:0
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FCCOB2.Word:0
TEST.EXPECTED:EEPROM.WriteWord.return:8
TEST.END

-- Test Case: SwUFn_2106.002
TEST.UNIT:EEPROM
TEST.SUBPROGRAM:WriteWord
TEST.NEW
TEST.NAME:SwUFn_2106.002
TEST.NOTES:
REQ/BA
TEST.END_NOTES:
TEST.STUB:EEPROM.BackupSector
TEST.STUB:EEPROM.WriteBlock
TEST.STUB:EEPROM.SetupFCCOB
TEST.STUB:EEPROM.EraseSectorInternal
TEST.STUB:EEPROM.EEPROM_SetByte
TEST.STUB:EEPROM.EEPROM_GetByte
TEST.STUB:EEPROM.EEPROM_Init
TEST.VALUE:EEPROM.<<GLOBAL>>._FSTAT.Byte:127
TEST.VALUE:EEPROM.<<GLOBAL>>._FSTAT.Bits.CCIF:0
TEST.VALUE:EEPROM.<<GLOBAL>>._FSTAT.MergedBits.grpMGSTAT:1
TEST.VALUE:EEPROM.WriteWord.AddrRow:<<malloc 1>>
TEST.VALUE:EEPROM.WriteWord.AddrRow[0]:2147483647
TEST.VALUE:EEPROM.WriteWord.Data16:32767
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FCCOBIX.Byte:0
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FSTAT.Byte:125
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FCCOB0.Overlap_STR.FCCOB0HISTR.Byte:0
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FCCOB0.Overlap_STR.FCCOB0LOSTR.Byte:0
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FCCOB1.Word:0
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FCCOB2.Word:0
TEST.EXPECTED:EEPROM.WriteWord.return:8
TEST.END

-- Test Case: SwUFn_2106.003
TEST.UNIT:EEPROM
TEST.SUBPROGRAM:WriteWord
TEST.NEW
TEST.NAME:SwUFn_2106.003
TEST.NOTES:
REQ/BA
TEST.END_NOTES:
TEST.STUB:EEPROM.BackupSector
TEST.STUB:EEPROM.WriteBlock
TEST.STUB:EEPROM.SetupFCCOB
TEST.STUB:EEPROM.EraseSectorInternal
TEST.STUB:EEPROM.EEPROM_SetByte
TEST.STUB:EEPROM.EEPROM_GetByte
TEST.STUB:EEPROM.EEPROM_Init
TEST.VALUE:EEPROM.<<GLOBAL>>._FSTAT.Byte:255
TEST.VALUE:EEPROM.<<GLOBAL>>._FSTAT.Bits.CCIF:1
TEST.VALUE:EEPROM.<<GLOBAL>>._FSTAT.MergedBits.grpMGSTAT:3
TEST.VALUE:EEPROM.WriteWord.AddrRow:<<malloc 1>>
TEST.VALUE:EEPROM.WriteWord.AddrRow[0]:4294967295
TEST.VALUE:EEPROM.WriteWord.Data16:65535
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FCCOBIX.Byte:2
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FSTAT.Byte:128
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FCCOB0.Overlap_STR.FCCOB0HISTR.Byte:17
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FCCOB0.Overlap_STR.FCCOB0LOSTR.Byte:0
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FCCOB1.Word:7252
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FCCOB2.Word:65535
TEST.EXPECTED:EEPROM.WriteWord.return:0
TEST.ATTRIBUTES:EEPROM.SetupFCCOB.Data[0]:INPUT_BASE=16
TEST.ATTRIBUTES:EEPROM.SetupFCCOB.pIndex[0]:INPUT_BASE=16,EXPECTED_BASE=16
TEST.END

-- Test Case: SwUFn_2106.004
TEST.UNIT:EEPROM
TEST.SUBPROGRAM:WriteWord
TEST.NEW
TEST.NAME:SwUFn_2106.004
TEST.NOTES:
REQ/FI
TEST.END_NOTES:
TEST.STUB:EEPROM.BackupSector
TEST.STUB:EEPROM.WriteBlock
TEST.STUB:EEPROM.SetupFCCOB
TEST.STUB:EEPROM.EraseSectorInternal
TEST.STUB:EEPROM.EEPROM_SetByte
TEST.STUB:EEPROM.EEPROM_GetByte
TEST.STUB:EEPROM.EEPROM_Init
TEST.VALUE:EEPROM.<<GLOBAL>>._FSTAT.Byte:-1
TEST.VALUE:EEPROM.<<GLOBAL>>._FSTAT.Bits.CCIF:-1
TEST.VALUE:EEPROM.<<GLOBAL>>._FSTAT.MergedBits.grpMGSTAT:-1
TEST.VALUE:EEPROM.WriteWord.AddrRow:<<malloc 1>>
TEST.VALUE:EEPROM.WriteWord.AddrRow[0]:-1
TEST.VALUE:EEPROM.WriteWord.Data16:-1
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FCCOBIX.Byte:2
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FSTAT.Byte:128
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FCCOB0.Overlap_STR.FCCOB0HISTR.Byte:17
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FCCOB0.Overlap_STR.FCCOB0LOSTR.Byte:0
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FCCOB1.Word:7244
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FCCOB2.Word:65535
TEST.EXPECTED:EEPROM.WriteWord.return:0
TEST.ATTRIBUTES:EEPROM.SetupFCCOB.Data[0]:INPUT_BASE=16
TEST.ATTRIBUTES:EEPROM.SetupFCCOB.pIndex[0]:INPUT_BASE=16,EXPECTED_BASE=16
TEST.END

-- Test Case: SwUFn_2106.005
TEST.UNIT:EEPROM
TEST.SUBPROGRAM:WriteWord
TEST.NEW
TEST.NAME:SwUFn_2106.005
TEST.NOTES:
REQ/FI
TEST.END_NOTES:
TEST.STUB:EEPROM.BackupSector
TEST.STUB:EEPROM.WriteBlock
TEST.STUB:EEPROM.SetupFCCOB
TEST.STUB:EEPROM.EraseSectorInternal
TEST.STUB:EEPROM.EEPROM_SetByte
TEST.STUB:EEPROM.EEPROM_GetByte
TEST.STUB:EEPROM.EEPROM_Init
TEST.VALUE:EEPROM.<<GLOBAL>>._FSTAT.Byte:256
TEST.VALUE:EEPROM.<<GLOBAL>>._FSTAT.Bits.CCIF:2
TEST.VALUE:EEPROM.<<GLOBAL>>._FSTAT.MergedBits.grpMGSTAT:4
TEST.VALUE:EEPROM.WriteWord.AddrRow:<<malloc 1>>
TEST.VALUE:EEPROM.WriteWord.AddrRow[0]:4294967296
TEST.VALUE:EEPROM.WriteWord.Data16:65536
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FCCOBIX.Byte:0
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FSTAT.Byte:0
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FCCOB0.Overlap_STR.FCCOB0HISTR.Byte:0
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FCCOB0.Overlap_STR.FCCOB0LOSTR.Byte:0
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FCCOB1.Word:0
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FCCOB2.Word:0
TEST.EXPECTED:EEPROM.WriteWord.return:8
TEST.END

-- Test Case: SwUFn_2106.006
TEST.UNIT:EEPROM
TEST.SUBPROGRAM:WriteWord
TEST.NEW
TEST.NAME:SwUFn_2106.006
TEST.NOTES:
REQ/FI
TEST.END_NOTES:
TEST.STUB:EEPROM.BackupSector
TEST.STUB:EEPROM.WriteBlock
TEST.STUB:EEPROM.SetupFCCOB
TEST.STUB:EEPROM.EraseSectorInternal
TEST.STUB:EEPROM.EEPROM_SetByte
TEST.STUB:EEPROM.EEPROM_GetByte
TEST.STUB:EEPROM.EEPROM_Init
TEST.VALUE:EEPROM.<<GLOBAL>>._FSTAT.Byte:340
TEST.VALUE:EEPROM.<<GLOBAL>>._FSTAT.Bits.CCIF:100
TEST.VALUE:EEPROM.<<GLOBAL>>._FSTAT.MergedBits.grpMGSTAT:150
TEST.VALUE:EEPROM.WriteWord.AddrRow:<<malloc 1>>
TEST.VALUE:EEPROM.WriteWord.AddrRow[0]:5201478035
TEST.VALUE:EEPROM.WriteWord.Data16:72503
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FCCOBIX.Byte:0
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FSTAT.Byte:86
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FCCOB0.Overlap_STR.FCCOB0HISTR.Byte:0
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FCCOB0.Overlap_STR.FCCOB0LOSTR.Byte:0
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FCCOB1.Word:0
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FCCOB2.Word:0
TEST.EXPECTED:EEPROM.WriteWord.return:8
TEST.END

-- Test Case: SwUFn_2106.007
TEST.UNIT:EEPROM
TEST.SUBPROGRAM:WriteWord
TEST.NEW
TEST.NAME:SwUFn_2106.007
TEST.NOTES:
REQ/FI
TEST.END_NOTES:
TEST.STUB:EEPROM.BackupSector
TEST.STUB:EEPROM.WriteBlock
TEST.STUB:EEPROM.SetupFCCOB
TEST.STUB:EEPROM.EraseSectorInternal
TEST.STUB:EEPROM.EEPROM_SetByte
TEST.STUB:EEPROM.EEPROM_GetByte
TEST.STUB:EEPROM.EEPROM_Init
TEST.VALUE:EEPROM.<<GLOBAL>>._FSTAT.Byte:312
TEST.VALUE:EEPROM.<<GLOBAL>>._FSTAT.Bits.CCIF:99
TEST.VALUE:EEPROM.<<GLOBAL>>._FSTAT.MergedBits.grpMGSTAT:99
TEST.VALUE:EEPROM.WriteWord.AddrRow:<<malloc 1>>
TEST.VALUE:EEPROM.WriteWord.AddrRow[0]:5001472305
TEST.VALUE:EEPROM.WriteWord.Data16:70065
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FCCOBIX.Byte:2
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FSTAT.Byte:128
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FCCOB0.Overlap_STR.FCCOB0HISTR.Byte:17
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FCCOB0.Overlap_STR.FCCOB0LOSTR.Byte:0
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FCCOB1.Word:7256
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FCCOB2.Word:4529
TEST.EXPECTED:EEPROM.WriteWord.return:0
TEST.ATTRIBUTES:EEPROM.SetupFCCOB.Data[0]:INPUT_BASE=16
TEST.ATTRIBUTES:EEPROM.SetupFCCOB.pIndex[0]:INPUT_BASE=16,EXPECTED_BASE=16
TEST.END
