
typedef int VECTORCAST_MARKER__UNIT_PREFIX_START;

typedef int VECTORCAST_MARKER__UNIT_PREFIX_END;
#include "C:/MDS_work/PSD_ENV/UT/SwUT_21_EEPROM/SWUT_21_EEPROM/S0000008.c"

typedef int VECTORCAST_MARKER__UNIT_APPENDIX_START;

typedef int VECTORCAST_MARKER__UNIT_APPENDIX_END;
