#ifndef VCAST_NEVER_STUB_EXTERNS
/* Begin defined extern variables */

/* INITIALIZATION_OBJECTS_USER_CODE "1" */
/* INITIALIZATION_OBJECTS_USER_CODE_END "1" */
volatile FCLKDIVSTR  _FCLKDIV 
/* INITIALIZATION_CODE_USER_CODE "1" */

/* INITIALIZATION_CODE_USER_CODE_END "1" */
;

/* INITIALIZATION_OBJECTS_USER_CODE "2" */
/* INITIALIZATION_OBJECTS_USER_CODE_END "2" */
volatile FCCOBIXSTR  _FCCOBIX 
/* INITIALIZATION_CODE_USER_CODE "2" */

/* INITIALIZATION_CODE_USER_CODE_END "2" */
;

/* INITIALIZATION_OBJECTS_USER_CODE "3" */
/* INITIALIZATION_OBJECTS_USER_CODE_END "3" */
volatile FSTATSTR  _FSTAT 
/* INITIALIZATION_CODE_USER_CODE "3" */

/* INITIALIZATION_CODE_USER_CODE_END "3" */
;

/* INITIALIZATION_OBJECTS_USER_CODE "4" */
/* INITIALIZATION_OBJECTS_USER_CODE_END "4" */
volatile FCCOB0STR  _FCCOB0 
/* INITIALIZATION_CODE_USER_CODE "4" */

/* INITIALIZATION_CODE_USER_CODE_END "4" */
;

/* INITIALIZATION_OBJECTS_USER_CODE "5" */
/* INITIALIZATION_OBJECTS_USER_CODE_END "5" */
volatile FCCOB1STR  _FCCOB1 
/* INITIALIZATION_CODE_USER_CODE "5" */

/* INITIALIZATION_CODE_USER_CODE_END "5" */
;

/* INITIALIZATION_OBJECTS_USER_CODE "6" */
/* INITIALIZATION_OBJECTS_USER_CODE_END "6" */
volatile FCCOB2STR  _FCCOB2 
/* INITIALIZATION_CODE_USER_CODE "6" */

/* INITIALIZATION_CODE_USER_CODE_END "6" */
;
/* End defined extern variables */
/* Begin defined static member variables */
/* End defined static member variables */
#endif /*VCAST_NEVER_STUB_EXTERNS*/
/* BEGIN PROTOTYPE STUBS */
/* END PROTOTYPE STUBS */
