"""CodeSonar(GrammaTech) Analysis Report PDF 파서.

회사 정적분석 산출물 중 CodeSonar PDF(`CodeSonar_<proj>_<ver>_<date>.pdf`)에서
구조화된 지표를 추출한다. SCM `…/09.정적분석/01.Static Analysis/CodeSonar Report/<date>/`
에 위치하며, 기존 SwSA 빌더(QAC xml + PMD txt)는 CodeSonar(PDF)를 다루지 않았다.

추출 항목(실데이터 PDS64_RD analysis 106 기준):
    - summary: active_warnings, file_count, project_name, time_started/finished, machine, title, generated
    - by_class: [{warning_class, count}]  (Warnings by Class 표)
    - by_file:  [{file, warnings, lines, language}]  (Warnings by File 표)

PDF 레이아웃은 표 셀이 병합되어 추출되므로 pdfplumber extract_text() 라인 파싱이 가장 안정적이다.
(extract_tables()는 빈 셀이 많아 신뢰도 낮음 — Figure 차트 페이지 등.)
"""
from __future__ import annotations

import io
import re
from typing import Any, Dict, List, Union

__all__ = ["parse_codesonar_pdf", "parse_codesonar_text"]


def _full_text(src: Union[bytes, str]) -> str:
    """pdfplumber로 전체 페이지 텍스트를 합친다. src는 bytes(PDF 내용) 또는 파일 경로."""
    import pdfplumber  # lazy — pdfplumber 미설치 환경에서 import 비용 회피

    stream: Union[io.BytesIO, str] = io.BytesIO(src) if isinstance(src, bytes) else src
    pages: List[str] = []
    with pdfplumber.open(stream) as pdf:
        for pg in pdf.pages:
            pages.append(pg.extract_text() or "")
    return "\n".join(pages)


def parse_codesonar_text(full: str) -> Dict[str, Any]:
    """추출된 전체 텍스트 → 구조화 dict. (PDF 분리 — 단위테스트 용이)"""
    result: Dict[str, Any] = {
        "summary": {},
        "by_class": [],
        "by_file": [],
        "parse_warnings": [],
    }

    # ── Title / generated ──
    m_title = re.search(r"(CodeSonar Analysis Report)", full)
    if m_title:
        result["summary"]["title"] = m_title.group(1)
    m_gen = re.search(r"generated by .+? on (.+?)\n", full)
    if m_gen:
        result["summary"]["generated"] = m_gen.group(1).strip()
    m_for = re.search(r"for analysis\s+(\S+)\s+analysis\s+(\d+)", full)
    if m_for:
        result["summary"]["analysis_name"] = m_for.group(1)
        result["summary"]["analysis_id"] = m_for.group(2)

    # ── Summary 표: "Active Warnings File Count Project Name Time Started Time Finished Machine"
    #    다음 줄: "50 93 PDS64_RD Tue Oct 10 16:57:10 2023 Tue Oct 10 16:59:02 2023 LAPTOP-..."
    m_sum = re.search(
        r"Active Warnings\s+File Count\s+Project Name\s+Time Started\s+Time Finished\s+Machine\s*\n\s*"
        r"(\d+)\s+(\d+)\s+(\S+)\s+(.+)",
        full,
    )
    if m_sum:
        result["summary"]["active_warnings"] = int(m_sum.group(1))
        result["summary"]["file_count"] = int(m_sum.group(2))
        result["summary"]["project_name"] = m_sum.group(3)
        # 시간/머신은 자유 텍스트 — 끝의 머신 토큰만 따로, 나머지는 raw로 보존.
        tail = m_sum.group(4).strip()
        result["summary"]["time_raw"] = tail
        m_mc = re.search(r"(\S+)\s*$", tail)
        if m_mc:
            result["summary"]["machine"] = m_mc.group(1)
    else:
        result["parse_warnings"].append("summary 표(Active Warnings/File Count) 미발견")

    # ── Warnings by Class: "Warning Class Active Warnings" 이후, 다음 표/섹션 전까지
    m_cls = re.search(
        r"Warning Class\s+Active Warnings\s*\n(.*?)(?:\n\s*(?:Table\s+\d|File\s+Active Warnings|Figure)\b|\Z)",
        full,
        re.S,
    )
    if m_cls:
        for line in m_cls.group(1).splitlines():
            line = line.strip()
            if not line:
                continue
            mm = re.match(r"^(.+?)\s+(\d+)$", line)
            if mm:
                result["by_class"].append(
                    {"warning_class": mm.group(1).strip(), "count": int(mm.group(2))}
                )
    if not result["by_class"]:
        result["parse_warnings"].append("Warnings by Class 표 미발견/빈값")

    # ── Warnings by File: "File Active Warnings Total Lines Language" 이후
    m_file = re.search(
        r"File\s+Active Warnings\s+Total Lines\s+Language\s*\n(.*?)(?:\n\s*(?:Table\s+\d|Figure)\b|\Z)",
        full,
        re.S,
    )
    if m_file:
        for line in m_file.group(1).splitlines():
            line = line.strip()
            if not line:
                continue
            # "ApiOut_LinTxComp_PDS.c 20 192 C" — 파일명에 공백 가능성 낮으나 .+? non-greedy로 보호
            mm = re.match(r"^(.+?)\s+(\d+)\s+(\d+)\s+([A-Za-z+#]+)$", line)
            if mm:
                result["by_file"].append(
                    {
                        "file": mm.group(1).strip(),
                        "warnings": int(mm.group(2)),
                        "lines": int(mm.group(3)),
                        "language": mm.group(4),
                    }
                )
    if not result["by_file"]:
        result["parse_warnings"].append("Warnings by File 표 미발견/빈값")

    # ── 파생: 분류 수 / 표시용 total ──
    result["summary"]["distinct_classes"] = len(result["by_class"])
    # by_class 합이 active_warnings와 일치하는지 검증(불일치 시 경고 — 페이지 누락/파싱 갭 탐지)
    cls_sum = sum(c["count"] for c in result["by_class"])
    if result["by_class"] and result["summary"].get("active_warnings") is not None:
        if cls_sum != result["summary"]["active_warnings"]:
            result["parse_warnings"].append(
                f"by_class 합({cls_sum}) != active_warnings({result['summary']['active_warnings']})"
            )
    return result


def parse_codesonar_pdf(src: Union[bytes, str]) -> Dict[str, Any]:
    """CodeSonar PDF(bytes/경로/파일객체) → 구조화 dict.

    Returns:
        {"ok": bool, "summary": {...}, "by_class": [...], "by_file": [...], "parse_warnings": [...]}
    """
    try:
        full = _full_text(src)
    except Exception as e:  # pragma: no cover — pdfplumber 실패/손상 PDF
        return {
            "ok": False,
            "error": f"{type(e).__name__}: {e}",
            "summary": {},
            "by_class": [],
            "by_file": [],
            "parse_warnings": ["PDF 텍스트 추출 실패"],
        }
    data = parse_codesonar_text(full)
    data["ok"] = bool(data.get("summary", {}).get("active_warnings") is not None or data.get("by_class"))
    return data
