"""룰 상충 후보 — "이 규칙을 고치면 저 규칙에 걸린다"의 결정론 산출(LLM 0회).

요약탭 소스코드 서브탭 "룰 상충·판단 지점"의 코어. 새 파싱·새 IO를 만들지 않고
기존 산출물만 결합한다: RCR 디스크캐시(prqa_delta) · 룰 트렌드(prqa_rule_trend) ·
HMR 함수 메트릭(his_metric_delta) · 큐레이션 지식 테이블(config/misra_rule_conflicts.json).

**왜 지식 테이블이 필요한가 — 실측 근거.** 빌드 구간에서 '규칙 A 감소 · 규칙 B 증가'가
같은 파일에 동시에 난 사례는 캐시된 17개 빌드에서 **0건**이었다(변화가 난 6구간 중
대부분이 코드 변경이 아니라 규칙셋 on/off였다). 구간 delta만으로는 상충을 찾을 수 없다.
그래서 근거를 4단계로 나누고, 구간 실측(T1)은 최상위 등급에 자리만 두어 빌드가 쌓이면
자동으로 채워지게 한다.

증거 등급(tier) — 강→약:
  window          같은 파일 × 같은 구간에서 A↓·B↑ (실측)
  cooccurrence    같은 파일에 A·B가 함께 위반 중 (실측)
  metric_headroom 그 수정이 밀어올릴 HIS 메트릭이 밴드 경계에 붙은 함수 존재 (실측)
  ruleset_active  상대 규칙이 활성이나 현재 위반 0 — 예고

정직성 규약:
- **상대 규칙이 규칙셋에 없거나 비활성이면 후보에서 제외한다.** 그 규칙으로는 걸릴 수
  없으므로 경고 자체가 헛것이다. 제외 사유는 버리지 않고 risk_filtered로 돌려준다.
- **RCFInfo가 없는 빌드는 활성 판정 자체가 불가**하다 → 제외가 아니라 ruleset_unknown
  으로 표시하고 tier를 강등한다. 증거 부재를 '위험 없음'으로 읽히게 하지 않는다.
- 상충은 가능성이지 인과·확정 판정이 아니다 — CONFLICT_NOTE를 서버가 고정 주입한다.
- 지식 테이블은 도구 산출물이 아니라 사람이 정리한 지식이다. 파일의 source_note를
  그대로 실어 보내 그 경계를 화면에서도 유지한다.
- 테이블 부재·손상은 available:false + reason (빈 목록을 '상충 없음'으로 위장 금지).
"""
from __future__ import annotations

import json
import logging
import re
from pathlib import Path
from typing import Any, Dict, List, Optional, Set, Tuple

from backend.services.build_inventory import find_build_meta, list_cached_builds_meta
from backend.services.his_metric_delta import (
    METRIC_LABEL,
    _resolve_file_key,
    band_headroom,
    load_his_metrics_cached,
)
from backend.services.prqa_delta import load_rcr_details_cached
from backend.services.prqa_rule_trend import (
    compute_rule_trend,
    cross_module_keys,
    file_rule_counts,
    is_cross_module_key,
    rules_applied_in_build,
)

logger = logging.getLogger(__name__)

CONFLICT_TABLE_NAME = "misra_rule_conflicts.json"
DEFAULT_MAX_CONFLICTS = 40
MAX_EVIDENCE_PER_KIND = 6
# 자동 생성 마커 확인은 파일을 열어야 한다 — 경로로 이미 판정된 건 건너뛰고 나머지만, 상한 내에서.
MAX_MARKER_PROBES = 20
MARKER_HEAD_BYTES = 800
# 밴드 여유 임계 — 이 값 이하로 남은 함수를 "여유 없음"으로 본다.
# 왜 1이 아닌가: 단일 exit 변환·재귀 제거 같은 준수 리팩터링은 복잡도·중첩을 1단이 아니라
# 2~5단 올린다. 1로 두면 상한에 정확히 붙은 함수만 잡혀 실측 두 프로젝트에서 발화 0이었다.
HEADROOM_THRESHOLD = 3
# 동반 해소 후보 판정 — 두 규칙이 같은 코드를 세고 있는지 데이터로 추정한다.
# 파일 1개 우연 일치를 후보로 올리면 노이즈라 최소 2파일, 공존 파일의 과반이 일치해야 한다
# (실측 Rule-2.2↔C-POS-012 는 4파일 중 3파일 일치 = 0.75 — 완전 일치만 요구하면 놓친다).
CO_RES_MIN_FILES = 2
CO_RES_MIN_RATIO = 0.6
CO_RES_MAX = 12

CO_RESOLUTION_NOTE = (
    "두 규칙의 파일별 위반 수가 일치한다는 관측이며, 같은 코드 줄을 가리킨다는 증명이 "
    "아닙니다 — QAC 리포트는 파일×규칙 카운트가 최상세라 줄 정보가 없습니다. "
    "겹침 수는 상한이지 확정 중복분이 아닙니다."
)

CONFLICT_NOTE = (
    "상충 후보는 큐레이션된 규칙 지식과 이 빌드의 관측(동시 위반·메트릭 여유)을 결합한 "
    "가능성이며, 그 위반이 실제로 발생한다는 판정이 아닙니다. 상대 규칙이 규칙셋에 없거나 "
    "비활성이면 후보에서 제외됩니다 — 규칙 설정(RCFInfo)을 읽을 수 없는 빌드는 그 판정 "
    "자체가 불가하므로 별도 표시합니다."
)

TIER_ORDER: Dict[str, int] = {
    "window": 0, "cooccurrence": 1, "metric_headroom": 2, "ruleset_active": 3, "ruleset_unknown": 4,
}
TIER_NOTE: Dict[str, str] = {
    "window": "이 구간에서 한 규칙이 줄고 다른 규칙이 같은 파일에서 늘었습니다 — 관측이지 인과가 아닙니다",
    "cooccurrence": "두 규칙이 같은 파일에서 함께 위반 중입니다 — 한쪽 수정이 다른 쪽 코드를 건드릴 위치입니다",
    "metric_headroom": "이 수정이 밀어올리는 메트릭이 밴드 경계에 붙은 함수가 있습니다",
    "ruleset_active": "상대 규칙이 활성이나 현재 위반은 없습니다 — 수정 시 새로 발생할 수 있습니다",
    # 실측 증거도 없고 규칙 설정도 못 읽은 상태 — '활성'이라 부르면 거짓이 된다.
    "ruleset_unknown": "이 빌드의 규칙 설정(RCFInfo)이 없어 상대 규칙이 검사되는지 확인하지 못했습니다",
}

# 규칙 ID 표기 흡수 — 'Rule 10.4' / 'Rule-10.4' / 'MISRA 10.4' / 'M3CM Rule-10.4' / '10.4'.
_RULE_NUM_RE = re.compile(r"(?:^|[\s\-_])(?:rule[\s\-_]*)?(\d{1,2})\.(\d{1,2})\s*$", re.I)

# 자동 생성 코드 판별 — ① 경로 세그먼트 ② 파일명 ③ 파일 머리의 생성 마커.
_GENERATED_SEGMENTS = {"generated_code", "generated", "autogen", "auto_generated", "gen"}
_GENERATED_NAME_RE = re.compile(r"(_cfg|_gen|_generated)\.[ch]$", re.I)
# ⚠ **"do not edit/modify" 단독은 생성의 증거가 아니다.** 실측에서 수기 파일
#    `Sources/SYSTEM/SysOs_Main.c` 의 `/*** End of main routine. DO NOT MODIFY THIS TEXT!!! ***/`
#    가 걸렸다 — 세 프로젝트 전부에서. 이 축의 목적이 "손대면 안 되는 파일을 조치 대상에서
#    빼는 것"이라 오탐은 **고쳐야 할 코드를 건너뛰게 만든다**. 생성 표기를 요구하면 진짜
#    생성 파일은 그대로 잡힌다(Processor Expert "generated by" 68/68 유지, 오탐 1건만 탈락).
_GENERATED_MARKER_RE = re.compile(
    r"auto(?:matically)?[-\s]?generat"
    r"|(?:code|file|module|header)?\s*generated\s+(?:by|from|with)"
    r"|machine[-\s]generated"
    r"|this\s+file\s+is\s+generated"
    r"|자동\s*(?:으로\s*)?생성",
    re.I,
)


def normalize_rule_id(raw: Any) -> str:
    """규칙 ID 표기 정규화 — 'Rule 10.4'·'MISRA 10.4'·'10.4' → 'Rule-10.4'.

    숫자.숫자 패턴이 아닌 ID(Secure C 'C-INT-002' 등)는 공백만 정리해 그대로 둔다 —
    억지로 Rule-* 로 접으면 다른 규칙 체계가 같은 키로 뭉개진다.
    """
    s = str(raw or "").strip()
    if not s:
        return ""
    m = _RULE_NUM_RE.search(s)
    if m:
        return f"Rule-{int(m.group(1))}.{int(m.group(2))}"
    return re.sub(r"\s+", " ", s)


def _table_path(base: Optional[Path] = None) -> Path:
    """지식 테이블 경로 — 저장소 루트의 config/ 하위."""
    if base is not None:
        return Path(base)
    return Path(__file__).resolve().parents[2] / "config" / CONFLICT_TABLE_NAME


# 프로세스 캐시: {경로: (mtime_ns, size, payload)} — 편집 즉시 반영(재기동 불필요).
_TABLE_CACHE: Dict[str, Tuple[int, int, Dict[str, Any]]] = {}


def load_conflict_table(path: Optional[Path] = None) -> Dict[str, Any]:
    """상충 지식 테이블 로드. 부재·손상은 available:false + reason(빈 목록 위장 금지).

    mtime+size 시그니처 캐시 — config/swut_meta.json 과 같은 규약(파일을 고치면 다음
    호출에 바로 반영되고, 안 고치면 JSON 파싱이 반복되지 않는다).
    """
    p = _table_path(path)
    key = str(p)
    try:
        st = p.stat()
    except OSError:
        return {"available": False, "reason": "table_missing", "conflicts": [], "rule_categories": {}}
    hit = _TABLE_CACHE.get(key)
    if hit and hit[0] == st.st_mtime_ns and hit[1] == st.st_size:
        return hit[2]
    try:
        data = json.loads(p.read_text(encoding="utf-8"))
    except (OSError, ValueError) as exc:
        logger.warning("rule conflict table 읽기 실패 (%s): %s", p, exc)
        return {"available": False, "reason": "table_unreadable", "conflicts": [], "rule_categories": {}}
    if not isinstance(data, dict) or not isinstance(data.get("conflicts"), list):
        return {"available": False, "reason": "table_invalid", "conflicts": [], "rule_categories": {}}

    categories = {
        normalize_rule_id(k): str(v)
        for k, v in (data.get("rule_categories") or {}).items()
        if normalize_rule_id(k)
    }
    entries: List[Dict[str, Any]] = []
    for raw in data["conflicts"]:
        if not isinstance(raw, dict) or not str(raw.get("id") or "").strip():
            continue
        fixing = [r for r in (normalize_rule_id(x) for x in raw.get("when_fixing") or []) if r]
        risky = [r for r in (normalize_rule_id(x) for x in raw.get("may_violate") or []) if r]
        if not fixing:
            continue  # 고칠 대상이 없는 항목은 후보를 만들 수 없다
        entries.append({
            "id": str(raw["id"]).strip(),
            "when_fixing": fixing,
            "may_violate": risky,
            "kind": str(raw.get("kind") or "fix_induces"),
            "mechanism": str(raw.get("mechanism") or ""),
            "resolutions": [str(x) for x in (raw.get("resolutions") or []) if str(x).strip()],
            "deviation_hint": str(raw.get("deviation_hint") or ""),
            "metric_risk": [str(x).strip() for x in (raw.get("metric_risk") or []) if str(x).strip()],
            "confidence": str(raw.get("confidence") or "low"),
            "refs": [str(x) for x in (raw.get("refs") or []) if str(x).strip()],
        })
    payload = {
        "available": True,
        "reason": None,
        "version": data.get("version"),
        "source_note": str(data.get("source_note") or ""),
        "category_note": str(data.get("category_note") or ""),
        "rule_categories": categories,
        "conflicts": entries,
    }
    _TABLE_CACHE[key] = (st.st_mtime_ns, st.st_size, payload)
    return payload


def clear_conflict_table_cache() -> None:
    """테이블 캐시 비우기 — 테스트에서 임시 파일을 갈아끼울 때 쓴다."""
    _TABLE_CACHE.clear()


def is_generated_path(path: str) -> bool:
    """경로만으로 자동 생성 코드인지 — 세그먼트·파일명 규칙(파일 IO 없음)."""
    s = str(path or "").replace("\\", "/").strip().lower()
    if not s:
        return False
    if any(seg in _GENERATED_SEGMENTS for seg in s.split("/") if seg):
        return True
    return bool(_GENERATED_NAME_RE.search(s.rsplit("/", 1)[-1]))


def _marker_in_snapshot(
    build_root: Optional[Path], path: str, index: Optional[Dict[str, List[Path]]] = None,
) -> bool:
    """스냅샷 파일 머리에 생성 마커가 있는지 — 경로로 판정 못 한 파일의 2차 확인."""
    if build_root is None:
        return False
    from backend.services.rule_fix_examples import resolve_snapshot_file

    resolved = resolve_snapshot_file(Path(build_root), path, index=index)
    if resolved is None:
        return False
    try:
        head = resolved.read_text(encoding="utf-8", errors="ignore")[:MARKER_HEAD_BYTES]
    except OSError:
        return False
    return bool(_GENERATED_MARKER_RE.search(head))


def _rule_meta(
    rule: str, descriptions: Dict[str, Any], categories: Dict[str, str], counts: Dict[str, int]
) -> Dict[str, Any]:
    desc = descriptions.get(rule) if isinstance(descriptions, dict) else None
    return {
        "rule": rule,
        "title": (desc or {}).get("title") if isinstance(desc, dict) else None,
        "group": (desc or {}).get("group") if isinstance(desc, dict) else None,
        "count": counts.get(rule, 0),
        "category": categories.get(rule),
    }


def _window_evidence(
    trend_rules: Dict[str, Dict[str, Any]], fixing: List[str], risky: List[str],
) -> Tuple[List[Dict[str, Any]], int]:
    """T1 — 같은 파일 · 같은 구간에서 fixing 규칙이 줄고 risk 규칙이 늘어난 관측.

    트렌드가 규칙별로 이미 계산해 둔 decreased_files/increased_files 를 조인한다(추가 IO 0).
    구간(from_build,to_build)과 파일이 **둘 다** 같아야 한 사건으로 본다 — 파일만 같고
    구간이 다르면 서로 무관한 두 변화를 인과처럼 붙이는 셈이다.

    반환 (표시분, 전체 건수) — 상한에 잘린 사실을 화면이 말할 수 있어야 한다.
    """
    out: List[Dict[str, Any]] = []
    for fr in fixing:
        down = (trend_rules.get(fr) or {}).get("decreased_files") or []
        if not down:
            continue
        down_idx = {(d.get("path"), d.get("from_build"), d.get("to_build")): d for d in down}
        for rr in risky:
            for up in (trend_rules.get(rr) or {}).get("increased_files") or []:
                hit = down_idx.get((up.get("path"), up.get("from_build"), up.get("to_build")))
                if hit is None:
                    continue
                out.append({
                    "file": up.get("path"),
                    "from_build": up.get("from_build"),
                    "to_build": up.get("to_build"),
                    "rule_down": fr, "delta_down": hit.get("delta"),
                    "rule_up": rr, "delta_up": up.get("delta"),
                    **({"scope": "cross_module"} if up.get("scope") == "cross_module" else {}),
                })
    out.sort(key=lambda e: (-(abs(e.get("delta_up") or 0) + abs(e.get("delta_down") or 0)), str(e.get("file"))))
    return out[:MAX_EVIDENCE_PER_KIND], len(out)


def _cooccurrence_evidence(
    per_file: Dict[str, Dict[str, int]], fixing: List[str], risky: List[str],
    pseudo: Set[str], generated: Set[str],
) -> Tuple[List[Dict[str, Any]], int]:
    """T2 — 최신 빌드에서 fixing 규칙과 risk 규칙이 같은 파일에 함께 위반 중.

    반환 (표시분, 전체 파일 수). 자동 생성 파일은 지우지 않고 **표시**한다 — 조치 대상이
    아니라는 사실이 그 행에 붙어야 한다(빼버리면 총계가 화면에서 안 맞는다).
    """
    out: List[Dict[str, Any]] = []
    for path, rc in per_file.items():
        hit_fix = {r: rc[r] for r in fixing if rc.get(r, 0) > 0}
        hit_risk = {r: rc[r] for r in risky if rc.get(r, 0) > 0}
        if not hit_fix or not hit_risk:
            continue
        entry: Dict[str, Any] = {
            "file": path, "fixing_counts": hit_fix, "risk_counts": hit_risk,
            "total": sum(hit_fix.values()) + sum(hit_risk.values()),
        }
        if path in pseudo or is_cross_module_key(path):
            entry["scope"] = "cross_module"
        if path in generated:
            entry["generated"] = True
        out.append(entry)
    # 조치 가능한 파일(수기)을 먼저 — 상한에 잘려도 손댈 수 있는 증거가 남는다.
    out.sort(key=lambda e: (bool(e.get("generated")), -int(e["total"]), str(e["file"])))
    return out[:MAX_EVIDENCE_PER_KIND], len(out)


def _headroom_evidence(
    functions: Dict[str, Dict[str, str]], files: List[str], metrics: List[str],
    *, threshold: int = HEADROOM_THRESHOLD,
) -> Tuple[List[Dict[str, Any]], int]:
    """T3 — metric_risk 메트릭의 **밴드 여유가 임계 이하**인 함수.

    "복잡도가 높다"가 아니라 "여유가 없다"를 본다. 여유가 정확히 1인 함수만 잡으면
    (구 구현) 실제 리팩터링 규모와 안 맞아 아무것도 안 걸린다 — 실측에서 이 등급은
    두 프로젝트 어디서도 발화하지 않았다. 거리를 재고 임계로 거른다(`band_headroom`).
    이미 최악 밴드(Fail)인 함수는 더 나빠질 곳이 없어 여기 안 잡히지만, 그건 여유
    문제가 아니라 이미 실패한 것이라 별도 축이다.
    """
    out: List[Dict[str, Any]] = []
    if not functions or not metrics:
        return out, 0
    for f in files:
        keys, reason = _resolve_file_key(functions, f)
        if reason or not keys:
            continue
        for key in keys:
            vals = functions.get(key) or {}
            for metric in metrics:
                room = band_headroom(metric, vals.get(metric))
                if room is None or room["headroom"] > threshold:
                    continue
                out.append({
                    "file": f,
                    "function": key.split("\x1f", 1)[1] if "\x1f" in key else key,
                    "metric": metric,
                    "label": METRIC_LABEL.get(metric, metric),
                    "value": int(str(vals.get(metric)).strip()),
                    "headroom": room["headroom"],
                    "st_id": room["st_id"],
                    "band": room["band"], "verdict": room["verdict"],
                    "next_band": room["next_band"], "next_verdict": room["next_verdict"],
                })
    # 여유가 작은 것부터 — 상한에 잘려도 가장 위험한 함수가 남는다.
    out.sort(key=lambda e: (int(e["headroom"]), str(e["file"]), str(e["function"]), str(e["metric"])))
    return out[:MAX_EVIDENCE_PER_KIND], len(out)


def _co_resolution_candidates(
    per_file: Dict[str, Dict[str, int]], pseudo: Set[str], descriptions: Dict[str, Any],
) -> List[Dict[str, Any]]:
    """**함께 해소될 수 있는 규칙 쌍** — 같은 코드를 두 규칙이 각각 셌을 가능성.

    상충("고치면 걸린다")의 반대편이고, 사용자 질문의 빠진 반쪽이다. 실측 근거:
    KJPDS02_PV 에서 `Rule-2.2`(dead code)와 `C-POS-012`("Remove 'Dead Code'")가 세 파일에서
    카운트까지 **정확히 일치**했다(12=12 · 10=10 · 11=11). MISRA(M3CM)와 회사 규칙셋(HKCCM)이
    같은 코드를 각각 센 것이다. 그러면 한쪽을 고칠 때 다른 쪽도 함께 줄고, 위반 총계에는
    같은 코드가 두 번 들어가 있다.

    ⚠ 지식 테이블이 아니라 **데이터가 말하게** 한다 — 회사 규칙셋은 프로젝트마다 다르고
    142개를 미리 알 수 없다. 대신 판정 근거를 전부 실어 보내 사용자가 검증할 수 있게 한다.

    ⚠ 정직성: RCR 은 파일×규칙 카운트가 최상세라 **같은 줄인지는 확인할 수 없다**.
    카운트 일치는 상관이지 증명이 아니다 — `overlap_upper_bound` 라는 이름이 그 경계다
    (확정 중복분이 아니라 상한). 파일 귀속이 없는 항목(RCMA)은 애초에 제외한다.
    """
    real = {
        p: rc for p, rc in per_file.items()
        if rc and not (p in pseudo or is_cross_module_key(p))
    }
    rules = sorted({r for rc in real.values() for r in rc})
    out: List[Dict[str, Any]] = []
    for i, a in enumerate(rules):
        for b in rules[i + 1:]:
            both = [p for p, rc in real.items() if rc.get(a, 0) > 0 and rc.get(b, 0) > 0]
            if len(both) < CO_RES_MIN_FILES:
                continue
            same = [p for p in both if real[p][a] == real[p][b]]
            if len(same) < CO_RES_MIN_FILES or len(same) / len(both) < CO_RES_MIN_RATIO:
                continue
            ga = (descriptions.get(a) or {}).get("group") or ""
            gb = (descriptions.get(b) or {}).get("group") or ""
            out.append({
                "rules": [a, b],
                "titles": [
                    (descriptions.get(a) or {}).get("title"),
                    (descriptions.get(b) or {}).get("title"),
                ],
                "groups": [ga, gb],
                # 규칙셋이 다르면 '중복 계상'의 강한 신호다 — 같은 셋 안의 인접 규칙
                # (10.6/10.8 처럼)은 원래 관련이라 놀랍지 않다.
                # ⚠ 3-state. 그룹을 모르면(RCFInfo 부재 → 규칙 설명이 통째로 없음) False 가
                #   아니라 **None** 이다 — False 는 "같은 규칙셋"이라는 단정이고, 실측
                #   HDPDM01 이 정확히 그 상태에서 False 로 나갔다(증거 부재 ≠ 같은 규칙셋).
                "cross_ruleset": (ga != gb) if (ga and gb) else None,
                "files": len(both),
                "identical_files": len(same),
                "strength": "identical" if len(same) == len(both) else "mostly_identical",
                # 겹칠 수 있는 최대치(상한) — 확정 중복분이 아니다.
                "overlap_upper_bound": sum(min(real[p][a], real[p][b]) for p in both),
                "totals": {
                    a: sum(rc.get(a, 0) for rc in real.values()),
                    b: sum(rc.get(b, 0) for rc in real.values()),
                },
                "sample_files": [
                    {"file": p, a: real[p][a], b: real[p][b]} for p in same[:3]
                ],
            })
    out.sort(key=lambda e: (-int(e["overlap_upper_bound"]), e["rules"][0], e["rules"][1]))
    return out[:CO_RES_MAX]


def _measurement_ambiguities(
    trend: Dict[str, Any], details: Dict[str, Any], per_file: Dict[str, Dict[str, int]],
    pseudo: Set[str], applied: Optional[Set[str]],
) -> List[Dict[str, Any]]:
    """측정 근거가 불확실한 지점 — 숫자를 그대로 믿으면 안 되는 곳들.

    실측에서 확인된 것들이다: 규칙셋 on/off가 만든 가짜 증감, 파일에 귀속되지 않는 위반,
    RCFInfo 부재로 인한 활성 판정 불가, 관측 1개 규칙, 규칙 귀속이 없는 residual.
    """
    out: List[Dict[str, Any]] = []
    builds = trend.get("builds") or []
    sizes = trend.get("ruleset_sizes") or []
    rules = trend.get("rules") or []

    # ① 규칙셋 크기가 변한 구간 — 그 구간의 증감은 코드 변화가 아닐 수 있다.
    # ⚠ **관측(non-None)끼리** 이어야 한다. 배열 인덱스로 바로 이웃을 비교하면 사이에 낀
    #    미분석 빌드(RCR 없음 → None)가 변화를 삼킨다 — 실측 KJPDS02_PV는 #116(104) →
    #    #117(미분석) → #120(242) 이라 단순 이웃 비교로는 규칙셋 2.3배 확장을 못 봤다.
    observed = [i for i, s in enumerate(sizes) if s is not None and i < len(builds)]
    for a_idx, b_idx in zip(observed, observed[1:]):
        a, b = sizes[a_idx], sizes[b_idx]
        if a == b:
            continue
        affected = [
            r["rule"] for r in rules
            if isinstance(r.get("counts"), list) and b_idx < len(r["counts"])
            and (r["counts"][a_idx] is None) != (r["counts"][b_idx] is None)
        ]
        out.append({
            "kind": "ruleset_change",
            "from_build": builds[a_idx].get("build_number"),
            "to_build": builds[b_idx].get("build_number"),
            "from_size": a, "to_size": b,
            "affected_rules": sorted(affected)[:12],
            "affected_total": len(affected),
            "detail": "규칙셋이 바뀐 구간입니다 — 이 구간의 위반 증감은 코드 변화가 아니라 검사 범위 변화일 수 있습니다.",
        })

    # ② 파일에 귀속되지 않는 위반(RCMA류) — 규칙별 비중이 큰 순.
    unattributed: Dict[str, int] = {}
    for path, rc in per_file.items():
        if not (path in pseudo or is_cross_module_key(path)):
            continue
        for rule, cnt in rc.items():
            unattributed[rule] = unattributed.get(rule, 0) + int(cnt)
    if unattributed:
        totals: Dict[str, int] = {}
        for rc in per_file.values():
            for rule, cnt in rc.items():
                totals[rule] = totals.get(rule, 0) + int(cnt)
        rows = sorted(unattributed.items(), key=lambda kv: (-kv[1], kv[0]))[:6]
        out.append({
            "kind": "unattributed",
            "rules": [
                {"rule": r, "unattributed": c, "total": totals.get(r, c)} for r, c in rows
            ],
            "detail": "이 위반들은 특정 파일에 귀속되지 않는 모듈 간 분석(RCMA) 집계입니다 — 파일 단위 조치 대상을 특정할 수 없습니다.",
        })

    # ③ RCFInfo 부재 — 활성/비활성 판정 자체가 불가(증거 부재 ≠ 위험 없음).
    if applied is None:
        out.append({
            "kind": "ruleset_unknown",
            "detail": "이 빌드의 RCR에 규칙 설정(RCFInfo)이 없어 어떤 규칙이 활성인지 판정할 수 없습니다 — 상충 후보의 '상대 규칙이 활성인가'를 확인하지 못한 상태입니다.",
        })

    # ④ 관측 1개 규칙 — 추세를 단정할 수 없다.
    single = [r["rule"] for r in rules if r.get("classification_reason") == "insufficient_observations"]
    if single:
        out.append({
            "kind": "single_observation",
            "rules": sorted(single)[:12], "total": len(single),
            "detail": "이 규칙들은 관측이 1개뿐이라 증가/감소를 판정하지 않았습니다.",
        })

    # ⑤ residual — 규칙 귀속이 없는 잔여 위반.
    residual_counts = (trend.get("residual") or {}).get("counts") or []
    latest_residual = next((c for c in reversed(residual_counts) if c is not None), None)
    if latest_residual:
        out.append({
            "kind": "residual", "count": latest_residual,
            "detail": "원본 리포트가 '상위 규칙'으로 분해하지 않은 잔여 위반입니다 — 어느 규칙인지 알 수 없어 상충 판정 대상에서 제외됩니다.",
        })

    # ⑥ 파일 총계와 규칙 분해 합의 차이 — 리포트 자체의 미귀속분.
    fs_total = details.get("filestatus_total_vc")
    attributed = details.get("violations_attributed_total")
    if isinstance(fs_total, int) and isinstance(attributed, int) and fs_total > attributed:
        out.append({
            "kind": "file_unattributed", "total": fs_total, "attributed": attributed,
            "gap": fs_total - attributed,
            "detail": "원본 QAC 리포트의 총 위반과 파일별 합계가 다릅니다 — 차이만큼은 파일에 귀속되지 않은 위반입니다.",
        })
    return out


def _generated_ambiguities(
    per_file: Dict[str, Dict[str, int]], pseudo: Set[str], build_root: Optional[Path],
) -> Tuple[List[Dict[str, Any]], Dict[str, Any]]:
    """자동 생성 코드의 위반 — 손댈 수 없는 파일과 조치 대상을 구분한다.

    반환 (목록, 마커 검사 상태). 두 번째 값은 이 목록이 **얼마나 완전한지**를 말한다:

    - ``available=False`` — 소스 스냅샷이 없어 마커를 **한 건도** 못 봤다. 경로 규칙으로
      잡힌 것만 목록에 있다. ⚠ 이전 구현은 이 상태에서도 `unprobed=0` 을 돌려줘 화면이
      "전부 확인했고 자동 생성이 아니다"로 읽혔다 — 실측에서 스냅샷 없는 캐시 루트가
      드물지 않다(이 PC 의 캐시 루트 4개 중 3개).
    - ``unprobed>0`` — 상한(MAX_MARKER_PROBES)에 걸려 못 본 파일 수.

    ⚠ 상한 절단은 **위반이 많은 파일부터** 검사한 뒤에 걸려야 한다. 예전엔 파일명
    알파벳순이라 실측 KJPDS02_DV 에서 6개가 이름 순으로 잘렸다 — 상한이 있는 곳에서는
    무엇이 남는지가 곧 품질이다(`_headroom_evidence` 가 여유 작은 순으로 자르는 것과 같다).
    """
    from backend.services.rule_fix_examples import build_snapshot_index, snapshot_dir

    out: List[Dict[str, Any]] = []
    real = [
        (p, rc) for p, rc in per_file.items()
        if rc and not (p in pseudo or is_cross_module_key(p))
    ]
    for path, rc in real:
        if is_generated_path(path):
            out.append({
                "file": path, "basis": "path",
                "violations": int(sum(rc.values())), "rules": sorted(rc.keys()),
            })
    # 경로로 판정되지 않은 나머지만 마커 확인 대상 — 위반 많은 순(상한에 잘려도 큰 것이 남는다).
    need_probe = sorted(
        ((p, rc) for p, rc in real if not is_generated_path(p)),
        key=lambda e: (-int(sum(e[1].values())), str(e[0])),
    )
    snapshot = snapshot_dir(build_root)
    probe: Dict[str, Any] = {
        "available": snapshot is not None,
        "reason": None if snapshot is not None else (
            "latest_build_not_cached" if build_root is None else "no_source_snapshot"
        ),
        "candidates": len(need_probe), "probed": 0, "unprobed": 0,
        "cap": MAX_MARKER_PROBES, "head_bytes": MARKER_HEAD_BYTES,
    }
    if snapshot is None or build_root is None:
        # 스냅샷이 없으면 마커 축 전체가 미측정이다 — 후보를 전부 '못 봄'으로 돌린다.
        probe["unprobed"] = len(need_probe)
    else:
        # 마커 확인은 파일마다 스냅샷 트리를 걷는다 — 인덱스를 1회 만들어 재사용한다
        # (실측 프로파일에서 이 rglob 반복이 전체 시간의 58%였다).
        index = build_snapshot_index(Path(build_root)) if need_probe else None
        for path, rc in need_probe:
            if probe["probed"] >= MAX_MARKER_PROBES:
                probe["unprobed"] += 1  # 상한 초과 — 자동 생성일 수도 있으나 확인하지 못했다
                continue
            probe["probed"] += 1
            if _marker_in_snapshot(build_root, path, index):
                out.append({
                    "file": path, "basis": "marker",
                    "violations": int(sum(rc.values())), "rules": sorted(rc.keys()),
                })
    out.sort(key=lambda e: (-int(e["violations"]), str(e["file"])))
    return out, probe


def compute_rule_conflicts(
    *, job_url: str, cache_root: Path, limit: int = 15,
    max_conflicts: int = DEFAULT_MAX_CONFLICTS, table_path: Optional[Path] = None,
) -> Dict[str, Any]:
    """상충 후보 + 애매한 지점 산출(결정론). 실패는 available:false + reason."""
    table = load_conflict_table(table_path)
    trend = compute_rule_trend(job_url=job_url, cache_root=cache_root, limit=limit, max_rules=200)
    if not trend.get("available"):
        return {
            "ok": True, "available": False,
            "reason": trend.get("reason") or "no_cached_build",
            "table": {k: table.get(k) for k in ("available", "reason", "version", "source_note")},
        }
    if not table.get("available"):
        return {
            "ok": True, "available": False, "reason": table.get("reason") or "table_missing",
            "table": {k: table.get(k) for k in ("available", "reason", "version", "source_note")},
        }

    rng = trend.get("observed_range") or {}
    metas = list_cached_builds_meta(job_url=job_url, cache_root=cache_root)
    to_meta = find_build_meta(metas, rng.get("to_build"))
    build_root = Path(str(to_meta.get("build_root"))) if to_meta else None

    details: Dict[str, Any] = {}
    per_file: Dict[str, Dict[str, int]] = {}
    pseudo: Set[str] = set()
    applied: Optional[Set[str]] = None
    functions: Dict[str, Dict[str, str]] = {}
    # 최신 빌드의 RCR을 못 읽으면 위반 표가 통째로 비어 '상충 없음'처럼 보인다 — 그건
    # 좋은 소식이 아니라 측정 실패다. 사유를 따로 들고 나가 화면이 구분할 수 있게 한다.
    latest_rcr_reason: Optional[str] = None
    # ⚠ 메트릭 축도 **같은 규약**이 필요하다. HMR이 없으면 headroom 증거가 빈 목록이 되는데,
    #   그건 '여유 있음'이 아니라 '못 봄'이다. RCR에만 사유를 달고 메트릭 축을 빼놓은 게
    #   직전 라운드의 비대칭이었다(같은 종류의 침묵을 한쪽에서만 막았다).
    metrics_reason: Optional[str] = None
    if to_meta is None:
        latest_rcr_reason = "latest_build_not_cached"
        metrics_reason = "latest_build_not_cached"
    else:
        loaded = load_rcr_details_cached(
            build_root, Path(str(to_meta.get("reports_dir") or ""))
        )
        if loaded is None:
            latest_rcr_reason = "latest_rcr_unreadable"
        else:
            details = loaded["details"]
            per_file = file_rule_counts(details)
            pseudo = cross_module_keys(details)
            applied = rules_applied_in_build(details)
        hmr = load_his_metrics_cached(build_root, Path(str(to_meta.get("reports_dir") or "")))
        if hmr is None:
            metrics_reason = "no_hmr"
        else:
            functions = hmr.get("functions") or {}
            if not functions:
                metrics_reason = "hmr_empty"

    # 자동 생성 판별을 **상충 루프보다 먼저** 한다. 두 축이 서로를 모르면 화면이 "고쳐라"라고
    # 내미는 최상위 항목이 사실은 손댈 수 없는 파일일 수 있다 — 실측 HDPDM01
    # `macro-identifier-uniqueness`(Rule-5.4)는 파일 귀속 256건이 **256건 모두** 자동 생성
    # 파일(lin_cfg.h)이었고, 정렬이 위반 수 내림차순이라 목록 맨 위에 있었다.
    generated_rows, generated_probe = _generated_ambiguities(per_file, pseudo, build_root)
    generated_files: Set[str] = {str(g["file"]) for g in generated_rows}
    # 소스 스냅샷 유무는 **여러 축을 동시에 결정한다** — 마커 확인·코드 발췌(LLM 지침)·구간 diff.
    # 판정은 `rule_fix_examples.snapshot_dir` 한 곳에서만 온다(두 계층이 각자 세면 갈린다).
    snapshot_reason: Optional[str] = None if generated_probe["available"] else str(generated_probe["reason"])

    descriptions: Dict[str, Any] = details.get("rule_descriptions") or {}
    categories: Dict[str, str] = table.get("rule_categories") or {}
    trend_rules: Dict[str, Dict[str, Any]] = {r["rule"]: r for r in (trend.get("rules") or []) if r.get("rule")}
    # 규칙별 최신 위반 합(파일 분해 기준) — 트렌드 latest 와 달리 파일 귀속분만 센다.
    rule_totals: Dict[str, int] = {}
    for rc in per_file.values():
        for rule, cnt in rc.items():
            rule_totals[rule] = rule_totals.get(rule, 0) + int(cnt)

    def _violating(rule: str) -> int:
        """이 규칙의 현재 위반 수 — 파일 분해 우선, 없으면 트렌드 최신값."""
        if rule in rule_totals:
            return rule_totals[rule]
        latest = (trend_rules.get(rule) or {}).get("latest")
        return int(latest) if isinstance(latest, int) else 0

    def _active(rule: str) -> Optional[bool]:
        """규칙이 이 빌드에서 검사되는가 — 판정 불가면 None(RCFInfo 부재).

        ⚠ **위반이 1건이라도 있으면 적용된 것**이다(위반이 곧 검사의 증거). RCFInfo는
        빌드마다 있기도 없기도 하고 규칙셋 표기도 갈리는데, 카운트만으로 확실한 이 근거를
        무시하면 실제로 걸리고 있는 규칙을 '검사 안 함'으로 접어버린다 —
        prqa_rule_trend 가 카운트>0을 null 로 접지 않는 것과 같은 규약이다.
        """
        if _violating(rule) > 0:
            return True
        if applied is None:
            return None
        return rule in applied

    conflicts: List[Dict[str, Any]] = []
    # 후보가 통째로 빠진 사유 — 제외를 침묵시키면 "왜 이 상충은 안 보이나"에 답할 수 없다.
    # 위반이 없어 건너뛴 항목(대다수)은 개수만, 상대 규칙이 꺼져 성립하지 않는 항목은 목록으로.
    skipped_no_violation = 0
    excluded: List[Dict[str, Any]] = []
    for entry in table.get("conflicts") or []:
        # ① 고칠 대상: 실제로 위반이 있는 규칙만. 위반 0인 규칙을 '고칠 때'를 경고할 이유가 없다.
        #    (`_active` 는 위반>0 이면 True 를 돌려주므로 여기서 다시 물을 필요가 없다.)
        fixing = [r for r in entry["when_fixing"] if _violating(r) > 0]
        if not fixing:
            skipped_no_violation += 1
            continue
        # ② 상대 규칙: 활성인 것만. 규칙셋에 없거나 비활성이면 그 규칙으로는 걸릴 수 없다.
        risky: List[str] = []
        filtered: List[Dict[str, str]] = []
        for r in entry["may_violate"]:
            state = _active(r)
            if state is False:
                filtered.append({"rule": r, "reason": "not_in_ruleset"})
            else:
                risky.append(r)
        if not risky and entry["kind"] != "process_tension":
            # 상대 규칙이 전부 걸러졌다 — 이 프로젝트에선 상충이 성립하지 않는다(좋은 소식이지만
            # 근거를 남긴다: 규칙 설정이 바뀌면 되살아나는 후보다).
            # 상대 규칙 자체가 테이블에 없는 항목(may_violate 빈 배열)은 다른 사유다 —
            # '비활성이라 성립 안 함'으로 적으면 없는 규칙을 껐다고 말하는 셈이다.
            excluded.append({
                "id": entry["id"],
                "reason": "counterpart_inactive" if filtered else "no_counterpart_rule",
                "fixing": fixing, "inactive": [f["rule"] for f in filtered],
            })
            continue

        windows, windows_total = _window_evidence(trend_rules, fixing, risky)
        cooc, cooc_total = _cooccurrence_evidence(per_file, fixing, risky, pseudo, generated_files)
        fixing_files = [
            p for p, rc in per_file.items()
            if any(rc.get(r, 0) > 0 for r in fixing) and not (p in pseudo or is_cross_module_key(p))
        ]
        headroom, headroom_total = _headroom_evidence(functions, fixing_files, entry["metric_risk"])
        # 이 상충의 메트릭 축을 실제로 볼 수 있었나 — 빈 목록의 뜻을 여기서 확정한다.
        #   n/a  = 이 상충은 메트릭을 밀지 않는다(볼 게 없다)
        #   측정 = 봤고 여유가 임계보다 크다 / 여유 없는 함수를 찾았다
        #   불가 = HMR 부재·파일 미귀속 등으로 못 봤다 ← 이걸 '여유 있음'으로 접으면 안 된다
        if not entry["metric_risk"]:
            metric_axis: Dict[str, Any] = {"applicable": False, "checked": False, "reason": None}
        elif metrics_reason is not None:
            metric_axis = {"applicable": True, "checked": False, "reason": metrics_reason}
        elif not fixing_files:
            metric_axis = {"applicable": True, "checked": False, "reason": "no_attributed_file"}
        else:
            metric_axis = {
                "applicable": True, "checked": True, "reason": None,
                "files_checked": len(fixing_files), "threshold": HEADROOM_THRESHOLD,
            }

        # 이 상충으로 LLM 지침을 만들 수 있는가 — 버튼을 누르기 전에 알 수 있어야 한다.
        # 위반이 전부 파일 미귀속(RCMA)이면 스냅샷 발췌가 **원리적으로** 불가능하다:
        # '못 찾음'과 '없음'은 사용자가 취할 조치가 다르다(전자는 재수집, 후자는 도구 한계).
        fixing_total = fixing_cross = fixing_generated = 0
        for p, rc in per_file.items():
            n = sum(rc.get(r, 0) for r in fixing)
            if n <= 0:
                continue
            fixing_total += n
            if p in pseudo or is_cross_module_key(p):
                fixing_cross += n
            elif p in generated_files:
                fixing_generated += n
        # ⚠ 증거가 **있어도 전부 cross_module 이면** 스냅샷 발췌는 못 만든다
        #    (`_collect_conflict_evidence` 가 pseudo 항목을 걸러낸다). 그걸 available:True 로
        #    두면 버튼을 눌러야만 실패를 알게 되고, 그때 나오는 사유도 틀린다.
        usable = [
            e for e in (cooc + windows) if e.get("scope") != "cross_module"
        ]
        # 고칠 규칙이 실제 파일에 귀속된 위반을 가진 파일들 — 상대 규칙이 아직 0건이어도
        # **고칠 코드는 실재한다**. 이 기능의 핵심 용도가 예방적 경고인데, 동시 위반만
        # 근거로 삼으면 가장 큰 항목이 통째로 막힌다(실측: Rule-2.2+C-POS-012 169건이
        # 실파일 5개·82건 귀속인데도 상대 규칙 위반이 0이라 지침 불가였다).
        fixing_file_rows = sorted(
            (
                {
                    "file": p, "count": sum(rc.get(r, 0) for r in fixing),
                    **({"generated": True} if p in generated_files else {}),
                }
                for p, rc in per_file.items()
                if not (p in pseudo or is_cross_module_key(p))
                and sum(rc.get(r, 0) for r in fixing) > 0
            ),
            # 손댈 수 있는 파일 먼저 — 상한에 잘려도 조치 가능한 증거가 남는다(발췌도 이걸 쓴다).
            key=lambda e: (bool(e.get("generated")), -int(e["count"]), str(e["file"])),
        )[:MAX_EVIDENCE_PER_KIND]
        if (usable or fixing_file_rows) and snapshot_reason is not None:
            # ⚠ 발췌할 파일은 있는데 **소스 스냅샷이 없어** 못 뽑는 경우. 예전엔 이 축을 안 봐서
            #    available:True 로 버튼을 내밀고, 눌러야 나오는 사유가 'no_code_evidence'
            #    (도구 한계)로 **틀리게** 붙었다 — 실제 조치는 정반대다(빌드를 다시 받으면
            #    해결된다). 실측 재현 6/6.
            # ⚠ 순서가 중요하다: 애초에 귀속된 위반이 없으면(전부 RCMA·또는 0건) 스냅샷을
            #    받아와도 소용없으므로 아래 cross_module_only / no_code_evidence 가 우선이다.
            advice = {"available": False, "reason": snapshot_reason, "basis": None}
        elif usable:
            advice = {"available": True, "reason": None, "basis": "cooccurrence"}
        elif fixing_file_rows:
            # 예방적 — 상대 규칙은 아직 안 걸렸다. LLM 에 그 사실을 명시해 "이미 걸려 있다"는
            # 서술을 막는다(프롬프트가 아니라 입력 데이터로 알린다).
            advice = {"available": True, "reason": None, "basis": "fixing_only"}
        elif fixing_total > 0 and fixing_cross == fixing_total:
            advice = {"available": False, "reason": "cross_module_only", "basis": None,
                      "unattributed": fixing_cross, "total": fixing_total}
        else:
            advice = {"available": False, "reason": "no_code_evidence", "basis": None}

        # 실측 증거(관측)는 RCFInfo 유무와 무관하게 유효하다 — 같은 파일에 두 규칙 위반이
        # 함께 있다는 건 그 자체로 사실이다. 반면 증거가 하나도 없을 때의 근거는 '상대 규칙이
        # 활성'뿐인데, RCFInfo가 없으면 그것조차 확인 못 한 것이므로 '활성'이라 부르면 거짓이다.
        if windows:
            tier = "window"
        elif cooc:
            tier = "cooccurrence"
        elif headroom:
            tier = "metric_headroom"
        elif applied is None:
            tier = "ruleset_unknown"
        else:
            tier = "ruleset_active"
        ruleset_unknown = applied is None

        conflicts.append({
            "id": entry["id"],
            "kind": entry["kind"],
            "tier": tier,
            "tier_note": TIER_NOTE.get(tier, ""),
            "ruleset_unknown": ruleset_unknown,
            "fixing": [_rule_meta(r, descriptions, categories, rule_totals) for r in fixing],
            "risk": [_rule_meta(r, descriptions, categories, rule_totals) for r in risky],
            "risk_filtered": filtered,
            "evidence": {"windows": windows, "cooccurrence": cooc, "metric_headroom": headroom},
            # 상한(MAX_EVIDENCE_PER_KIND)에 잘린 사실을 화면이 말할 수 있게 전체 건수도 싣는다.
            # 실측 KJPDS02_DV `unsigned-wrap-guard` 는 공존 파일이 9개인데 6개만 보였고,
            # 조치 대상 파일은 23개 중 6개만 보였다 — 침묵 절단은 "이게 전부"로 읽힌다.
            "evidence_totals": {
                "windows": windows_total, "cooccurrence": cooc_total,
                "metric_headroom": headroom_total, "fixing_files": len(fixing_files),
            },
            # 빈 evidence 의 뜻을 확정하는 두 필드 — 없으면 화면이 '안전'으로 오독한다.
            "metric_axis": metric_axis,
            # ⚠ 이 상충의 위반 중 **손댈 수 없는 자동 생성 파일 몫**. 이게 없으면 "고쳐라"라고
            #    내민 최상위 항목이 사실 전부 생성 코드일 수 있다(실측 HDPDM01 Rule-5.4 256/256).
            #    빼지 않고 표시한다 — 빼면 총계가 다른 화면과 안 맞는다.
            "generated": {
                "violations": fixing_generated,
                "attributed_total": fixing_total - fixing_cross,
                "files": sorted(
                    p for p in fixing_files if p in generated_files
                ),
                "probe": {"available": generated_probe["available"], "reason": generated_probe["reason"]},
            },
            "advice": advice,
            # 고칠 규칙이 실제로 위반 중인 파일 — 상대 규칙이 아직 0건일 때 예방적 지침의 근거.
            "fixing_files": fixing_file_rows,
            "mechanism": entry["mechanism"],
            "resolutions": entry["resolutions"],
            "deviation_hint": entry["deviation_hint"],
            "metric_risk": entry["metric_risk"],
            "confidence": entry["confidence"],
            "refs": entry["refs"],
            # 정렬·표시용 — 이 상충이 지금 얼마나 큰 덩어리인가.
            "fixing_violations": sum(_violating(r) for r in fixing),
        })

    conflicts.sort(key=lambda c: (
        TIER_ORDER.get(c["tier"], 9), -int(c["fixing_violations"]), c["id"],
    ))
    omitted = max(0, len(conflicts) - max_conflicts)
    conflicts = conflicts[:max_conflicts]

    by_rule: Dict[str, List[str]] = {}
    for c in conflicts:
        for meta in c["fixing"]:
            by_rule.setdefault(meta["rule"], []).append(c["id"])

    # 판단이 필요한 지점 = 실측 근거가 있는 후보(지금 당장 마주치는 것) 우선.
    judgement = [
        {
            "id": c["id"], "tier": c["tier"],
            "fixing": [m["rule"] for m in c["fixing"]],
            "risk": [m["rule"] for m in c["risk"]],
            "categories": sorted({m["category"] for m in c["fixing"] + c["risk"] if m.get("category")}),
            "kind": c["kind"],
            "confidence": c["confidence"],
        }
        for c in conflicts if c["tier"] in ("window", "cooccurrence")
    ]

    return {
        "ok": True,
        "available": True,
        "reason": None,
        "build_number": rng.get("to_build"),
        "note": CONFLICT_NOTE,
        "table": {
            "available": True, "reason": None,
            "version": table.get("version"),
            "source_note": table.get("source_note"),
            "category_note": table.get("category_note"),
            "total": len(table.get("conflicts") or []),
            # 대조 결과의 나머지 — 합이 total 이 되어야 표가 자립한다.
            "skipped_no_violation": skipped_no_violation,
            "excluded": excluded,
        },
        "ruleset": {
            "available": applied is not None,
            "enabled_count": len(applied) if applied is not None else None,
            # ⚠ enabled_count 는 **최신 빌드의 RCFInfo** 에서 온다. 예전엔 여기에 트렌드의
            #   descriptions_source_build(설명을 가져온 빌드 — 더 옛날일 수 있다)를 실어
            #   두 빌드의 값이 한 객체에 섞였다. 규칙 수의 출처는 그 수를 센 빌드다.
            "source_build": rng.get("to_build") if applied is not None else None,
            "descriptions_source_build": trend.get("descriptions_source_build"),
            # RCR 자체를 못 읽은 것과 RCR은 읽었으나 RCFInfo가 없는 것은 사유가 다르다 —
            # 전자를 'no_rcfinfo'로 적으면 리포트 부재가 규칙 설정 부재로 위장된다.
            "reason": None if applied is not None else (latest_rcr_reason or "no_rcfinfo"),
        },
        # 최신 빌드의 위반 표가 비어 있는 사유(측정 실패 vs 진짜 0) — null이면 정상 측정.
        "latest_rcr_reason": latest_rcr_reason,
        # 메트릭 축(HMR) 가용성 — RCR과 대칭. metric_headroom 이 비었을 때 '여유 있음'인지
        # '못 봄'인지는 이 필드로만 구분된다.
        "metrics": {
            "available": metrics_reason is None,
            "reason": metrics_reason,
            "function_count": len(functions) or None,
            "headroom_threshold": HEADROOM_THRESHOLD,
        },
        # 소스 스냅샷 축 — RCR·메트릭과 **같은 급의 침묵**이다. 스냅샷이 없으면 자동 생성
        # 마커도, LLM 지침의 코드 발췌도, 구간 diff 도 만들 수 없다. 이 축을 응답에 안 실었던
        # 탓에 화면이 "확인했고 자동 생성 아님"·"지침 생성 가능"을 둘 다 거짓으로 말했다.
        "snapshot": {
            "available": generated_probe["available"],
            "reason": generated_probe["reason"],
        },
        "conflicts": conflicts,
        "conflicts_omitted": omitted,
        "by_rule": by_rule,
        # 상충의 반대편 — "고치면 걸린다"만 보여주면 질문의 반쪽만 답하는 것이다.
        "co_resolution": _co_resolution_candidates(per_file, pseudo, descriptions),
        "co_resolution_note": CO_RESOLUTION_NOTE,
        "ambiguities": {
            "conflict": judgement,
            "measurement": _measurement_ambiguities(trend, details, per_file, pseudo, applied),
            "generated": generated_rows,
            # 마커 확인의 완전성 — 스냅샷 부재(한 건도 못 봄)와 상한 초과를 구분한다.
            # ⚠ 예전엔 `generated_unprobed` 숫자 하나뿐이라, 스냅샷이 아예 없어 **0건 확인**
            #    한 상태도 `0`(=전부 확인함)으로 보고됐다. 같은 0이 정반대를 뜻했다.
            "generated_probe": generated_probe,
            "generated_unprobed": generated_probe["unprobed"],
            # 자동 생성 파일이 전체 위반에서 차지하는 몫 — 분모 없이 파일 목록만 주면
            # "몇 개뿐이네"로 읽힌다(실측 HDPDM01은 462건 중 318건 = 68.8%가 여기였다).
            "generated_share": {
                "violations": sum(int(g["violations"]) for g in generated_rows),
                "attributed_total": sum(
                    int(sum(rc.values())) for p, rc in per_file.items()
                    if rc and not (p in pseudo or is_cross_module_key(p))
                ),
            },
        },
    }
