/* Undefine all class, enum, field, namespace, struct, stubbed function,
   testable function, and union names (disable by setting
   VCAST_DO_NOT_UNDEF_FIELDS) */
#undef u8g_Lib_Sha256_Hash
#undef lin_tl_rx_queue
#undef u16g_SysDiag_SystemStatus
#undef u16g_SysDiag_BuzzerLevelMax
#undef u8g_SysDiag_MotorOverHeatActiveHold_F
#undef u8g_SysEepromCtrl_SleepMode
#undef u8g_SysEepromCtrl_MotorA1A2Output
#undef u16g_SysOptCtrl_OverOpenDeg
#undef s16g_SysOptCtrl_OverPos
#undef u8g_ApiIn_MotorDirection
#undef u8g_ApiIn_MotorCountSpeed
#undef u8g_ApiIn_MotorRps
#undef u16g_ApiIn_MotorLevel_A1
#undef u16g_ApiIn_MotorLevel_A2
#undef s16g_ApiIn_MotorCurrLvl
#undef u16g_ApiIn_MotorTempLvl
#undef u16g_ApiIn_HallSnsrLevel
#undef u16g_ApiIn_Vsup
#undef u16g_ApiIn_BandGap
#undef s16g_ApiIn_MotorPosition
#undef u8g_ApiOut_DoorAngle
#undef u8g_ApiOut_DoorState
#undef u8g_ApiOut_MotorCurrent
#undef u8g_ApiOut_Vsup
#undef u8g_DoorPreCtrl_MotorOverHeat_F
#undef u8g_SysUds_UsDoorCtrl
#undef u8g_SysUds_UsAutoOpenEn_F
#undef u8g_SysUds_UsDir
#undef u8g_SysUds_UsStepMsb
#undef u8g_SysUds_UsStepLsb
#undef u8g_SysUds_WdbiCmd
#undef u8g_SysUds_BuzzerTest_F
#undef u8g_SysUds_WriteData
#undef u16g_SysUds_UsMotorPwm
#undef u16g_SysUds_UsStep
#undef u8s_UdsSid
#undef u8s_DidMsb
#undef u8s_DidLsb
#undef u8s_SwIntVer
#undef u8s_DataBuffer
#undef u8s_UserServiceIdMsb
#undef u8s_UserServiceIdLsb
#undef u8t_Data
#undef u8t_DataInit
#undef u8t_MaxCount
#undef u16t_Data
#undef u16tDataInit
#undef u8t_MaxCount
#undef u8t_Data
#undef u8t_DataMin
#undef u8t_DataMax
#undef u16t_Data
#undef u16t_DataMin
#undef u16t_DataMax
#undef s16t_Data
#undef s16t_DataMin
#undef s16t_DataMax
#undef length
#undef data
#undef u16t_Offset
#undef u16t_Offset
#undef u16t_Offset
#undef u16t_Offset
#undef u16t_Offset
#undef u16t_Offset
#undef u16t_Offset
#undef u16t_Addr1
#undef u16t_Addr2
#undef u16t_Angle
#undef u8t_PwmData
#undef u16t_DidLsb
#undef u16t_DidLsb
#undef u16t_DidLsb
#undef u16t_DidLsb
#undef u8t_ServiceId
#undef u8t_ServiceId
#undef __T381822080
#undef g_Lib_Sha256_Nb_GetState
#undef ld_send_message
#undef u8g_SysEepromCtrl_ReadInlineData
#undef u8g_SysEepromCtrl_ReadDiagData
#undef u8g_SysEepromCtrl_ReadProdDate
#undef u8g_SysEepromCtrl_ReadPartNo
#undef u8g_SysEepromCtrl_ReadHwVer
#undef u8g_SysEepromCtrl_ReadDbVer
#undef u8g_SysEepromCtrl_ReadCrcByte
#undef u8g_SysEepromCtrl_ReadUdsData
#undef g_SysEepromCtrl_Reset
#undef g_SysOptionCtrl
#undef u16s_Pwm2Spd_Conv
#undef g_UDS_RDBI_Paser
#undef s_UDS_RDBI_ExtractParams
#undef s_UDS_RDBI_ProcessDatePartInfo
#undef s_UDS_RDBI_ProcessVersionInfo
#undef s_UDS_RDBI_ProcessSystemInfo
#undef s_UDS_RDBI_ProcessSystemStatus
#undef s_UDS_RDBI_ProdDate
#undef s_UDS_RDBI_PartNumber
#undef s_UDS_RDBI_SW_Version
#undef s_UDS_RDBI_HW_Version
#undef s_UDS_RDBI_DB_Version
#undef s_UDS_RDBI_SW_Unit1_Version
#undef s_UDS_RDBI_SW_Unit1_IVD
#undef s_UDS_RDBI_StatusCheck1
#undef s_UDS_RDBI_StatusCheck2
#undef s_UDS_RDBI_StatusCheck3
#undef g_UDS_WDBI_Paser
#undef s_UDS_WDBI_UserOptRecordId
#undef s_UDS_WDBI_UsOptMain
#undef s_UDS_WDBI_UsOpt_F1G
#undef s_UDS_WDBI_UsOpt_E2G_1
#undef s_UDS_WDBI_UsOpt_E2G_2
#undef s_UDS_WDBI_UsOpt_E2G_2_ProcessGroup1
#undef s_UDS_WDBI_UsOpt_E2G_2_ProcessGroup2
#undef s_UDS_WDBI_UsOpt_E2G_3
#undef s_UDS_WDBI_ProdDate
#undef s_UDS_WDBI_PartNumber
#undef s_UDS_WDBI_HW_Version
#undef s_UDS_WDBI_DB_Version
#undef s_UDS_WDBI_US_ReadEeprom
#undef s_UDS_WDBI_US_WiteEeprom
#undef s_UDS_WDBI_US_ApplyParam
#undef s_UDS_WDBI_US_ClearEeprom
#undef s_UDS_WDBI_US_ReadSysSts
#undef s_UDS_WDBI_US_UserCtrl
#undef s_UDS_WDBI_US_OpDataRead
#undef s_UDS_WDBI_US_SysOpt
#undef s_UDS_WDBI_US_BuzzTest
#undef s_UDS_WDBI_US_Reprogram
#undef s_UDS_WDBI_US_Write_Checksum
#undef s_UDS_WDBI_US_Read_Checksum
#undef g_UDS_SessionCtrl
#undef s_UDS_DSC_ProgSession
#undef s_UDS_SendNRC22_ConditionsNotCorrect
#undef g_UDS_LinComp_Reset
#undef queue_header
#undef queue_tail
#undef queue_status
#undef queue_current_size
#undef queue_max_size
#undef tl_pdu
#undef E_LIB_SHA256_NB_STATE
#undef E_LIB_SHA256_NB_STATE_IDLE
#undef E_LIB_SHA256_NB_STATE_ERROR
#undef ld_queue_status
#undef LD_NO_DATA
#undef LD_TRANSMIT_ERROR
