-- VectorCAST 25.sp4 (08/19/25)
-- Test Case Script
--
-- Environment    : SWUT_21_EEPROM
-- Unit(s) Under Test: EEPROM
--
-- Script Features
TEST.SCRIPT_FEATURE:C_DIRECT_ARRAY_INDEXING
TEST.SCRIPT_FEATURE:CPP_CLASS_OBJECT_REVISION
TEST.SCRIPT_FEATURE:MULTIPLE_UUT_SUPPORT
TEST.SCRIPT_FEATURE:REMOVED_CL_PREFIX
TEST.SCRIPT_FEATURE:MIXED_CASE_NAMES
TEST.SCRIPT_FEATURE:STATIC_HEADER_FUNCS_IN_UUTS
TEST.SCRIPT_FEATURE:VCAST_MAIN_NOT_RENAMED
--

-- Unit: EEPROM

-- Subprogram: BackupSector

-- Test Case: SwUFn_2104.001
TEST.UNIT:EEPROM
TEST.SUBPROGRAM:BackupSector
TEST.NEW
TEST.NAME:SwUFn_2104.001
TEST.NOTES:
REQ/BA
TEST.END_NOTES:
TEST.STUB:EEPROM.WriteBlock
TEST.STUB:EEPROM.SetupFCCOB
TEST.STUB:EEPROM.EraseSectorInternal
TEST.STUB:EEPROM.WriteWord
TEST.STUB:EEPROM.EEPROM_SetByte
TEST.STUB:EEPROM.EEPROM_GetByte
TEST.STUB:EEPROM.EEPROM_Init
TEST.VALUE:EEPROM.BackupSector.Addr:<<malloc 1>>
TEST.VALUE:EEPROM.BackupSector.Addr[0]:0
TEST.VALUE:EEPROM.BackupSector.From:0
TEST.VALUE:EEPROM.BackupSector.To:0
TEST.EXPECTED:EEPROM.<<GLOBAL>>.BackupArray[0..1]:0
TEST.END

-- Test Case: SwUFn_2104.002
TEST.UNIT:EEPROM
TEST.SUBPROGRAM:BackupSector
TEST.NEW
TEST.NAME:SwUFn_2104.002
TEST.NOTES:
REQ/BA
TEST.END_NOTES:
TEST.STUB:EEPROM.WriteBlock
TEST.STUB:EEPROM.SetupFCCOB
TEST.STUB:EEPROM.EraseSectorInternal
TEST.STUB:EEPROM.WriteWord
TEST.STUB:EEPROM.EEPROM_SetByte
TEST.STUB:EEPROM.EEPROM_GetByte
TEST.STUB:EEPROM.EEPROM_Init
TEST.VALUE:EEPROM.BackupSector.Addr:<<malloc 1>>
TEST.VALUE:EEPROM.BackupSector.Addr[0]:2147483647
TEST.VALUE:EEPROM.BackupSector.From:32767
TEST.VALUE:EEPROM.BackupSector.To:32767
TEST.EXPECTED:EEPROM.<<GLOBAL>>.BackupArray[0..1]:0
TEST.END

-- Test Case: SwUFn_2104.003
TEST.UNIT:EEPROM
TEST.SUBPROGRAM:BackupSector
TEST.NEW
TEST.NAME:SwUFn_2104.003
TEST.NOTES:
REQ/BA
TEST.END_NOTES:
TEST.STUB:EEPROM.WriteBlock
TEST.STUB:EEPROM.SetupFCCOB
TEST.STUB:EEPROM.EraseSectorInternal
TEST.STUB:EEPROM.WriteWord
TEST.STUB:EEPROM.EEPROM_SetByte
TEST.STUB:EEPROM.EEPROM_GetByte
TEST.STUB:EEPROM.EEPROM_Init
TEST.VALUE:EEPROM.BackupSector.Addr:<<malloc 1>>
TEST.VALUE:EEPROM.BackupSector.Addr[0]:4294967295
TEST.VALUE:EEPROM.BackupSector.From:65535
TEST.VALUE:EEPROM.BackupSector.To:65535
TEST.EXPECTED:EEPROM.<<GLOBAL>>.BackupArray[0..1]:0
TEST.END

-- Test Case: SwUFn_2104.004
TEST.UNIT:EEPROM
TEST.SUBPROGRAM:BackupSector
TEST.NEW
TEST.NAME:SwUFn_2104.004
TEST.NOTES:
REQ/FI
TEST.END_NOTES:
TEST.STUB:EEPROM.WriteBlock
TEST.STUB:EEPROM.SetupFCCOB
TEST.STUB:EEPROM.EraseSectorInternal
TEST.STUB:EEPROM.WriteWord
TEST.STUB:EEPROM.EEPROM_SetByte
TEST.STUB:EEPROM.EEPROM_GetByte
TEST.STUB:EEPROM.EEPROM_Init
TEST.VALUE:EEPROM.BackupSector.Addr:<<malloc 1>>
TEST.VALUE:EEPROM.BackupSector.Addr[0]:-1
TEST.VALUE:EEPROM.BackupSector.From:-1
TEST.VALUE:EEPROM.BackupSector.To:-1
TEST.EXPECTED:EEPROM.<<GLOBAL>>.BackupArray[0..1]:0
TEST.END

-- Test Case: SwUFn_2104.005
TEST.UNIT:EEPROM
TEST.SUBPROGRAM:BackupSector
TEST.NEW
TEST.NAME:SwUFn_2104.005
TEST.NOTES:
REQ/FI
TEST.END_NOTES:
TEST.STUB:EEPROM.WriteBlock
TEST.STUB:EEPROM.SetupFCCOB
TEST.STUB:EEPROM.EraseSectorInternal
TEST.STUB:EEPROM.WriteWord
TEST.STUB:EEPROM.EEPROM_SetByte
TEST.STUB:EEPROM.EEPROM_GetByte
TEST.STUB:EEPROM.EEPROM_Init
TEST.VALUE:EEPROM.BackupSector.Addr:<<malloc 1>>
TEST.VALUE:EEPROM.BackupSector.Addr[0]:4294967296
TEST.VALUE:EEPROM.BackupSector.From:65536
TEST.VALUE:EEPROM.BackupSector.To:65536
TEST.EXPECTED:EEPROM.<<GLOBAL>>.BackupArray[0..1]:0
TEST.END

-- Test Case: SwUFn_2104.006
TEST.UNIT:EEPROM
TEST.SUBPROGRAM:BackupSector
TEST.NEW
TEST.NAME:SwUFn_2104.006
TEST.NOTES:
REQ/FI
TEST.END_NOTES:
TEST.STUB:EEPROM.WriteBlock
TEST.STUB:EEPROM.SetupFCCOB
TEST.STUB:EEPROM.EraseSectorInternal
TEST.STUB:EEPROM.WriteWord
TEST.STUB:EEPROM.EEPROM_SetByte
TEST.STUB:EEPROM.EEPROM_GetByte
TEST.STUB:EEPROM.EEPROM_Init
TEST.VALUE:EEPROM.BackupSector.Addr:<<malloc 1>>
TEST.VALUE:EEPROM.BackupSector.Addr[0]:5004924896
TEST.VALUE:EEPROM.BackupSector.From:70154
TEST.VALUE:EEPROM.BackupSector.To:70154
TEST.EXPECTED:EEPROM.<<GLOBAL>>.BackupArray[0..1]:0
TEST.END

-- Test Case: SwUFn_2104.007
TEST.UNIT:EEPROM
TEST.SUBPROGRAM:BackupSector
TEST.NEW
TEST.NAME:SwUFn_2104.007
TEST.NOTES:
REQ/FI
TEST.END_NOTES:
TEST.STUB:EEPROM.WriteBlock
TEST.STUB:EEPROM.SetupFCCOB
TEST.STUB:EEPROM.EraseSectorInternal
TEST.STUB:EEPROM.WriteWord
TEST.STUB:EEPROM.EEPROM_SetByte
TEST.STUB:EEPROM.EEPROM_GetByte
TEST.STUB:EEPROM.EEPROM_Init
TEST.VALUE:EEPROM.BackupSector.Addr:<<malloc 1>>
TEST.VALUE:EEPROM.BackupSector.Addr[0]:5104000765
TEST.VALUE:EEPROM.BackupSector.From:72148
TEST.VALUE:EEPROM.BackupSector.To:72148
TEST.EXPECTED:EEPROM.<<GLOBAL>>.BackupArray[0..1]:0
TEST.END

-- Subprogram: EEPROM_GetByte

-- Test Case: SwUFn_2102.001
TEST.UNIT:EEPROM
TEST.SUBPROGRAM:EEPROM_GetByte
TEST.NEW
TEST.NAME:SwUFn_2102.001
TEST.IMPORT_FAILURES:
(E) @LINE: 203 TEST.VALUE:EEPROM.<<GLOBAL>>.EEPROMaddr:<<malloc 1>>
    >>> Unknown parameter/object name EEPROMaddr
    >>> Value Line Error - Command Ignored
(E) @LINE: 204 TEST.VALUE:EEPROM.<<GLOBAL>>.REG_FSTAT.Bits.CCIF:-1
    >>> Unknown parameter/object name REG_FSTAT
    >>> Value Line Error - Command Ignored
(E) @LINE: 205 TEST.EXPECTED:EEPROM.<<GLOBAL>>.EEPROMaddr[0]:65535
    >>> Unknown parameter/object name EEPROMaddr
    >>> Value Line Error - Command Ignored
TEST.END_IMPORT_FAILURES:
TEST.NOTES:
REQ/BA
TEST.END_NOTES:
TEST.STUB:EEPROM.BackupSector
TEST.STUB:EEPROM.WriteBlock
TEST.STUB:EEPROM.SetupFCCOB
TEST.STUB:EEPROM.EraseSectorInternal
TEST.STUB:EEPROM.WriteWord
TEST.STUB:EEPROM.EEPROM_SetByte
TEST.STUB:EEPROM.EEPROM_Init
TEST.VALUE:EEPROM.<<GLOBAL>>._FSTAT.Bits.CCIF:0
TEST.VALUE:EEPROM.EEPROM_GetByte.Addr:<<malloc 1>>
TEST.VALUE:EEPROM.EEPROM_GetByte.Addr[0]:0
TEST.EXPECTED:EEPROM.EEPROM_GetByte.return:2
TEST.END

-- Test Case: SwUFn_2102.002
TEST.UNIT:EEPROM
TEST.SUBPROGRAM:EEPROM_GetByte
TEST.NEW
TEST.NAME:SwUFn_2102.002
TEST.IMPORT_FAILURES:
(E) @LINE: 246 TEST.VALUE:EEPROM.<<GLOBAL>>.EEPROMaddr:<<malloc 1>>
    >>> Unknown parameter/object name EEPROMaddr
    >>> Value Line Error - Command Ignored
(E) @LINE: 247 TEST.VALUE:EEPROM.<<GLOBAL>>.REG_FSTAT.Bits.CCIF:0
    >>> Unknown parameter/object name REG_FSTAT
    >>> Value Line Error - Command Ignored
(E) @LINE: 248 TEST.EXPECTED:EEPROM.<<GLOBAL>>.EEPROMaddr[0]:0
    >>> Unknown parameter/object name EEPROMaddr
    >>> Value Line Error - Command Ignored
TEST.END_IMPORT_FAILURES:
TEST.NOTES:
REQ/BA
TEST.END_NOTES:
TEST.STUB:EEPROM.BackupSector
TEST.STUB:EEPROM.WriteBlock
TEST.STUB:EEPROM.SetupFCCOB
TEST.STUB:EEPROM.EraseSectorInternal
TEST.STUB:EEPROM.WriteWord
TEST.STUB:EEPROM.EEPROM_SetByte
TEST.STUB:EEPROM.EEPROM_Init
TEST.VALUE:EEPROM.<<GLOBAL>>._FSTAT.Bits.CCIF:0
TEST.VALUE:EEPROM.EEPROM_GetByte.Addr:<<malloc 1>>
TEST.VALUE:EEPROM.EEPROM_GetByte.Addr[0]:2147483647
TEST.EXPECTED:EEPROM.EEPROM_GetByte.return:2
TEST.END


-- Test Case: SwUFn_2102.003
TEST.UNIT:EEPROM
TEST.SUBPROGRAM:EEPROM_GetByte
TEST.NEW
TEST.NAME:SwUFn_2102.003
TEST.IMPORT_FAILURES:
(E) @LINE: 283 TEST.VALUE:EEPROM.<<GLOBAL>>.EEPROMaddr:<<malloc 1>>
    >>> Unknown parameter/object name EEPROMaddr
    >>> Value Line Error - Command Ignored
(E) @LINE: 284 TEST.VALUE:EEPROM.<<GLOBAL>>.REG_FSTAT.Bits.CCIF:64
    >>> Unknown parameter/object name REG_FSTAT
    >>> Value Line Error - Command Ignored
(E) @LINE: 285 TEST.EXPECTED:EEPROM.<<GLOBAL>>.EEPROMaddr[0]:0
    >>> Unknown parameter/object name EEPROMaddr
    >>> Value Line Error - Command Ignored
TEST.END_IMPORT_FAILURES:
TEST.NOTES:
REQ/BA
TEST.END_NOTES:
TEST.STUB:EEPROM.BackupSector
TEST.STUB:EEPROM.WriteBlock
TEST.STUB:EEPROM.SetupFCCOB
TEST.STUB:EEPROM.EraseSectorInternal
TEST.STUB:EEPROM.WriteWord
TEST.STUB:EEPROM.EEPROM_SetByte
TEST.STUB:EEPROM.EEPROM_Init
TEST.VALUE:EEPROM.<<GLOBAL>>._FSTAT.Bits.CCIF:1
TEST.VALUE:EEPROM.EEPROM_GetByte.Addr:<<malloc 1>>
TEST.VALUE:EEPROM.EEPROM_GetByte.Addr[0]:4294967295
TEST.EXPECTED:EEPROM.EEPROM_GetByte.return:2
TEST.END

-- Test Case: SwUFn_2102.004
TEST.UNIT:EEPROM
TEST.SUBPROGRAM:EEPROM_GetByte
TEST.NEW
TEST.NAME:SwUFn_2102.004
TEST.IMPORT_FAILURES:
(E) @LINE: 320 TEST.VALUE:EEPROM.<<GLOBAL>>.EEPROMaddr:<<malloc 1>>
    >>> Unknown parameter/object name EEPROMaddr
    >>> Value Line Error - Command Ignored
(E) @LINE: 321 TEST.VALUE:EEPROM.<<GLOBAL>>.REG_FSTAT.Bits.CCIF:128
    >>> Unknown parameter/object name REG_FSTAT
    >>> Value Line Error - Command Ignored
(E) @LINE: 322 TEST.EXPECTED:EEPROM.<<GLOBAL>>.EEPROMaddr[0]:0
    >>> Unknown parameter/object name EEPROMaddr
    >>> Value Line Error - Command Ignored
TEST.END_IMPORT_FAILURES:
TEST.NOTES:
REQ/FI
TEST.END_NOTES:
TEST.STUB:EEPROM.BackupSector
TEST.STUB:EEPROM.WriteBlock
TEST.STUB:EEPROM.SetupFCCOB
TEST.STUB:EEPROM.EraseSectorInternal
TEST.STUB:EEPROM.WriteWord
TEST.STUB:EEPROM.EEPROM_SetByte
TEST.STUB:EEPROM.EEPROM_Init
TEST.VALUE:EEPROM.<<GLOBAL>>._FSTAT.Bits.CCIF:-1
TEST.VALUE:EEPROM.EEPROM_GetByte.Addr:<<malloc 1>>
TEST.VALUE:EEPROM.EEPROM_GetByte.Addr[0]:-1
TEST.EXPECTED:EEPROM.EEPROM_GetByte.return:2
TEST.END


-- Test Case: SwUFn_2102.005
TEST.UNIT:EEPROM
TEST.SUBPROGRAM:EEPROM_GetByte
TEST.NEW
TEST.NAME:SwUFn_2102.005
TEST.IMPORT_FAILURES:
(E) @LINE: 357 TEST.VALUE:EEPROM.<<GLOBAL>>.EEPROMaddr:<<malloc 1>>
    >>> Unknown parameter/object name EEPROMaddr
    >>> Value Line Error - Command Ignored
(E) @LINE: 358 TEST.VALUE:EEPROM.<<GLOBAL>>.REG_FSTAT.Bits.CCIF:129
    >>> Unknown parameter/object name REG_FSTAT
    >>> Value Line Error - Command Ignored
(E) @LINE: 359 TEST.EXPECTED:EEPROM.<<GLOBAL>>.EEPROMaddr[0]:65535
    >>> Unknown parameter/object name EEPROMaddr
    >>> Value Line Error - Command Ignored
TEST.END_IMPORT_FAILURES:
TEST.NOTES:
REQ/BA
TEST.END_NOTES:
TEST.STUB:EEPROM.BackupSector
TEST.STUB:EEPROM.WriteBlock
TEST.STUB:EEPROM.SetupFCCOB
TEST.STUB:EEPROM.EraseSectorInternal
TEST.STUB:EEPROM.WriteWord
TEST.STUB:EEPROM.EEPROM_SetByte
TEST.STUB:EEPROM.EEPROM_Init
TEST.VALUE:EEPROM.<<GLOBAL>>._FSTAT.Bits.CCIF:2
TEST.VALUE:EEPROM.EEPROM_GetByte.Addr:<<malloc 1>>
TEST.VALUE:EEPROM.EEPROM_GetByte.Addr[0]:4294967296
TEST.EXPECTED:EEPROM.EEPROM_GetByte.return:2
TEST.END


-- Test Case: SwUFn_2102.006
TEST.UNIT:EEPROM
TEST.SUBPROGRAM:EEPROM_GetByte
TEST.NEW
TEST.NAME:SwUFn_2102.006
TEST.IMPORT_FAILURES:
(E) @LINE: 394 TEST.VALUE:EEPROM.<<GLOBAL>>.EEPROMaddr:<<malloc 1>>
    >>> Unknown parameter/object name EEPROMaddr
    >>> Value Line Error - Command Ignored
(E) @LINE: 395 TEST.VALUE:EEPROM.<<GLOBAL>>.REG_FSTAT.Bits.CCIF:0
    >>> Unknown parameter/object name REG_FSTAT
    >>> Value Line Error - Command Ignored
(E) @LINE: 396 TEST.EXPECTED:EEPROM.<<GLOBAL>>.EEPROMaddr[0]:0
    >>> Unknown parameter/object name EEPROMaddr
    >>> Value Line Error - Command Ignored
TEST.END_IMPORT_FAILURES:
TEST.NOTES:
REQ/BA
TEST.END_NOTES:
TEST.STUB:EEPROM.BackupSector
TEST.STUB:EEPROM.WriteBlock
TEST.STUB:EEPROM.SetupFCCOB
TEST.STUB:EEPROM.EraseSectorInternal
TEST.STUB:EEPROM.WriteWord
TEST.STUB:EEPROM.EEPROM_SetByte
TEST.STUB:EEPROM.EEPROM_Init
TEST.VALUE:EEPROM.<<GLOBAL>>._FSTAT.Bits.CCIF:5
TEST.VALUE:EEPROM.EEPROM_GetByte.Addr:<<malloc 1>>
TEST.VALUE:EEPROM.EEPROM_GetByte.Addr[0]:5000067296
TEST.EXPECTED:EEPROM.EEPROM_GetByte.return:2
TEST.END


-- Test Case: SwUFn_2102.007
TEST.UNIT:EEPROM
TEST.SUBPROGRAM:EEPROM_GetByte
TEST.NEW
TEST.NAME:SwUFn_2102.007
TEST.IMPORT_FAILURES:
(E) Errors from previous script import(s)
    >>> (E) @LINE: 608 TEST.VALUE:EEPROM.<<GLOBAL>>.REG_FSTAT.Bits.CCIF:2
    >>>     >>> Unknown parameter/object name REG_FSTAT
    >>>     >>> Value Line Error - Command Ignored
TEST.END_IMPORT_FAILURES:
TEST.NOTES:
REQ/BA
TEST.END_NOTES:
TEST.STUB:EEPROM.BackupSector
TEST.STUB:EEPROM.WriteBlock
TEST.STUB:EEPROM.SetupFCCOB
TEST.STUB:EEPROM.EraseSectorInternal
TEST.STUB:EEPROM.WriteWord
TEST.STUB:EEPROM.EEPROM_SetByte
TEST.STUB:EEPROM.EEPROM_Init
TEST.VALUE:EEPROM.<<GLOBAL>>._FSTAT.Bits.CCIF:10
TEST.VALUE:EEPROM.EEPROM_GetByte.Addr:<<malloc 1>>
TEST.VALUE:EEPROM.EEPROM_GetByte.Addr[0]:4900069496
TEST.EXPECTED:EEPROM.EEPROM_GetByte.return:2
TEST.END

-- Test Case: SwUFn_2102.008
TEST.UNIT:EEPROM
TEST.SUBPROGRAM:EEPROM_GetByte
TEST.NEW
TEST.NAME:SwUFn_2102.008
TEST.NOTES:
REQ/EC
TEST.END_NOTES:
TEST.STUB:EEPROM.BackupSector
TEST.STUB:EEPROM.WriteBlock
TEST.STUB:EEPROM.SetupFCCOB
TEST.STUB:EEPROM.EraseSectorInternal
TEST.STUB:EEPROM.WriteWord
TEST.STUB:EEPROM.EEPROM_SetByte
TEST.STUB:EEPROM.EEPROM_Init
TEST.EXPECTED:EEPROM.EEPROM_GetByte.return:0
TEST.VALUE_USER_CODE:EEPROM.<<GLOBAL>>._FSTAT.Bits.CCIF
<<EEPROM.<<GLOBAL>>._FSTAT>>.Bits.CCIF = ( 1 );
TEST.END_VALUE_USER_CODE:
TEST.VALUE_USER_CODE:EEPROM.EEPROM_GetByte.Addr
<<EEPROM.EEPROM_GetByte.Addr>> = ( (word *)0x001003F0UL );
TEST.END_VALUE_USER_CODE:
TEST.END

-- Test Case: SwUFn_2102.009
TEST.UNIT:EEPROM
TEST.SUBPROGRAM:EEPROM_GetByte
TEST.NEW
TEST.NAME:SwUFn_2102.009
TEST.NOTES:
REQ/EC
TEST.END_NOTES:
TEST.STUB:EEPROM.BackupSector
TEST.STUB:EEPROM.WriteBlock
TEST.STUB:EEPROM.SetupFCCOB
TEST.STUB:EEPROM.EraseSectorInternal
TEST.STUB:EEPROM.WriteWord
TEST.STUB:EEPROM.EEPROM_SetByte
TEST.STUB:EEPROM.EEPROM_Init
TEST.VALUE:EEPROM.<<GLOBAL>>._FSTAT.Bits.CCIF:0
TEST.EXPECTED:EEPROM.EEPROM_GetByte.return:8
TEST.VALUE_USER_CODE:EEPROM.EEPROM_GetByte.Addr
<<EEPROM.EEPROM_GetByte.Addr>> = ( (word *)0x001003F0UL );
TEST.END_VALUE_USER_CODE:
TEST.END

-- Test Case: SwUFn_2102.010
TEST.UNIT:EEPROM
TEST.SUBPROGRAM:EEPROM_GetByte
TEST.NEW
TEST.NAME:SwUFn_2102.010
TEST.NOTES:
REQ/EC
TEST.END_NOTES:
TEST.STUB:EEPROM.BackupSector
TEST.STUB:EEPROM.WriteBlock
TEST.STUB:EEPROM.SetupFCCOB
TEST.STUB:EEPROM.EraseSectorInternal
TEST.STUB:EEPROM.WriteWord
TEST.STUB:EEPROM.EEPROM_SetByte
TEST.STUB:EEPROM.EEPROM_Init
TEST.EXPECTED:EEPROM.EEPROM_GetByte.return:0
TEST.VALUE_USER_CODE:EEPROM.<<GLOBAL>>._FSTAT.Bits.CCIF
<<EEPROM.<<GLOBAL>>._FSTAT>>.Bits.CCIF = ( 1 );
TEST.END_VALUE_USER_CODE:
TEST.VALUE_USER_CODE:EEPROM.EEPROM_GetByte.Addr
<<EEPROM.EEPROM_GetByte.Addr>> = ( (word *)0x001003F1UL );
TEST.END_VALUE_USER_CODE:
TEST.END

-- Subprogram: EEPROM_Init

-- Test Case: SwUFn_2103.001
TEST.UNIT:EEPROM
TEST.SUBPROGRAM:EEPROM_Init
TEST.NEW
TEST.NAME:SwUFn_2103.001
TEST.IMPORT_FAILURES:
(E) @LINE: 532 TEST.VALUE:EEPROM.<<GLOBAL>>.EEPROMaddr:<<malloc 1>>
    >>> Unknown parameter/object name EEPROMaddr
    >>> Value Line Error - Command Ignored
(E) @LINE: 533 TEST.EXPECTED:EEPROM.<<GLOBAL>>.EEPROMaddr[0]:0
    >>> Unknown parameter/object name EEPROMaddr
    >>> Value Line Error - Command Ignored
(E) @LINE: 534 TEST.EXPECTED:EEPROM.<<GLOBAL>>.REG_FCLKDIV.Byte:0x1D
    >>> Unknown parameter/object name REG_FCLKDIV
    >>> Value Line Error - Command Ignored
TEST.END_IMPORT_FAILURES:
TEST.NOTES:
REQ/EC
TEST.END_NOTES:
TEST.STUB:EEPROM.BackupSector
TEST.STUB:EEPROM.WriteBlock
TEST.STUB:EEPROM.SetupFCCOB
TEST.STUB:EEPROM.EraseSectorInternal
TEST.STUB:EEPROM.WriteWord
TEST.STUB:EEPROM.EEPROM_SetByte
TEST.STUB:EEPROM.EEPROM_GetByte
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FCLKDIV.Byte:29
TEST.END

-- Subprogram: EEPROM_SetByte

-- Test Case: SwUFn_2101.001
TEST.UNIT:EEPROM
TEST.SUBPROGRAM:EEPROM_SetByte
TEST.NEW
TEST.NAME:SwUFn_2101.001
TEST.IMPORT_FAILURES:
(E) @LINE: 574 TEST.VALUE:EEPROM.<<GLOBAL>>.REG_FSTAT.Bits.CCIF:-1
    >>> Unknown parameter/object name REG_FSTAT
    >>> Value Line Error - Command Ignored
TEST.END_IMPORT_FAILURES:
TEST.NOTES:
REQ/BA
TEST.END_NOTES:
TEST.STUB:EEPROM.BackupSector
TEST.STUB:EEPROM.WriteBlock
TEST.STUB:EEPROM.SetupFCCOB
TEST.STUB:EEPROM.EraseSectorInternal
TEST.STUB:EEPROM.WriteWord
TEST.STUB:EEPROM.EEPROM_GetByte
TEST.STUB:EEPROM.EEPROM_Init
TEST.VALUE:EEPROM.<<GLOBAL>>.BackupArray[0..1]:0
TEST.VALUE:EEPROM.<<GLOBAL>>._FSTAT.Bits.CCIF:0
TEST.VALUE:EEPROM.EEPROM_SetByte.Addr:<<malloc 2>>
TEST.VALUE:EEPROM.EEPROM_SetByte.Addr[0]:0
TEST.VALUE:EEPROM.EEPROM_SetByte.Addr[1]:0
TEST.VALUE:EEPROM.EEPROM_SetByte.Data:0
TEST.EXPECTED:EEPROM.<<GLOBAL>>.BackupArray[0..1]:0
TEST.EXPECTED:EEPROM.EEPROM_SetByte.return:2
TEST.END

-- Test Case: SwUFn_2101.002
TEST.UNIT:EEPROM
TEST.SUBPROGRAM:EEPROM_SetByte
TEST.NEW
TEST.NAME:SwUFn_2101.002
TEST.IMPORT_FAILURES:
(E) @LINE: 612 TEST.VALUE:EEPROM.<<GLOBAL>>.REG_FSTAT.Bits.CCIF:0
    >>> Unknown parameter/object name REG_FSTAT
    >>> Value Line Error - Command Ignored
TEST.END_IMPORT_FAILURES:
TEST.NOTES:
REQ/BA
TEST.END_NOTES:
TEST.STUB:EEPROM.BackupSector
TEST.STUB:EEPROM.WriteBlock
TEST.STUB:EEPROM.SetupFCCOB
TEST.STUB:EEPROM.EraseSectorInternal
TEST.STUB:EEPROM.WriteWord
TEST.STUB:EEPROM.EEPROM_GetByte
TEST.STUB:EEPROM.EEPROM_Init
TEST.VALUE:EEPROM.<<GLOBAL>>.BackupArray[0..1]:32767
TEST.VALUE:EEPROM.<<GLOBAL>>._FSTAT.Bits.CCIF:0
TEST.VALUE:EEPROM.EEPROM_SetByte.Data:127
TEST.EXPECTED:EEPROM.<<GLOBAL>>.BackupArray[0..1]:32767
TEST.EXPECTED:EEPROM.EEPROM_SetByte.return:8
TEST.VALUE_USER_CODE:EEPROM.EEPROM_SetByte.Addr
<<EEPROM.EEPROM_SetByte.Addr>> = ( (word *)0x00100300UL );
TEST.END_VALUE_USER_CODE:
TEST.END


-- Test Case: SwUFn_2101.003
TEST.UNIT:EEPROM
TEST.SUBPROGRAM:EEPROM_SetByte
TEST.NEW
TEST.NAME:SwUFn_2101.003
TEST.IMPORT_FAILURES:
(E) @LINE: 650 TEST.VALUE:EEPROM.<<GLOBAL>>.REG_FSTAT.Bits.CCIF:1
    >>> Unknown parameter/object name REG_FSTAT
    >>> Value Line Error - Command Ignored
TEST.END_IMPORT_FAILURES:
TEST.NOTES:
REQ/BA
TEST.END_NOTES:
TEST.STUB:EEPROM.BackupSector
TEST.STUB:EEPROM.WriteBlock
TEST.STUB:EEPROM.SetupFCCOB
TEST.STUB:EEPROM.EraseSectorInternal
TEST.STUB:EEPROM.WriteWord
TEST.STUB:EEPROM.EEPROM_GetByte
TEST.STUB:EEPROM.EEPROM_Init
TEST.VALUE:EEPROM.<<GLOBAL>>.BackupArray[0..1]:65535
TEST.VALUE:EEPROM.<<GLOBAL>>._FSTAT.Bits.CCIF:1
TEST.VALUE:EEPROM.EEPROM_SetByte.Data:255
TEST.EXPECTED:EEPROM.<<GLOBAL>>.BackupArray[0..1]:65535
TEST.EXPECTED:EEPROM.EEPROM_SetByte.return:0
TEST.VALUE_USER_CODE:EEPROM.EEPROM_SetByte.Addr
<<EEPROM.EEPROM_SetByte.Addr>> = ( (word *)0x001003FFUL );
TEST.END_VALUE_USER_CODE:
TEST.END

-- Test Case: SwUFn_2101.004
TEST.UNIT:EEPROM
TEST.SUBPROGRAM:EEPROM_SetByte
TEST.NEW
TEST.NAME:SwUFn_2101.004
TEST.IMPORT_FAILURES:
(E) @LINE: 688 TEST.VALUE:EEPROM.<<GLOBAL>>.REG_FSTAT.Bits.CCIF:1
    >>> Unknown parameter/object name REG_FSTAT
    >>> Value Line Error - Command Ignored
TEST.END_IMPORT_FAILURES:
TEST.NOTES:
REQ/FI
TEST.END_NOTES:
TEST.STUB:EEPROM.BackupSector
TEST.STUB:EEPROM.WriteBlock
TEST.STUB:EEPROM.SetupFCCOB
TEST.STUB:EEPROM.EraseSectorInternal
TEST.STUB:EEPROM.WriteWord
TEST.STUB:EEPROM.EEPROM_GetByte
TEST.STUB:EEPROM.EEPROM_Init
TEST.VALUE:EEPROM.<<GLOBAL>>.BackupArray[0..1]:-1
TEST.VALUE:EEPROM.<<GLOBAL>>._FSTAT.Bits.CCIF:-1
TEST.VALUE:EEPROM.EEPROM_SetByte.Data:-1
TEST.EXPECTED:EEPROM.<<GLOBAL>>.BackupArray[0..1]:65535
TEST.EXPECTED:EEPROM.EEPROM_SetByte.return:0
TEST.VALUE_USER_CODE:EEPROM.EEPROM_SetByte.Addr
<<EEPROM.EEPROM_SetByte.Addr>> = ( (word *)0x001003F0UL );
TEST.END_VALUE_USER_CODE:
TEST.END

-- Test Case: SwUFn_2101.005
TEST.UNIT:EEPROM
TEST.SUBPROGRAM:EEPROM_SetByte
TEST.NEW
TEST.NAME:SwUFn_2101.005
TEST.IMPORT_FAILURES:
(E) @LINE: 725 TEST.VALUE:EEPROM.<<GLOBAL>>.REG_FSTAT.Bits.CCIF:2
    >>> Unknown parameter/object name REG_FSTAT
    >>> Value Line Error - Command Ignored
TEST.END_IMPORT_FAILURES:
TEST.NOTES:
REQ/BA
TEST.END_NOTES:
TEST.STUB:EEPROM.BackupSector
TEST.STUB:EEPROM.WriteBlock
TEST.STUB:EEPROM.SetupFCCOB
TEST.STUB:EEPROM.EraseSectorInternal
TEST.STUB:EEPROM.WriteWord
TEST.STUB:EEPROM.EEPROM_GetByte
TEST.STUB:EEPROM.EEPROM_Init
TEST.VALUE:EEPROM.<<GLOBAL>>.BackupArray[0..1]:65536
TEST.VALUE:EEPROM.<<GLOBAL>>._FSTAT.Bits.CCIF:2
TEST.VALUE:EEPROM.EEPROM_SetByte.Addr:<<malloc 1>>
TEST.VALUE:EEPROM.EEPROM_SetByte.Addr[0]:4294967296
TEST.VALUE:EEPROM.EEPROM_SetByte.Data:256
TEST.EXPECTED:EEPROM.<<GLOBAL>>.BackupArray[0..1]:0
TEST.EXPECTED:EEPROM.EEPROM_SetByte.return:2
TEST.END


-- Test Case: SwUFn_2101.006
TEST.UNIT:EEPROM
TEST.SUBPROGRAM:EEPROM_SetByte
TEST.NEW
TEST.NAME:SwUFn_2101.006
TEST.IMPORT_FAILURES:
(E) @LINE: 762 TEST.VALUE:EEPROM.<<GLOBAL>>.REG_FSTAT.Bits.CCIF:1
    >>> Unknown parameter/object name REG_FSTAT
    >>> Value Line Error - Command Ignored
TEST.END_IMPORT_FAILURES:
TEST.NOTES:
REQ/BA
TEST.END_NOTES:
TEST.STUB:EEPROM.BackupSector
TEST.STUB:EEPROM.WriteBlock
TEST.STUB:EEPROM.SetupFCCOB
TEST.STUB:EEPROM.EraseSectorInternal
TEST.STUB:EEPROM.WriteWord
TEST.STUB:EEPROM.EEPROM_GetByte
TEST.STUB:EEPROM.EEPROM_Init
TEST.VALUE:EEPROM.<<GLOBAL>>.BackupArray[0..1]:70000
TEST.VALUE:EEPROM.<<GLOBAL>>._FSTAT.Bits.CCIF:5
TEST.VALUE:EEPROM.EEPROM_SetByte.Addr:<<malloc 1>>
TEST.VALUE:EEPROM.EEPROM_SetByte.Addr[0]:5000000000
TEST.VALUE:EEPROM.EEPROM_SetByte.Data:300
TEST.EXPECTED:EEPROM.<<GLOBAL>>.BackupArray[0..1]:4464
TEST.EXPECTED:EEPROM.EEPROM_SetByte.return:2
TEST.END

-- Test Case: SwUFn_2101.007
TEST.UNIT:EEPROM
TEST.SUBPROGRAM:EEPROM_SetByte
TEST.NEW
TEST.NAME:SwUFn_2101.007
TEST.IMPORT_FAILURES:
(E) @LINE: 799 TEST.VALUE:EEPROM.<<GLOBAL>>.REG_FSTAT.Bits.CCIF:1
    >>> Unknown parameter/object name REG_FSTAT
    >>> Value Line Error - Command Ignored
TEST.END_IMPORT_FAILURES:
TEST.NOTES:
REQ/FI
TEST.END_NOTES:
TEST.STUB:EEPROM.BackupSector
TEST.STUB:EEPROM.WriteBlock
TEST.STUB:EEPROM.SetupFCCOB
TEST.STUB:EEPROM.EraseSectorInternal
TEST.STUB:EEPROM.WriteWord
TEST.STUB:EEPROM.EEPROM_GetByte
TEST.STUB:EEPROM.EEPROM_Init
TEST.VALUE:EEPROM.<<GLOBAL>>.BackupArray[0..1]:84266
TEST.VALUE:EEPROM.<<GLOBAL>>._FSTAT.Bits.CCIF:12
TEST.VALUE:EEPROM.EEPROM_SetByte.Addr:<<malloc 1>>
TEST.VALUE:EEPROM.EEPROM_SetByte.Addr[0]:5458712357
TEST.VALUE:EEPROM.EEPROM_SetByte.Data:452
TEST.EXPECTED:EEPROM.<<GLOBAL>>.BackupArray[0..1]:18730
TEST.EXPECTED:EEPROM.EEPROM_SetByte.return:2
TEST.END


-- Test Case: SwUFn_2101.008
TEST.UNIT:EEPROM
TEST.SUBPROGRAM:EEPROM_SetByte
TEST.NEW
TEST.NAME:SwUFn_2101.008
TEST.IMPORT_FAILURES:
(E) Errors from previous script import(s)
    >>> (E) @LINE: 995 TEST.VALUE:EEPROM.<<GLOBAL>>.REG_FSTAT.Bits.CCIF:1
    >>>     >>> Unknown parameter/object name REG_FSTAT
    >>>     >>> Value Line Error - Command Ignored
    >>> (E) @LINE: 996 TEST.EXPECTED:EEPROM.<<GLOBAL>>.REG_FCCOBIX.Byte:1
    >>>     >>> Unknown parameter/object name REG_FCCOBIX
    >>>     >>> Value Line Error - Command Ignored
    >>> (E) @LINE: 997 TEST.EXPECTED:EEPROM.<<GLOBAL>>.REG_FSTAT.Byte:0x80
    >>>     >>> Unknown parameter/object name REG_FSTAT
    >>>     >>> Value Line Error - Command Ignored
    >>> (E) @LINE: 998 TEST.EXPECTED:EEPROM.<<GLOBAL>>.REG_FCCOB0.Overlap_STR.FCCOB0HISTR.Byte:0x12
    >>>     >>> Unknown parameter/object name REG_FCCOB0
    >>>     >>> Value Line Error - Command Ignored
    >>> (E) @LINE: 999 TEST.EXPECTED:EEPROM.<<GLOBAL>>.REG_FCCOB0.Overlap_STR.FCCOB0LOSTR.Byte:0
    >>>     >>> Unknown parameter/object name REG_FCCOB0
    >>>     >>> Value Line Error - Command Ignored
    >>> (E) @LINE: 1000 TEST.EXPECTED:EEPROM.<<GLOBAL>>.REG_FCCOB1.Word:10322
    >>>     >>> Unknown parameter/object name REG_FCCOB1
    >>>     >>> Value Line Error - Command Ignored
TEST.END_IMPORT_FAILURES:
TEST.NOTES:
REQ/FI
TEST.END_NOTES:
TEST.STUB:EEPROM.BackupSector
TEST.STUB:EEPROM.WriteBlock
TEST.STUB:EEPROM.SetupFCCOB
TEST.STUB:EEPROM.EraseSectorInternal
TEST.STUB:EEPROM.WriteWord
TEST.STUB:EEPROM.EEPROM_GetByte
TEST.STUB:EEPROM.EEPROM_Init
TEST.VALUE:EEPROM.<<GLOBAL>>.BackupArray[0..1]:0
TEST.VALUE:EEPROM.<<GLOBAL>>._FSTAT.Bits.CCIF:0
TEST.VALUE:EEPROM.EEPROM_SetByte.Data:0
TEST.EXPECTED:EEPROM.<<GLOBAL>>.BackupArray[0..1]:0
TEST.EXPECTED:EEPROM.EEPROM_SetByte.return:8
TEST.VALUE_USER_CODE:EEPROM.EEPROM_SetByte.Addr
<<EEPROM.EEPROM_SetByte.Addr>> = ( (word *)0x00100300UL );
TEST.END_VALUE_USER_CODE:
TEST.END

-- Test Case: SwUFn_2101.009
TEST.UNIT:EEPROM
TEST.SUBPROGRAM:EEPROM_SetByte
TEST.NEW
TEST.NAME:SwUFn_2101.009
TEST.IMPORT_FAILURES:
(E) Errors from previous script import(s)
    >>> (E) @LINE: 1055 TEST.VALUE:EEPROM.<<GLOBAL>>.REG_FSTAT.Bits.CCIF:1
    >>>     >>> Unknown parameter/object name REG_FSTAT
    >>>     >>> Value Line Error - Command Ignored
    >>> (E) @LINE: 1056 TEST.EXPECTED:EEPROM.<<GLOBAL>>.REG_FCCOBIX.Byte:1
    >>>     >>> Unknown parameter/object name REG_FCCOBIX
    >>>     >>> Value Line Error - Command Ignored
    >>> (E) @LINE: 1057 TEST.EXPECTED:EEPROM.<<GLOBAL>>.REG_FSTAT.Byte:0x80
    >>>     >>> Unknown parameter/object name REG_FSTAT
    >>>     >>> Value Line Error - Command Ignored
    >>> (E) @LINE: 1058 TEST.EXPECTED:EEPROM.<<GLOBAL>>.REG_FCCOB0.Overlap_STR.FCCOB0HISTR.Byte:0x12
    >>>     >>> Unknown parameter/object name REG_FCCOB0
    >>>     >>> Value Line Error - Command Ignored
    >>> (E) @LINE: 1059 TEST.EXPECTED:EEPROM.<<GLOBAL>>.REG_FCCOB0.Overlap_STR.FCCOB0LOSTR.Byte:0
    >>>     >>> Unknown parameter/object name REG_FCCOB0
    >>>     >>> Value Line Error - Command Ignored
    >>> (E) @LINE: 1060 TEST.EXPECTED:EEPROM.<<GLOBAL>>.REG_FCCOB1.Word:10322
    >>>     >>> Unknown parameter/object name REG_FCCOB1
    >>>     >>> Value Line Error - Command Ignored
TEST.END_IMPORT_FAILURES:
TEST.NOTES:
REQ/FI
TEST.END_NOTES:
TEST.STUB:EEPROM.BackupSector
TEST.STUB:EEPROM.WriteBlock
TEST.STUB:EEPROM.SetupFCCOB
TEST.STUB:EEPROM.EraseSectorInternal
TEST.STUB:EEPROM.WriteWord
TEST.STUB:EEPROM.EEPROM_GetByte
TEST.STUB:EEPROM.EEPROM_Init
TEST.VALUE:EEPROM.<<GLOBAL>>.BackupArray[0..1]:0
TEST.VALUE:EEPROM.<<GLOBAL>>._FSTAT.Bits.CCIF:1
TEST.VALUE:EEPROM.EEPROM_SetByte.Data:0
TEST.EXPECTED:EEPROM.<<GLOBAL>>.BackupArray[0..1]:0
TEST.EXPECTED:EEPROM.EEPROM_SetByte.return:0
TEST.VALUE_USER_CODE:EEPROM.EEPROM_SetByte.Addr
<<EEPROM.EEPROM_SetByte.Addr>> = ( (word *)0x001003FFUL );
TEST.END_VALUE_USER_CODE:
TEST.END

-- Test Case: SwUFn_2101.010
TEST.UNIT:EEPROM
TEST.SUBPROGRAM:EEPROM_SetByte
TEST.NEW
TEST.NAME:SwUFn_2101.010
TEST.NOTES:
REQ/FI
TEST.END_NOTES:
TEST.STUB:EEPROM.BackupSector
TEST.STUB:EEPROM.WriteBlock
TEST.STUB:EEPROM.SetupFCCOB
TEST.STUB:EEPROM.EraseSectorInternal
TEST.STUB:EEPROM.WriteWord
TEST.STUB:EEPROM.EEPROM_GetByte
TEST.STUB:EEPROM.EEPROM_Init
TEST.VALUE:EEPROM.<<GLOBAL>>.BackupArray[0..1]:0
TEST.VALUE:EEPROM.<<GLOBAL>>._FSTAT.Bits.CCIF:1
TEST.VALUE:EEPROM.EraseSectorInternal.return:1
TEST.VALUE:EEPROM.EEPROM_SetByte.Data:0
TEST.EXPECTED:EEPROM.<<GLOBAL>>.BackupArray[0..1]:0
TEST.EXPECTED:EEPROM.EEPROM_SetByte.return:1
TEST.VALUE_USER_CODE:EEPROM.EEPROM_SetByte.Addr
<<EEPROM.EEPROM_SetByte.Addr>> = ( (word *)0x001003F0UL );
TEST.END_VALUE_USER_CODE:
TEST.END

-- Subprogram: EraseSectorInternal

-- Test Case: SwUFn_2106.001
TEST.UNIT:EEPROM
TEST.SUBPROGRAM:EraseSectorInternal
TEST.NEW
TEST.NAME:SwUFn_2106.001
TEST.IMPORT_FAILURES:
(E) @LINE: 974 TEST.VALUE:EEPROM.<<GLOBAL>>.REG_FSTAT.Bits.CCIF:-1
    >>> Unknown parameter/object name REG_FSTAT
    >>> Value Line Error - Command Ignored
(E) @LINE: 975 TEST.EXPECTED:EEPROM.<<GLOBAL>>.REG_FCCOBIX.Byte:1
    >>> Unknown parameter/object name REG_FCCOBIX
    >>> Value Line Error - Command Ignored
(E) @LINE: 976 TEST.EXPECTED:EEPROM.<<GLOBAL>>.REG_FSTAT.Byte:0x80
    >>> Unknown parameter/object name REG_FSTAT
    >>> Value Line Error - Command Ignored
(E) @LINE: 977 TEST.EXPECTED:EEPROM.<<GLOBAL>>.REG_FCCOB0.Overlap_STR.FCCOB0HISTR.Byte:0x12
    >>> Unknown parameter/object name REG_FCCOB0
    >>> Value Line Error - Command Ignored
(E) @LINE: 978 TEST.EXPECTED:EEPROM.<<GLOBAL>>.REG_FCCOB0.Overlap_STR.FCCOB0LOSTR.Byte:0
    >>> Unknown parameter/object name REG_FCCOB0
    >>> Value Line Error - Command Ignored
(E) @LINE: 979 TEST.EXPECTED:EEPROM.<<GLOBAL>>.REG_FCCOB1.Word:10314
    >>> Unknown parameter/object name REG_FCCOB1
    >>> Value Line Error - Command Ignored
TEST.END_IMPORT_FAILURES:
TEST.NOTES:
REQ/BA
TEST.END_NOTES:
TEST.STUB:EEPROM.BackupSector
TEST.STUB:EEPROM.WriteBlock
TEST.STUB:EEPROM.SetupFCCOB
TEST.STUB:EEPROM.WriteWord
TEST.STUB:EEPROM.EEPROM_SetByte
TEST.STUB:EEPROM.EEPROM_GetByte
TEST.STUB:EEPROM.EEPROM_Init
TEST.VALUE:EEPROM.<<GLOBAL>>._FSTAT.Byte:0
TEST.VALUE:EEPROM.<<GLOBAL>>._FSTAT.Bits.CCIF:0
TEST.VALUE:EEPROM.EraseSectorInternal.Addr:<<malloc 1>>
TEST.VALUE:EEPROM.EraseSectorInternal.Addr[0]:0
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FCCOBIX.Byte:0
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FSTAT.Byte:0
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FCCOB0.Overlap_STR.FCCOB0HISTR.Byte:0
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FCCOB0.Overlap_STR.FCCOB0LOSTR.Byte:0
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FCCOB1.Word:0
TEST.EXPECTED:EEPROM.EraseSectorInternal.return:8
TEST.END

-- Test Case: SwUFn_2106.002
TEST.UNIT:EEPROM
TEST.SUBPROGRAM:EraseSectorInternal
TEST.NEW
TEST.NAME:SwUFn_2106.002
TEST.IMPORT_FAILURES:
(E) @LINE: 1034 TEST.VALUE:EEPROM.<<GLOBAL>>.REG_FSTAT.Bits.CCIF:0
    >>> Unknown parameter/object name REG_FSTAT
    >>> Value Line Error - Command Ignored
(E) @LINE: 1035 TEST.EXPECTED:EEPROM.<<GLOBAL>>.REG_FCCOBIX.Byte:0
    >>> Unknown parameter/object name REG_FCCOBIX
    >>> Value Line Error - Command Ignored
(E) @LINE: 1036 TEST.EXPECTED:EEPROM.<<GLOBAL>>.REG_FSTAT.Byte:0x0
    >>> Unknown parameter/object name REG_FSTAT
    >>> Value Line Error - Command Ignored
(E) @LINE: 1037 TEST.EXPECTED:EEPROM.<<GLOBAL>>.REG_FCCOB0.Overlap_STR.FCCOB0HISTR.Byte:0x0
    >>> Unknown parameter/object name REG_FCCOB0
    >>> Value Line Error - Command Ignored
(E) @LINE: 1038 TEST.EXPECTED:EEPROM.<<GLOBAL>>.REG_FCCOB0.Overlap_STR.FCCOB0LOSTR.Byte:0
    >>> Unknown parameter/object name REG_FCCOB0
    >>> Value Line Error - Command Ignored
(E) @LINE: 1039 TEST.EXPECTED:EEPROM.<<GLOBAL>>.REG_FCCOB1.Word:0
    >>> Unknown parameter/object name REG_FCCOB1
    >>> Value Line Error - Command Ignored
TEST.END_IMPORT_FAILURES:
TEST.NOTES:
REQ/BA
TEST.END_NOTES:
TEST.STUB:EEPROM.BackupSector
TEST.STUB:EEPROM.WriteBlock
TEST.STUB:EEPROM.SetupFCCOB
TEST.STUB:EEPROM.WriteWord
TEST.STUB:EEPROM.EEPROM_SetByte
TEST.STUB:EEPROM.EEPROM_GetByte
TEST.STUB:EEPROM.EEPROM_Init
TEST.VALUE:EEPROM.<<GLOBAL>>._FSTAT.Byte:127
TEST.VALUE:EEPROM.<<GLOBAL>>._FSTAT.Bits.CCIF:0
TEST.VALUE:EEPROM.EraseSectorInternal.Addr:<<malloc 1>>
TEST.VALUE:EEPROM.EraseSectorInternal.Addr[0]:2147483647
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FCCOBIX.Byte:0
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FSTAT.Byte:127
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FCCOB0.Overlap_STR.FCCOB0HISTR.Byte:0
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FCCOB0.Overlap_STR.FCCOB0LOSTR.Byte:0
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FCCOB1.Word:0
TEST.EXPECTED:EEPROM.EraseSectorInternal.return:8
TEST.END

-- Test Case: SwUFn_2106.003
TEST.UNIT:EEPROM
TEST.SUBPROGRAM:EraseSectorInternal
TEST.NEW
TEST.NAME:SwUFn_2106.003
TEST.IMPORT_FAILURES:
(E) @LINE: 1094 TEST.VALUE:EEPROM.<<GLOBAL>>.REG_FSTAT.Bits.CCIF:1
    >>> Unknown parameter/object name REG_FSTAT
    >>> Value Line Error - Command Ignored
(E) @LINE: 1095 TEST.EXPECTED:EEPROM.<<GLOBAL>>.REG_FCCOBIX.Byte:1
    >>> Unknown parameter/object name REG_FCCOBIX
    >>> Value Line Error - Command Ignored
(E) @LINE: 1096 TEST.EXPECTED:EEPROM.<<GLOBAL>>.REG_FSTAT.Byte:0x80
    >>> Unknown parameter/object name REG_FSTAT
    >>> Value Line Error - Command Ignored
(E) @LINE: 1097 TEST.EXPECTED:EEPROM.<<GLOBAL>>.REG_FCCOB0.Overlap_STR.FCCOB0HISTR.Byte:0x12
    >>> Unknown parameter/object name REG_FCCOB0
    >>> Value Line Error - Command Ignored
(E) @LINE: 1098 TEST.EXPECTED:EEPROM.<<GLOBAL>>.REG_FCCOB0.Overlap_STR.FCCOB0LOSTR.Byte:0
    >>> Unknown parameter/object name REG_FCCOB0
    >>> Value Line Error - Command Ignored
(E) @LINE: 1099 TEST.EXPECTED:EEPROM.<<GLOBAL>>.REG_FCCOB1.Word:10322
    >>> Unknown parameter/object name REG_FCCOB1
    >>> Value Line Error - Command Ignored
TEST.END_IMPORT_FAILURES:
TEST.NOTES:
REQ/BA
TEST.END_NOTES:
TEST.STUB:EEPROM.BackupSector
TEST.STUB:EEPROM.WriteBlock
TEST.STUB:EEPROM.SetupFCCOB
TEST.STUB:EEPROM.WriteWord
TEST.STUB:EEPROM.EEPROM_SetByte
TEST.STUB:EEPROM.EEPROM_GetByte
TEST.STUB:EEPROM.EEPROM_Init
TEST.VALUE:EEPROM.<<GLOBAL>>._FSTAT.Byte:255
TEST.VALUE:EEPROM.<<GLOBAL>>._FSTAT.Bits.CCIF:1
TEST.VALUE:EEPROM.EraseSectorInternal.Addr:<<malloc 1>>
TEST.VALUE:EEPROM.EraseSectorInternal.Addr[0]:4294967295
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FCCOBIX.Byte:1
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FSTAT.Byte:128
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FCCOB0.Overlap_STR.FCCOB0HISTR.Byte:18
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FCCOB0.Overlap_STR.FCCOB0LOSTR.Byte:0
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FCCOB1.Word:7284
TEST.EXPECTED:EEPROM.EraseSectorInternal.return:0
TEST.END

-- Test Case: SwUFn_2106.004
TEST.UNIT:EEPROM
TEST.SUBPROGRAM:EraseSectorInternal
TEST.NEW
TEST.NAME:SwUFn_2106.004
TEST.IMPORT_FAILURES:
(E) @LINE: 1154 TEST.VALUE:EEPROM.<<GLOBAL>>.REG_FSTAT.Bits.CCIF:1
    >>> Unknown parameter/object name REG_FSTAT
    >>> Value Line Error - Command Ignored
(E) @LINE: 1155 TEST.EXPECTED:EEPROM.<<GLOBAL>>.REG_FCCOBIX.Byte:1
    >>> Unknown parameter/object name REG_FCCOBIX
    >>> Value Line Error - Command Ignored
(E) @LINE: 1156 TEST.EXPECTED:EEPROM.<<GLOBAL>>.REG_FSTAT.Byte:0x80
    >>> Unknown parameter/object name REG_FSTAT
    >>> Value Line Error - Command Ignored
(E) @LINE: 1157 TEST.EXPECTED:EEPROM.<<GLOBAL>>.REG_FCCOB0.Overlap_STR.FCCOB0HISTR.Byte:0x12
    >>> Unknown parameter/object name REG_FCCOB0
    >>> Value Line Error - Command Ignored
(E) @LINE: 1158 TEST.EXPECTED:EEPROM.<<GLOBAL>>.REG_FCCOB0.Overlap_STR.FCCOB0LOSTR.Byte:0
    >>> Unknown parameter/object name REG_FCCOB0
    >>> Value Line Error - Command Ignored
(E) @LINE: 1159 TEST.EXPECTED:EEPROM.<<GLOBAL>>.REG_FCCOB1.Word:10322
    >>> Unknown parameter/object name REG_FCCOB1
    >>> Value Line Error - Command Ignored
TEST.END_IMPORT_FAILURES:
TEST.NOTES:
REQ/FI
TEST.END_NOTES:
TEST.STUB:EEPROM.BackupSector
TEST.STUB:EEPROM.WriteBlock
TEST.STUB:EEPROM.SetupFCCOB
TEST.STUB:EEPROM.WriteWord
TEST.STUB:EEPROM.EEPROM_SetByte
TEST.STUB:EEPROM.EEPROM_GetByte
TEST.STUB:EEPROM.EEPROM_Init
TEST.VALUE:EEPROM.<<GLOBAL>>._FSTAT.Byte:-1
TEST.VALUE:EEPROM.<<GLOBAL>>._FSTAT.Bits.CCIF:-1
TEST.VALUE:EEPROM.EraseSectorInternal.Addr:<<malloc 1>>
TEST.VALUE:EEPROM.EraseSectorInternal.Addr[0]:-1
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FCCOBIX.Byte:1
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FSTAT.Byte:128
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FCCOB0.Overlap_STR.FCCOB0HISTR.Byte:18
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FCCOB0.Overlap_STR.FCCOB0LOSTR.Byte:0
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FCCOB1.Word:7276
TEST.EXPECTED:EEPROM.EraseSectorInternal.return:0
TEST.END


-- Test Case: SwUFn_2106.005
TEST.UNIT:EEPROM
TEST.SUBPROGRAM:EraseSectorInternal
TEST.NEW
TEST.NAME:SwUFn_2106.005
TEST.IMPORT_FAILURES:
(E) @LINE: 1214 TEST.VALUE:EEPROM.<<GLOBAL>>.REG_FSTAT.Bits.CCIF:1
    >>> Unknown parameter/object name REG_FSTAT
    >>> Value Line Error - Command Ignored
(E) @LINE: 1215 TEST.EXPECTED:EEPROM.<<GLOBAL>>.REG_FCCOBIX.Byte:1
    >>> Unknown parameter/object name REG_FCCOBIX
    >>> Value Line Error - Command Ignored
(E) @LINE: 1216 TEST.EXPECTED:EEPROM.<<GLOBAL>>.REG_FSTAT.Byte:0x80
    >>> Unknown parameter/object name REG_FSTAT
    >>> Value Line Error - Command Ignored
(E) @LINE: 1217 TEST.EXPECTED:EEPROM.<<GLOBAL>>.REG_FCCOB0.Overlap_STR.FCCOB0HISTR.Byte:0x12
    >>> Unknown parameter/object name REG_FCCOB0
    >>> Value Line Error - Command Ignored
(E) @LINE: 1218 TEST.EXPECTED:EEPROM.<<GLOBAL>>.REG_FCCOB0.Overlap_STR.FCCOB0LOSTR.Byte:0
    >>> Unknown parameter/object name REG_FCCOB0
    >>> Value Line Error - Command Ignored
(E) @LINE: 1219 TEST.EXPECTED:EEPROM.<<GLOBAL>>.REG_FCCOB1.Word:10322
    >>> Unknown parameter/object name REG_FCCOB1
    >>> Value Line Error - Command Ignored
TEST.END_IMPORT_FAILURES:
TEST.NOTES:
REQ/FI
TEST.END_NOTES:
TEST.STUB:EEPROM.BackupSector
TEST.STUB:EEPROM.WriteBlock
TEST.STUB:EEPROM.SetupFCCOB
TEST.STUB:EEPROM.WriteWord
TEST.STUB:EEPROM.EEPROM_SetByte
TEST.STUB:EEPROM.EEPROM_GetByte
TEST.STUB:EEPROM.EEPROM_Init
TEST.VALUE:EEPROM.<<GLOBAL>>._FSTAT.Byte:256
TEST.VALUE:EEPROM.<<GLOBAL>>._FSTAT.Bits.CCIF:2
TEST.VALUE:EEPROM.EraseSectorInternal.Addr:<<malloc 1>>
TEST.VALUE:EEPROM.EraseSectorInternal.Addr[0]:4294967296
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FCCOBIX.Byte:0
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FSTAT.Byte:0
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FCCOB0.Overlap_STR.FCCOB0HISTR.Byte:0
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FCCOB0.Overlap_STR.FCCOB0LOSTR.Byte:0
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FCCOB1.Word:0
TEST.EXPECTED:EEPROM.EraseSectorInternal.return:8
TEST.END

-- Test Case: SwUFn_2106.006
TEST.UNIT:EEPROM
TEST.SUBPROGRAM:EraseSectorInternal
TEST.NEW
TEST.NAME:SwUFn_2106.006
TEST.NOTES:
REQ/FI
TEST.END_NOTES:
TEST.STUB:EEPROM.BackupSector
TEST.STUB:EEPROM.WriteBlock
TEST.STUB:EEPROM.SetupFCCOB
TEST.STUB:EEPROM.WriteWord
TEST.STUB:EEPROM.EEPROM_SetByte
TEST.STUB:EEPROM.EEPROM_GetByte
TEST.STUB:EEPROM.EEPROM_Init
TEST.VALUE:EEPROM.<<GLOBAL>>._FSTAT.Byte:300
TEST.VALUE:EEPROM.<<GLOBAL>>._FSTAT.Bits.CCIF:100
TEST.VALUE:EEPROM.EraseSectorInternal.Addr:<<malloc 1>>
TEST.VALUE:EEPROM.EraseSectorInternal.Addr[0]:5421851548
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FCCOBIX.Byte:0
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FSTAT.Byte:44
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FCCOB0.Overlap_STR.FCCOB0HISTR.Byte:0
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FCCOB0.Overlap_STR.FCCOB0LOSTR.Byte:0
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FCCOB1.Word:0
TEST.EXPECTED:EEPROM.EraseSectorInternal.return:8
TEST.END

-- Test Case: SwUFn_2106.007
TEST.UNIT:EEPROM
TEST.SUBPROGRAM:EraseSectorInternal
TEST.NEW
TEST.NAME:SwUFn_2106.007
TEST.NOTES:
REQ/FI
TEST.END_NOTES:
TEST.STUB:EEPROM.BackupSector
TEST.STUB:EEPROM.WriteBlock
TEST.STUB:EEPROM.SetupFCCOB
TEST.STUB:EEPROM.WriteWord
TEST.STUB:EEPROM.EEPROM_SetByte
TEST.STUB:EEPROM.EEPROM_GetByte
TEST.STUB:EEPROM.EEPROM_Init
TEST.VALUE:EEPROM.<<GLOBAL>>._FSTAT.Byte:451
TEST.VALUE:EEPROM.<<GLOBAL>>._FSTAT.Bits.CCIF:150
TEST.VALUE:EEPROM.EraseSectorInternal.Addr:<<malloc 1>>
TEST.VALUE:EEPROM.EraseSectorInternal.Addr[0]:7236942574
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FCCOBIX.Byte:0
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FSTAT.Byte:67
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FCCOB0.Overlap_STR.FCCOB0HISTR.Byte:0
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FCCOB0.Overlap_STR.FCCOB0LOSTR.Byte:0
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FCCOB1.Word:0
TEST.EXPECTED:EEPROM.EraseSectorInternal.return:8
TEST.END

-- Subprogram: SetupFCCOB

-- Test Case: SwUFn_2108.001
TEST.UNIT:EEPROM
TEST.SUBPROGRAM:SetupFCCOB
TEST.NEW
TEST.NAME:SwUFn_2108.001
TEST.NOTES:
REQ/EC
TEST.END_NOTES:
TEST.STUB:EEPROM.BackupSector
TEST.STUB:EEPROM.WriteBlock
TEST.STUB:EEPROM.EraseSectorInternal
TEST.STUB:EEPROM.WriteWord
TEST.STUB:EEPROM.EEPROM_SetByte
TEST.STUB:EEPROM.EEPROM_GetByte
TEST.STUB:EEPROM.EEPROM_Init
TEST.VALUE:<<OPTIONS>>.EVENT_LIMIT:10
TEST.VALUE:EEPROM.SetupFCCOB.PhraseAddr:0
TEST.VALUE:EEPROM.SetupFCCOB.From:0
TEST.VALUE:EEPROM.SetupFCCOB.To:0
TEST.VALUE:EEPROM.SetupFCCOB.Data:<<malloc 1>>
TEST.VALUE:EEPROM.SetupFCCOB.Data[0]:0x0
TEST.VALUE:EEPROM.SetupFCCOB.pIndex:<<malloc 1>>
TEST.VALUE:EEPROM.SetupFCCOB.pIndex[0]:0x0
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FCCOBIX.Byte:2
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FSTAT.Byte:48
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FCCOB0.Overlap_STR.FCCOB0HISTR.Byte:17
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FCCOB0.Overlap_STR.FCCOB0LOSTR.Byte:0
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FCCOB1.Word:0
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FCCOB2.Word:0
TEST.EXPECTED:EEPROM.SetupFCCOB.pIndex[0]:0x2
TEST.EXPECTED:EEPROM.SetupFCCOB.return:0
TEST.END

-- Test Case: SwUFn_2108.002
TEST.UNIT:EEPROM
TEST.SUBPROGRAM:SetupFCCOB
TEST.NEW
TEST.NAME:SwUFn_2108.002
TEST.NOTES:
REQ/EC
TEST.END_NOTES:
TEST.STUB:EEPROM.BackupSector
TEST.STUB:EEPROM.WriteBlock
TEST.STUB:EEPROM.EraseSectorInternal
TEST.STUB:EEPROM.WriteWord
TEST.STUB:EEPROM.EEPROM_SetByte
TEST.STUB:EEPROM.EEPROM_GetByte
TEST.STUB:EEPROM.EEPROM_Init
TEST.VALUE:<<OPTIONS>>.EVENT_LIMIT:10
TEST.VALUE:EEPROM.SetupFCCOB.PhraseAddr:0x7FFFFFFF
TEST.VALUE:EEPROM.SetupFCCOB.From:0x7FFF
TEST.VALUE:EEPROM.SetupFCCOB.To:0x7FFF
TEST.VALUE:EEPROM.SetupFCCOB.Data:<<malloc 1>>
TEST.VALUE:EEPROM.SetupFCCOB.Data[0]:0x7FFF
TEST.VALUE:EEPROM.SetupFCCOB.pIndex:<<malloc 1>>
TEST.VALUE:EEPROM.SetupFCCOB.pIndex[0]:0x7FFFF
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FCCOBIX.Byte:2
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FSTAT.Byte:48
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FCCOB0.Overlap_STR.FCCOB0HISTR.Byte:17
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FCCOB0.Overlap_STR.FCCOB0LOSTR.Byte:255
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FCCOB1.Word:65535
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FCCOB2.Word:0
TEST.EXPECTED:EEPROM.SetupFCCOB.pIndex[0]:0x7FFF
TEST.EXPECTED:EEPROM.SetupFCCOB.return:0
TEST.END

-- Test Case: SwUFn_2108.003
TEST.UNIT:EEPROM
TEST.SUBPROGRAM:SetupFCCOB
TEST.NEW
TEST.NAME:SwUFn_2108.003
TEST.NOTES:
REQ/BA
TEST.END_NOTES:
TEST.STUB:EEPROM.BackupSector
TEST.STUB:EEPROM.WriteBlock
TEST.STUB:EEPROM.EraseSectorInternal
TEST.STUB:EEPROM.WriteWord
TEST.STUB:EEPROM.EEPROM_SetByte
TEST.STUB:EEPROM.EEPROM_GetByte
TEST.STUB:EEPROM.EEPROM_Init
TEST.VALUE:<<OPTIONS>>.EVENT_LIMIT:10
TEST.VALUE:EEPROM.SetupFCCOB.PhraseAddr:0xFFFFFFFF
TEST.VALUE:EEPROM.SetupFCCOB.From:0xFFFF
TEST.VALUE:EEPROM.SetupFCCOB.To:0xFFFF
TEST.VALUE:EEPROM.SetupFCCOB.Data:<<malloc 1>>
TEST.VALUE:EEPROM.SetupFCCOB.Data[0]:0xFFFF
TEST.VALUE:EEPROM.SetupFCCOB.pIndex:<<malloc 1>>
TEST.VALUE:EEPROM.SetupFCCOB.pIndex[0]:0xFFFF
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FCCOBIX.Byte:2
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FSTAT.Byte:48
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FCCOB0.Overlap_STR.FCCOB0HISTR.Byte:17
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FCCOB0.Overlap_STR.FCCOB0LOSTR.Byte:255
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FCCOB1.Word:65535
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FCCOB2.Word:0
TEST.EXPECTED:EEPROM.SetupFCCOB.pIndex[0]:0xFFFF
TEST.EXPECTED:EEPROM.SetupFCCOB.return:0
TEST.END

-- Test Case: SwUFn_2108.004
TEST.UNIT:EEPROM
TEST.SUBPROGRAM:SetupFCCOB
TEST.NEW
TEST.NAME:SwUFn_2108.004
TEST.NOTES:
REQ/EC
TEST.END_NOTES:
TEST.STUB:EEPROM.BackupSector
TEST.STUB:EEPROM.WriteBlock
TEST.STUB:EEPROM.EraseSectorInternal
TEST.STUB:EEPROM.WriteWord
TEST.STUB:EEPROM.EEPROM_SetByte
TEST.STUB:EEPROM.EEPROM_GetByte
TEST.STUB:EEPROM.EEPROM_Init
TEST.VALUE:<<OPTIONS>>.EVENT_LIMIT:10
TEST.VALUE:EEPROM.SetupFCCOB.PhraseAddr:0xFFFFFFFF
TEST.VALUE:EEPROM.SetupFCCOB.From:0xFFFF
TEST.VALUE:EEPROM.SetupFCCOB.To:0x4
TEST.VALUE:EEPROM.SetupFCCOB.Data:<<malloc 1>>
TEST.VALUE:EEPROM.SetupFCCOB.Data[0]:0xFFFF
TEST.VALUE:EEPROM.SetupFCCOB.pIndex:<<malloc 1>>
TEST.VALUE:EEPROM.SetupFCCOB.pIndex[0]:0x0
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FCCOBIX.Byte:3
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FSTAT.Byte:48
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FCCOB0.Overlap_STR.FCCOB0HISTR.Byte:17
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FCCOB0.Overlap_STR.FCCOB0LOSTR.Byte:255
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FCCOB1.Word:65535
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FCCOB2.Word:65535
TEST.EXPECTED:EEPROM.SetupFCCOB.pIndex[0]:0x4
TEST.EXPECTED:EEPROM.SetupFCCOB.return:0
TEST.END

-- Test Case: SwUFn_2108.005
TEST.UNIT:EEPROM
TEST.SUBPROGRAM:SetupFCCOB
TEST.NEW
TEST.NAME:SwUFn_2108.005
TEST.NOTES:
REQ/EC
TEST.END_NOTES:
TEST.STUB:EEPROM.BackupSector
TEST.STUB:EEPROM.WriteBlock
TEST.STUB:EEPROM.EraseSectorInternal
TEST.STUB:EEPROM.WriteWord
TEST.STUB:EEPROM.EEPROM_SetByte
TEST.STUB:EEPROM.EEPROM_GetByte
TEST.STUB:EEPROM.EEPROM_Init
TEST.VALUE:<<OPTIONS>>.EVENT_LIMIT:10
TEST.VALUE:EEPROM.SetupFCCOB.PhraseAddr:0xFFFFFFFF
TEST.VALUE:EEPROM.SetupFCCOB.From:0xFFFF
TEST.VALUE:EEPROM.SetupFCCOB.To:0xFFFF
TEST.VALUE:EEPROM.SetupFCCOB.Data:<<malloc 1>>
TEST.VALUE:EEPROM.SetupFCCOB.Data[0]:0xFFFF
TEST.VALUE:EEPROM.SetupFCCOB.pIndex:<<malloc 1>>
TEST.VALUE:EEPROM.SetupFCCOB.pIndex[0]:0x0
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FCCOBIX.Byte:0x5
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FSTAT.Byte:48
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FCCOB0.Overlap_STR.FCCOB0HISTR.Byte:17
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FCCOB0.Overlap_STR.FCCOB0LOSTR.Byte:255
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FCCOB1.Word:65535
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FCCOB2.Word:65535
TEST.EXPECTED:EEPROM.SetupFCCOB.pIndex[0]:0x8
TEST.EXPECTED:EEPROM.SetupFCCOB.return:0
TEST.END

-- Test Case: SwUFn_2108.006
TEST.UNIT:EEPROM
TEST.SUBPROGRAM:SetupFCCOB
TEST.NEW
TEST.NAME:SwUFn_2108.006
TEST.NOTES:
REQ/FI
TEST.END_NOTES:
TEST.STUB:EEPROM.BackupSector
TEST.STUB:EEPROM.WriteBlock
TEST.STUB:EEPROM.EraseSectorInternal
TEST.STUB:EEPROM.WriteWord
TEST.STUB:EEPROM.EEPROM_SetByte
TEST.STUB:EEPROM.EEPROM_GetByte
TEST.STUB:EEPROM.EEPROM_Init
TEST.VALUE:<<OPTIONS>>.EVENT_LIMIT:10
TEST.VALUE:EEPROM.SetupFCCOB.PhraseAddr:0x100000000
TEST.VALUE:EEPROM.SetupFCCOB.From:0x10000
TEST.VALUE:EEPROM.SetupFCCOB.To:0x10000
TEST.VALUE:EEPROM.SetupFCCOB.Data:<<malloc 1>>
TEST.VALUE:EEPROM.SetupFCCOB.Data[0]:0x10000
TEST.VALUE:EEPROM.SetupFCCOB.pIndex:<<malloc 1>>
TEST.VALUE:EEPROM.SetupFCCOB.pIndex[0]:0x10000
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FCCOBIX.Byte:0x2
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FSTAT.Byte:48
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FCCOB0.Overlap_STR.FCCOB0HISTR.Byte:17
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FCCOB0.Overlap_STR.FCCOB0LOSTR.Byte:255
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FCCOB1.Word:65535
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FCCOB2.Word:0
TEST.EXPECTED:EEPROM.SetupFCCOB.pIndex[0]:0x2
TEST.EXPECTED:EEPROM.SetupFCCOB.return:0
TEST.END

-- Test Case: SwUFn_2108.007
TEST.UNIT:EEPROM
TEST.SUBPROGRAM:SetupFCCOB
TEST.NEW
TEST.NAME:SwUFn_2108.007
TEST.NOTES:
REQ/FI
TEST.END_NOTES:
TEST.STUB:EEPROM.BackupSector
TEST.STUB:EEPROM.WriteBlock
TEST.STUB:EEPROM.EraseSectorInternal
TEST.STUB:EEPROM.WriteWord
TEST.STUB:EEPROM.EEPROM_SetByte
TEST.STUB:EEPROM.EEPROM_GetByte
TEST.STUB:EEPROM.EEPROM_Init
TEST.VALUE:<<OPTIONS>>.EVENT_LIMIT:10
TEST.VALUE:EEPROM.SetupFCCOB.PhraseAddr:-1
TEST.VALUE:EEPROM.SetupFCCOB.From:-1
TEST.VALUE:EEPROM.SetupFCCOB.To:-1
TEST.VALUE:EEPROM.SetupFCCOB.Data:<<malloc 1>>
TEST.VALUE:EEPROM.SetupFCCOB.Data[0]:-1
TEST.VALUE:EEPROM.SetupFCCOB.pIndex:<<malloc 1>>
TEST.VALUE:EEPROM.SetupFCCOB.pIndex[0]:-1
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FCCOBIX.Byte:0x2
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FSTAT.Byte:48
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FCCOB0.Overlap_STR.FCCOB0HISTR.Byte:17
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FCCOB0.Overlap_STR.FCCOB0LOSTR.Byte:255
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FCCOB1.Word:65535
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FCCOB2.Word:0
TEST.EXPECTED:EEPROM.SetupFCCOB.pIndex[0]:0xFFFF
TEST.EXPECTED:EEPROM.SetupFCCOB.return:0
TEST.END

-- Test Case: SwUFn_2108.008
TEST.UNIT:EEPROM
TEST.SUBPROGRAM:SetupFCCOB
TEST.NEW
TEST.NAME:SwUFn_2108.008
TEST.NOTES:
REQ/FI
TEST.END_NOTES:
TEST.STUB:EEPROM.BackupSector
TEST.STUB:EEPROM.WriteBlock
TEST.STUB:EEPROM.EraseSectorInternal
TEST.STUB:EEPROM.WriteWord
TEST.STUB:EEPROM.EEPROM_SetByte
TEST.STUB:EEPROM.EEPROM_GetByte
TEST.STUB:EEPROM.EEPROM_Init
TEST.VALUE:<<OPTIONS>>.EVENT_LIMIT:10
TEST.VALUE:EEPROM.SetupFCCOB.PhraseAddr:0x141616874
TEST.VALUE:EEPROM.SetupFCCOB.From:0x16803
TEST.VALUE:EEPROM.SetupFCCOB.To:0x16803
TEST.VALUE:EEPROM.SetupFCCOB.Data:<<malloc 1>>
TEST.VALUE:EEPROM.SetupFCCOB.Data[0]:0x13846
TEST.VALUE:EEPROM.SetupFCCOB.pIndex:<<malloc 1>>
TEST.VALUE:EEPROM.SetupFCCOB.pIndex[0]:0x46406
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FCCOBIX.Byte:0x5
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FSTAT.Byte:48
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FCCOB0.Overlap_STR.FCCOB0HISTR.Byte:17
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FCCOB0.Overlap_STR.FCCOB0LOSTR.Byte:255
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FCCOB1.Word:65535
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FCCOB2.Word:0
TEST.EXPECTED:EEPROM.SetupFCCOB.pIndex[0]:0x640E
TEST.EXPECTED:EEPROM.SetupFCCOB.return:0
TEST.END

-- Test Case: SwUFn_2108.009
TEST.UNIT:EEPROM
TEST.SUBPROGRAM:SetupFCCOB
TEST.NEW
TEST.NAME:SwUFn_2108.009
TEST.NOTES:
REQ/FI
TEST.END_NOTES:
TEST.STUB:EEPROM.BackupSector
TEST.STUB:EEPROM.WriteBlock
TEST.STUB:EEPROM.EraseSectorInternal
TEST.STUB:EEPROM.WriteWord
TEST.STUB:EEPROM.EEPROM_SetByte
TEST.STUB:EEPROM.EEPROM_GetByte
TEST.STUB:EEPROM.EEPROM_Init
TEST.VALUE:<<OPTIONS>>.EVENT_LIMIT:10
TEST.VALUE:EEPROM.SetupFCCOB.PhraseAddr:0x13A4084C0
TEST.VALUE:EEPROM.SetupFCCOB.From:0xC1800
TEST.VALUE:EEPROM.SetupFCCOB.To:0x1680A
TEST.VALUE:EEPROM.SetupFCCOB.Data:<<malloc 1>>
TEST.VALUE:EEPROM.SetupFCCOB.Data[0]:0x6454C0
TEST.VALUE:EEPROM.SetupFCCOB.pIndex:<<malloc 1>>
TEST.VALUE:EEPROM.SetupFCCOB.pIndex[0]:0x84B3E
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FCCOBIX.Byte:0x5
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FSTAT.Byte:48
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FCCOB0.Overlap_STR.FCCOB0HISTR.Byte:17
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FCCOB0.Overlap_STR.FCCOB0LOSTR.Byte:255
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FCCOB1.Word:65535
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FCCOB2.Word:0
TEST.EXPECTED:EEPROM.SetupFCCOB.pIndex[0]:0x4B46
TEST.EXPECTED:EEPROM.SetupFCCOB.return:0
TEST.END

-- Subprogram: WriteBlock

-- Test Case: SwUFn_2105.001
TEST.UNIT:EEPROM
TEST.SUBPROGRAM:WriteBlock
TEST.NEW
TEST.NAME:SwUFn_2105.001
TEST.IMPORT_FAILURES:
(E) @LINE: 1634 TEST.VALUE:EEPROM.<<GLOBAL>>.REG_FSTAT.Bits.CCIF:-1
    >>> Unknown parameter/object name REG_FSTAT
    >>> Value Line Error - Command Ignored
(E) @LINE: 1635 TEST.VALUE:EEPROM.<<GLOBAL>>.REG_FSTAT.MergedBits.grpMGSTAT:-1
    >>> Unknown parameter/object name REG_FSTAT
    >>> Value Line Error - Command Ignored
(E) @LINE: 1636 TEST.EXPECTED:EEPROM.<<GLOBAL>>.REG_FCCOBIX.Byte:0
    >>> Unknown parameter/object name REG_FCCOBIX
    >>> Value Line Error - Command Ignored
(E) @LINE: 1637 TEST.EXPECTED:EEPROM.<<GLOBAL>>.REG_FSTAT.Byte:0x83
    >>> Unknown parameter/object name REG_FSTAT
    >>> Value Line Error - Command Ignored
(E) @LINE: 1638 TEST.EXPECTED:EEPROM.<<GLOBAL>>.REG_FCCOB0.Overlap_STR.FCCOB0HISTR.Byte:0
    >>> Unknown parameter/object name REG_FCCOB0
    >>> Value Line Error - Command Ignored
(E) @LINE: 1639 TEST.EXPECTED:EEPROM.<<GLOBAL>>.REG_FCCOB0.Overlap_STR.FCCOB0LOSTR.Byte:0
    >>> Unknown parameter/object name REG_FCCOB0
    >>> Value Line Error - Command Ignored
(E) @LINE: 1640 TEST.EXPECTED:EEPROM.<<GLOBAL>>.REG_FCCOB1.Word:0
    >>> Unknown parameter/object name REG_FCCOB1
    >>> Value Line Error - Command Ignored
(E) @LINE: 1641 TEST.EXPECTED:EEPROM.<<GLOBAL>>.REG_FCCOB2.Word:0
    >>> Unknown parameter/object name REG_FCCOB2
    >>> Value Line Error - Command Ignored
TEST.END_IMPORT_FAILURES:
TEST.NOTES:
REQ/BA
TEST.END_NOTES:
TEST.STUB:EEPROM.BackupSector
TEST.STUB:EEPROM.SetupFCCOB
TEST.STUB:EEPROM.EraseSectorInternal
TEST.STUB:EEPROM.WriteWord
TEST.STUB:EEPROM.EEPROM_SetByte
TEST.STUB:EEPROM.EEPROM_GetByte
TEST.STUB:EEPROM.EEPROM_Init
TEST.VALUE:EEPROM.<<GLOBAL>>._FSTAT.Byte:0
TEST.VALUE:EEPROM.<<GLOBAL>>._FSTAT.Bits.CCIF:0
TEST.VALUE:EEPROM.<<GLOBAL>>._FSTAT.MergedBits.grpMGSTAT:0
TEST.VALUE:EEPROM.WriteBlock.Addr:<<malloc 1>>
TEST.VALUE:EEPROM.WriteBlock.Addr[0]:0
TEST.VALUE:EEPROM.WriteBlock.From:0
TEST.VALUE:EEPROM.WriteBlock.To:0
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FSTAT.Byte:0
TEST.EXPECTED:EEPROM.WriteBlock.return:0
TEST.END


-- Test Case: SwUFn_2105.002
TEST.UNIT:EEPROM
TEST.SUBPROGRAM:WriteBlock
TEST.NEW
TEST.NAME:SwUFn_2105.002
TEST.IMPORT_FAILURES:
(E) @LINE: 1701 TEST.VALUE:EEPROM.<<GLOBAL>>.REG_FSTAT.Bits.CCIF:0
    >>> Unknown parameter/object name REG_FSTAT
    >>> Value Line Error - Command Ignored
(E) @LINE: 1702 TEST.VALUE:EEPROM.<<GLOBAL>>.REG_FSTAT.MergedBits.grpMGSTAT:0
    >>> Unknown parameter/object name REG_FSTAT
    >>> Value Line Error - Command Ignored
(E) @LINE: 1703 TEST.EXPECTED:EEPROM.<<GLOBAL>>.REG_FCCOBIX.Byte:0
    >>> Unknown parameter/object name REG_FCCOBIX
    >>> Value Line Error - Command Ignored
(E) @LINE: 1704 TEST.EXPECTED:EEPROM.<<GLOBAL>>.REG_FSTAT.Byte:0x0
    >>> Unknown parameter/object name REG_FSTAT
    >>> Value Line Error - Command Ignored
(E) @LINE: 1705 TEST.EXPECTED:EEPROM.<<GLOBAL>>.REG_FCCOB0.Overlap_STR.FCCOB0HISTR.Byte:0
    >>> Unknown parameter/object name REG_FCCOB0
    >>> Value Line Error - Command Ignored
(E) @LINE: 1706 TEST.EXPECTED:EEPROM.<<GLOBAL>>.REG_FCCOB0.Overlap_STR.FCCOB0LOSTR.Byte:0
    >>> Unknown parameter/object name REG_FCCOB0
    >>> Value Line Error - Command Ignored
(E) @LINE: 1707 TEST.EXPECTED:EEPROM.<<GLOBAL>>.REG_FCCOB1.Word:0
    >>> Unknown parameter/object name REG_FCCOB1
    >>> Value Line Error - Command Ignored
(E) @LINE: 1708 TEST.EXPECTED:EEPROM.<<GLOBAL>>.REG_FCCOB2.Word:0
    >>> Unknown parameter/object name REG_FCCOB2
    >>> Value Line Error - Command Ignored
TEST.END_IMPORT_FAILURES:
TEST.NOTES:
REQ/BA
TEST.END_NOTES:
TEST.STUB:EEPROM.BackupSector
TEST.STUB:EEPROM.SetupFCCOB
TEST.STUB:EEPROM.EraseSectorInternal
TEST.STUB:EEPROM.WriteWord
TEST.STUB:EEPROM.EEPROM_SetByte
TEST.STUB:EEPROM.EEPROM_GetByte
TEST.STUB:EEPROM.EEPROM_Init
TEST.VALUE:EEPROM.<<GLOBAL>>._FSTAT.Byte:127
TEST.VALUE:EEPROM.<<GLOBAL>>._FSTAT.Bits.CCIF:0
TEST.VALUE:EEPROM.<<GLOBAL>>._FSTAT.MergedBits.grpMGSTAT:1
TEST.VALUE:EEPROM.WriteBlock.Addr:<<malloc 1>>
TEST.VALUE:EEPROM.WriteBlock.Addr[0]:2147483647
TEST.VALUE:EEPROM.WriteBlock.From:32767
TEST.VALUE:EEPROM.WriteBlock.To:32767
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FSTAT.Byte:125
TEST.EXPECTED:EEPROM.WriteBlock.return:0
TEST.END


-- Test Case: SwUFn_2105.003
TEST.UNIT:EEPROM
TEST.SUBPROGRAM:WriteBlock
TEST.NEW
TEST.NAME:SwUFn_2105.003
TEST.IMPORT_FAILURES:
(E) @LINE: 1768 TEST.VALUE:EEPROM.<<GLOBAL>>.REG_FSTAT.Bits.CCIF:1
    >>> Unknown parameter/object name REG_FSTAT
    >>> Value Line Error - Command Ignored
(E) @LINE: 1769 TEST.VALUE:EEPROM.<<GLOBAL>>.REG_FSTAT.MergedBits.grpMGSTAT:1
    >>> Unknown parameter/object name REG_FSTAT
    >>> Value Line Error - Command Ignored
(E) @LINE: 1770 TEST.EXPECTED:EEPROM.<<GLOBAL>>.REG_FCCOBIX.Byte:0
    >>> Unknown parameter/object name REG_FCCOBIX
    >>> Value Line Error - Command Ignored
(E) @LINE: 1771 TEST.EXPECTED:EEPROM.<<GLOBAL>>.REG_FSTAT.Byte:0x81
    >>> Unknown parameter/object name REG_FSTAT
    >>> Value Line Error - Command Ignored
(E) @LINE: 1772 TEST.EXPECTED:EEPROM.<<GLOBAL>>.REG_FCCOB0.Overlap_STR.FCCOB0HISTR.Byte:0
    >>> Unknown parameter/object name REG_FCCOB0
    >>> Value Line Error - Command Ignored
(E) @LINE: 1773 TEST.EXPECTED:EEPROM.<<GLOBAL>>.REG_FCCOB0.Overlap_STR.FCCOB0LOSTR.Byte:0
    >>> Unknown parameter/object name REG_FCCOB0
    >>> Value Line Error - Command Ignored
(E) @LINE: 1774 TEST.EXPECTED:EEPROM.<<GLOBAL>>.REG_FCCOB1.Word:0
    >>> Unknown parameter/object name REG_FCCOB1
    >>> Value Line Error - Command Ignored
(E) @LINE: 1775 TEST.EXPECTED:EEPROM.<<GLOBAL>>.REG_FCCOB2.Word:0
    >>> Unknown parameter/object name REG_FCCOB2
    >>> Value Line Error - Command Ignored
TEST.END_IMPORT_FAILURES:
TEST.NOTES:
REQ/BA
TEST.END_NOTES:
TEST.STUB:EEPROM.BackupSector
TEST.STUB:EEPROM.SetupFCCOB
TEST.STUB:EEPROM.EraseSectorInternal
TEST.STUB:EEPROM.WriteWord
TEST.STUB:EEPROM.EEPROM_SetByte
TEST.STUB:EEPROM.EEPROM_GetByte
TEST.STUB:EEPROM.EEPROM_Init
TEST.VALUE:EEPROM.<<GLOBAL>>._FSTAT.Byte:255
TEST.VALUE:EEPROM.<<GLOBAL>>._FSTAT.Bits.CCIF:1
TEST.VALUE:EEPROM.<<GLOBAL>>._FSTAT.MergedBits.grpMGSTAT:3
TEST.VALUE:EEPROM.WriteBlock.Addr:<<malloc 1>>
TEST.VALUE:EEPROM.WriteBlock.Addr[0]:4294967295
TEST.VALUE:EEPROM.WriteBlock.From:65535
TEST.VALUE:EEPROM.WriteBlock.To:65535
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FSTAT.Byte:255
TEST.EXPECTED:EEPROM.WriteBlock.return:0
TEST.END


-- Test Case: SwUFn_2105.004
TEST.UNIT:EEPROM
TEST.SUBPROGRAM:WriteBlock
TEST.NEW
TEST.NAME:SwUFn_2105.004
TEST.IMPORT_FAILURES:
(E) @LINE: 1836 TEST.VALUE:EEPROM.<<GLOBAL>>.REG_FSTAT.Bits.CCIF:1
    >>> Unknown parameter/object name REG_FSTAT
    >>> Value Line Error - Command Ignored
(E) @LINE: 1837 TEST.VALUE:EEPROM.<<GLOBAL>>.REG_FSTAT.MergedBits.grpMGSTAT:3
    >>> Unknown parameter/object name REG_FSTAT
    >>> Value Line Error - Command Ignored
(E) @LINE: 1838 TEST.EXPECTED:EEPROM.<<GLOBAL>>.REG_FCCOBIX.Byte:0
    >>> Unknown parameter/object name REG_FCCOBIX
    >>> Value Line Error - Command Ignored
(E) @LINE: 1839 TEST.EXPECTED:EEPROM.<<GLOBAL>>.REG_FSTAT.Byte:0x83
    >>> Unknown parameter/object name REG_FSTAT
    >>> Value Line Error - Command Ignored
(E) @LINE: 1840 TEST.EXPECTED:EEPROM.<<GLOBAL>>.REG_FCCOB0.Overlap_STR.FCCOB0HISTR.Byte:0x0
    >>> Unknown parameter/object name REG_FCCOB0
    >>> Value Line Error - Command Ignored
(E) @LINE: 1841 TEST.EXPECTED:EEPROM.<<GLOBAL>>.REG_FCCOB0.Overlap_STR.FCCOB0LOSTR.Byte:0
    >>> Unknown parameter/object name REG_FCCOB0
    >>> Value Line Error - Command Ignored
(E) @LINE: 1842 TEST.EXPECTED:EEPROM.<<GLOBAL>>.REG_FCCOB1.Word:0
    >>> Unknown parameter/object name REG_FCCOB1
    >>> Value Line Error - Command Ignored
(E) @LINE: 1843 TEST.EXPECTED:EEPROM.<<GLOBAL>>.REG_FCCOB2.Word:0
    >>> Unknown parameter/object name REG_FCCOB2
    >>> Value Line Error - Command Ignored
TEST.END_IMPORT_FAILURES:
TEST.NOTES:
REQ/FI

TEST.END_NOTES:
TEST.STUB:EEPROM.BackupSector
TEST.STUB:EEPROM.SetupFCCOB
TEST.STUB:EEPROM.EraseSectorInternal
TEST.STUB:EEPROM.WriteWord
TEST.STUB:EEPROM.EEPROM_SetByte
TEST.STUB:EEPROM.EEPROM_GetByte
TEST.STUB:EEPROM.EEPROM_Init
TEST.VALUE:EEPROM.<<GLOBAL>>._FSTAT.Byte:-1
TEST.VALUE:EEPROM.<<GLOBAL>>._FSTAT.Bits.CCIF:-1
TEST.VALUE:EEPROM.<<GLOBAL>>._FSTAT.MergedBits.grpMGSTAT:-1
TEST.VALUE:EEPROM.WriteBlock.Addr:<<malloc 1>>
TEST.VALUE:EEPROM.WriteBlock.Addr[0]:-1
TEST.VALUE:EEPROM.WriteBlock.From:-1
TEST.VALUE:EEPROM.WriteBlock.To:-1
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FSTAT.Byte:255
TEST.EXPECTED:EEPROM.WriteBlock.return:0
TEST.END


-- Test Case: SwUFn_2105.005
TEST.UNIT:EEPROM
TEST.SUBPROGRAM:WriteBlock
TEST.NEW
TEST.NAME:SwUFn_2105.005
TEST.IMPORT_FAILURES:
(E) @LINE: 1904 TEST.VALUE:EEPROM.<<GLOBAL>>.REG_FSTAT.Bits.CCIF:2
    >>> Unknown parameter/object name REG_FSTAT
    >>> Value Line Error - Command Ignored
(E) @LINE: 1905 TEST.VALUE:EEPROM.<<GLOBAL>>.REG_FSTAT.MergedBits.grpMGSTAT:4
    >>> Unknown parameter/object name REG_FSTAT
    >>> Value Line Error - Command Ignored
(E) @LINE: 1906 TEST.EXPECTED:EEPROM.<<GLOBAL>>.REG_FCCOBIX.Byte:0
    >>> Unknown parameter/object name REG_FCCOBIX
    >>> Value Line Error - Command Ignored
(E) @LINE: 1907 TEST.EXPECTED:EEPROM.<<GLOBAL>>.REG_FSTAT.Byte:0x0
    >>> Unknown parameter/object name REG_FSTAT
    >>> Value Line Error - Command Ignored
(E) @LINE: 1908 TEST.EXPECTED:EEPROM.<<GLOBAL>>.REG_FCCOB0.Overlap_STR.FCCOB0HISTR.Byte:0x0
    >>> Unknown parameter/object name REG_FCCOB0
    >>> Value Line Error - Command Ignored
(E) @LINE: 1909 TEST.EXPECTED:EEPROM.<<GLOBAL>>.REG_FCCOB0.Overlap_STR.FCCOB0LOSTR.Byte:0
    >>> Unknown parameter/object name REG_FCCOB0
    >>> Value Line Error - Command Ignored
(E) @LINE: 1910 TEST.EXPECTED:EEPROM.<<GLOBAL>>.REG_FCCOB1.Word:0
    >>> Unknown parameter/object name REG_FCCOB1
    >>> Value Line Error - Command Ignored
(E) @LINE: 1911 TEST.EXPECTED:EEPROM.<<GLOBAL>>.REG_FCCOB2.Word:0
    >>> Unknown parameter/object name REG_FCCOB2
    >>> Value Line Error - Command Ignored
TEST.END_IMPORT_FAILURES:
TEST.NOTES:
REQ/FI

TEST.END_NOTES:
TEST.STUB:EEPROM.BackupSector
TEST.STUB:EEPROM.SetupFCCOB
TEST.STUB:EEPROM.EraseSectorInternal
TEST.STUB:EEPROM.WriteWord
TEST.STUB:EEPROM.EEPROM_SetByte
TEST.STUB:EEPROM.EEPROM_GetByte
TEST.STUB:EEPROM.EEPROM_Init
TEST.VALUE:EEPROM.<<GLOBAL>>._FSTAT.Byte:256
TEST.VALUE:EEPROM.<<GLOBAL>>._FSTAT.Bits.CCIF:2
TEST.VALUE:EEPROM.<<GLOBAL>>._FSTAT.MergedBits.grpMGSTAT:4
TEST.VALUE:EEPROM.WriteBlock.Addr:<<malloc 1>>
TEST.VALUE:EEPROM.WriteBlock.Addr[0]:4294967296
TEST.VALUE:EEPROM.WriteBlock.From:65536
TEST.VALUE:EEPROM.WriteBlock.To:65536
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FSTAT.Byte:0
TEST.EXPECTED:EEPROM.WriteBlock.return:0
TEST.END

-- Test Case: SwUFn_2105.006
TEST.UNIT:EEPROM
TEST.SUBPROGRAM:WriteBlock
TEST.NEW
TEST.NAME:SwUFn_2105.006
TEST.IMPORT_FAILURES:
(E) @LINE: 1972 TEST.VALUE:EEPROM.<<GLOBAL>>.REG_FSTAT.Bits.CCIF:0
    >>> Unknown parameter/object name REG_FSTAT
    >>> Value Line Error - Command Ignored
(E) @LINE: 1973 TEST.VALUE:EEPROM.<<GLOBAL>>.REG_FSTAT.MergedBits.grpMGSTAT:0
    >>> Unknown parameter/object name REG_FSTAT
    >>> Value Line Error - Command Ignored
(E) @LINE: 1974 TEST.EXPECTED:EEPROM.<<GLOBAL>>.REG_FCCOBIX.Byte:2
    >>> Unknown parameter/object name REG_FCCOBIX
    >>> Value Line Error - Command Ignored
(E) @LINE: 1975 TEST.EXPECTED:EEPROM.<<GLOBAL>>.REG_FSTAT.Byte:0x80
    >>> Unknown parameter/object name REG_FSTAT
    >>> Value Line Error - Command Ignored
(E) @LINE: 1976 TEST.EXPECTED:EEPROM.<<GLOBAL>>.REG_FCCOB0.Overlap_STR.FCCOB0HISTR.Byte:17
    >>> Unknown parameter/object name REG_FCCOB0
    >>> Value Line Error - Command Ignored
(E) @LINE: 1977 TEST.EXPECTED:EEPROM.<<GLOBAL>>.REG_FCCOB0.Overlap_STR.FCCOB0LOSTR.Byte:0
    >>> Unknown parameter/object name REG_FCCOB0
    >>> Value Line Error - Command Ignored
(E) @LINE: 1978 TEST.EXPECTED:EEPROM.<<GLOBAL>>.REG_FCCOB1.Word:10437
    >>> Unknown parameter/object name REG_FCCOB1
    >>> Value Line Error - Command Ignored
(E) @LINE: 1979 TEST.EXPECTED:EEPROM.<<GLOBAL>>.REG_FCCOB2.Word:0
    >>> Unknown parameter/object name REG_FCCOB2
    >>> Value Line Error - Command Ignored
TEST.END_IMPORT_FAILURES:
TEST.NOTES:
REQ/FI

TEST.END_NOTES:
TEST.STUB:EEPROM.BackupSector
TEST.STUB:EEPROM.SetupFCCOB
TEST.STUB:EEPROM.EraseSectorInternal
TEST.STUB:EEPROM.WriteWord
TEST.STUB:EEPROM.EEPROM_SetByte
TEST.STUB:EEPROM.EEPROM_GetByte
TEST.STUB:EEPROM.EEPROM_Init
TEST.VALUE:EEPROM.<<GLOBAL>>._FSTAT.Byte:345
TEST.VALUE:EEPROM.<<GLOBAL>>._FSTAT.Bits.CCIF:10
TEST.VALUE:EEPROM.<<GLOBAL>>._FSTAT.MergedBits.grpMGSTAT:15
TEST.VALUE:EEPROM.WriteBlock.Addr:<<malloc 1>>
TEST.VALUE:EEPROM.WriteBlock.Addr[0]:5781426894
TEST.VALUE:EEPROM.WriteBlock.From:75426
TEST.VALUE:EEPROM.WriteBlock.To:75426
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FSTAT.Byte:91
TEST.EXPECTED:EEPROM.WriteBlock.return:0
TEST.END


-- Test Case: SwUFn_2105.007
TEST.UNIT:EEPROM
TEST.SUBPROGRAM:WriteBlock
TEST.NEW
TEST.NAME:SwUFn_2105.007
TEST.IMPORT_FAILURES:
(E) @LINE: 2040 TEST.VALUE:EEPROM.<<GLOBAL>>.REG_FSTAT.Bits.CCIF:0
    >>> Unknown parameter/object name REG_FSTAT
    >>> Value Line Error - Command Ignored
(E) @LINE: 2041 TEST.VALUE:EEPROM.<<GLOBAL>>.REG_FSTAT.MergedBits.grpMGSTAT:1
    >>> Unknown parameter/object name REG_FSTAT
    >>> Value Line Error - Command Ignored
(E) @LINE: 2042 TEST.EXPECTED:EEPROM.<<GLOBAL>>.REG_FCCOBIX.Byte:2
    >>> Unknown parameter/object name REG_FCCOBIX
    >>> Value Line Error - Command Ignored
(E) @LINE: 2043 TEST.EXPECTED:EEPROM.<<GLOBAL>>.REG_FSTAT.Byte:0x80
    >>> Unknown parameter/object name REG_FSTAT
    >>> Value Line Error - Command Ignored
(E) @LINE: 2044 TEST.EXPECTED:EEPROM.<<GLOBAL>>.REG_FCCOB0.Overlap_STR.FCCOB0HISTR.Byte:17
    >>> Unknown parameter/object name REG_FCCOB0
    >>> Value Line Error - Command Ignored
(E) @LINE: 2045 TEST.EXPECTED:EEPROM.<<GLOBAL>>.REG_FCCOB0.Overlap_STR.FCCOB0LOSTR.Byte:0
    >>> Unknown parameter/object name REG_FCCOB0
    >>> Value Line Error - Command Ignored
(E) @LINE: 2046 TEST.EXPECTED:EEPROM.<<GLOBAL>>.REG_FCCOB1.Word:10446
    >>> Unknown parameter/object name REG_FCCOB1
    >>> Value Line Error - Command Ignored
(E) @LINE: 2047 TEST.EXPECTED:EEPROM.<<GLOBAL>>.REG_FCCOB2.Word:256
    >>> Unknown parameter/object name REG_FCCOB2
    >>> Value Line Error - Command Ignored
TEST.END_IMPORT_FAILURES:
TEST.NOTES:
REQ/FI

TEST.END_NOTES:
TEST.STUB:EEPROM.BackupSector
TEST.STUB:EEPROM.SetupFCCOB
TEST.STUB:EEPROM.EraseSectorInternal
TEST.STUB:EEPROM.WriteWord
TEST.STUB:EEPROM.EEPROM_SetByte
TEST.STUB:EEPROM.EEPROM_GetByte
TEST.STUB:EEPROM.EEPROM_Init
TEST.VALUE:EEPROM.<<GLOBAL>>._FSTAT.Byte:400
TEST.VALUE:EEPROM.<<GLOBAL>>._FSTAT.Bits.CCIF:180
TEST.VALUE:EEPROM.<<GLOBAL>>._FSTAT.MergedBits.grpMGSTAT:152
TEST.VALUE:EEPROM.WriteBlock.Addr:<<malloc 1>>
TEST.VALUE:EEPROM.WriteBlock.Addr[0]:5000000000
TEST.VALUE:EEPROM.WriteBlock.From:70000
TEST.VALUE:EEPROM.WriteBlock.To:70000
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FSTAT.Byte:16
TEST.EXPECTED:EEPROM.WriteBlock.return:0
TEST.END

-- Test Case: SwUFn_2105.008
TEST.UNIT:EEPROM
TEST.SUBPROGRAM:WriteBlock
TEST.NEW
TEST.NAME:SwUFn_2105.008
TEST.NOTES:
REQ/EC
TEST.END_NOTES:
TEST.STUB:EEPROM.BackupSector
TEST.STUB:EEPROM.SetupFCCOB
TEST.STUB:EEPROM.EraseSectorInternal
TEST.STUB:EEPROM.WriteWord
TEST.STUB:EEPROM.EEPROM_SetByte
TEST.STUB:EEPROM.EEPROM_GetByte
TEST.STUB:EEPROM.EEPROM_Init
TEST.VALUE:EEPROM.<<GLOBAL>>._FSTAT.Byte:127
TEST.VALUE:EEPROM.<<GLOBAL>>._FSTAT.Bits.CCIF:1
TEST.VALUE:EEPROM.<<GLOBAL>>._FSTAT.MergedBits.grpMGSTAT:1
TEST.VALUE:EEPROM.WriteBlock.Addr:<<malloc 1>>
TEST.VALUE:EEPROM.WriteBlock.Addr[0]:2147483647
TEST.VALUE:EEPROM.WriteBlock.From:1
TEST.VALUE:EEPROM.WriteBlock.To:2
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FSTAT.Byte:128
TEST.EXPECTED:EEPROM.WriteBlock.return:0
TEST.STUB_VAL_USER_CODE:EEPROM.SetupFCCOB.pIndex
word *temp = <<EEPROM.SetupFCCOB.pIndex>>;
*temp = 3;
TEST.END_STUB_VAL_USER_CODE:
TEST.END

-- Subprogram: WriteWord

-- Test Case: SwUFn_2106.001
TEST.UNIT:EEPROM
TEST.SUBPROGRAM:WriteWord
TEST.NEW
TEST.NAME:SwUFn_2106.001
TEST.NOTES:
REQ/BA
TEST.END_NOTES:
TEST.STUB:EEPROM.BackupSector
TEST.STUB:EEPROM.WriteBlock
TEST.STUB:EEPROM.SetupFCCOB
TEST.STUB:EEPROM.EraseSectorInternal
TEST.STUB:EEPROM.EEPROM_SetByte
TEST.STUB:EEPROM.EEPROM_GetByte
TEST.STUB:EEPROM.EEPROM_Init
TEST.VALUE:EEPROM.<<GLOBAL>>._FSTAT.Byte:0
TEST.VALUE:EEPROM.<<GLOBAL>>._FSTAT.Bits.CCIF:0
TEST.VALUE:EEPROM.<<GLOBAL>>._FSTAT.MergedBits.grpMGSTAT:0
TEST.VALUE:EEPROM.WriteWord.AddrRow:<<malloc 1>>
TEST.VALUE:EEPROM.WriteWord.AddrRow[0]:0
TEST.VALUE:EEPROM.WriteWord.Data16:0
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FCCOBIX.Byte:0
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FSTAT.Byte:0
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FCCOB0.Overlap_STR.FCCOB0HISTR.Byte:0
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FCCOB0.Overlap_STR.FCCOB0LOSTR.Byte:0
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FCCOB1.Word:0
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FCCOB2.Word:0
TEST.EXPECTED:EEPROM.WriteWord.return:8
TEST.END

-- Test Case: SwUFn_2106.002
TEST.UNIT:EEPROM
TEST.SUBPROGRAM:WriteWord
TEST.NEW
TEST.NAME:SwUFn_2106.002
TEST.NOTES:
REQ/BA
TEST.END_NOTES:
TEST.STUB:EEPROM.BackupSector
TEST.STUB:EEPROM.WriteBlock
TEST.STUB:EEPROM.SetupFCCOB
TEST.STUB:EEPROM.EraseSectorInternal
TEST.STUB:EEPROM.EEPROM_SetByte
TEST.STUB:EEPROM.EEPROM_GetByte
TEST.STUB:EEPROM.EEPROM_Init
TEST.VALUE:EEPROM.<<GLOBAL>>._FSTAT.Byte:127
TEST.VALUE:EEPROM.<<GLOBAL>>._FSTAT.Bits.CCIF:0
TEST.VALUE:EEPROM.<<GLOBAL>>._FSTAT.MergedBits.grpMGSTAT:1
TEST.VALUE:EEPROM.WriteWord.AddrRow:<<malloc 1>>
TEST.VALUE:EEPROM.WriteWord.AddrRow[0]:2147483647
TEST.VALUE:EEPROM.WriteWord.Data16:32767
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FCCOBIX.Byte:0
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FSTAT.Byte:125
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FCCOB0.Overlap_STR.FCCOB0HISTR.Byte:0
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FCCOB0.Overlap_STR.FCCOB0LOSTR.Byte:0
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FCCOB1.Word:0
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FCCOB2.Word:0
TEST.EXPECTED:EEPROM.WriteWord.return:8
TEST.END

-- Test Case: SwUFn_2106.003
TEST.UNIT:EEPROM
TEST.SUBPROGRAM:WriteWord
TEST.NEW
TEST.NAME:SwUFn_2106.003
TEST.NOTES:
REQ/BA
TEST.END_NOTES:
TEST.STUB:EEPROM.BackupSector
TEST.STUB:EEPROM.WriteBlock
TEST.STUB:EEPROM.SetupFCCOB
TEST.STUB:EEPROM.EraseSectorInternal
TEST.STUB:EEPROM.EEPROM_SetByte
TEST.STUB:EEPROM.EEPROM_GetByte
TEST.STUB:EEPROM.EEPROM_Init
TEST.VALUE:EEPROM.<<GLOBAL>>._FSTAT.Byte:255
TEST.VALUE:EEPROM.<<GLOBAL>>._FSTAT.Bits.CCIF:1
TEST.VALUE:EEPROM.<<GLOBAL>>._FSTAT.MergedBits.grpMGSTAT:3
TEST.VALUE:EEPROM.WriteWord.AddrRow:<<malloc 1>>
TEST.VALUE:EEPROM.WriteWord.AddrRow[0]:4294967295
TEST.VALUE:EEPROM.WriteWord.Data16:65535
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FCCOBIX.Byte:2
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FSTAT.Byte:128
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FCCOB0.Overlap_STR.FCCOB0HISTR.Byte:17
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FCCOB0.Overlap_STR.FCCOB0LOSTR.Byte:0
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FCCOB1.Word:7348
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FCCOB2.Word:65535
TEST.EXPECTED:EEPROM.WriteWord.return:0
TEST.END

-- Test Case: SwUFn_2106.004
TEST.UNIT:EEPROM
TEST.SUBPROGRAM:WriteWord
TEST.NEW
TEST.NAME:SwUFn_2106.004
TEST.NOTES:
REQ/FI
TEST.END_NOTES:
TEST.STUB:EEPROM.BackupSector
TEST.STUB:EEPROM.WriteBlock
TEST.STUB:EEPROM.SetupFCCOB
TEST.STUB:EEPROM.EraseSectorInternal
TEST.STUB:EEPROM.EEPROM_SetByte
TEST.STUB:EEPROM.EEPROM_GetByte
TEST.STUB:EEPROM.EEPROM_Init
TEST.VALUE:EEPROM.<<GLOBAL>>._FSTAT.Byte:-1
TEST.VALUE:EEPROM.<<GLOBAL>>._FSTAT.Bits.CCIF:-1
TEST.VALUE:EEPROM.<<GLOBAL>>._FSTAT.MergedBits.grpMGSTAT:-1
TEST.VALUE:EEPROM.WriteWord.AddrRow:<<malloc 1>>
TEST.VALUE:EEPROM.WriteWord.AddrRow[0]:-1
TEST.VALUE:EEPROM.WriteWord.Data16:-1
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FCCOBIX.Byte:2
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FSTAT.Byte:128
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FCCOB0.Overlap_STR.FCCOB0HISTR.Byte:17
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FCCOB0.Overlap_STR.FCCOB0LOSTR.Byte:0
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FCCOB1.Word:7340
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FCCOB2.Word:65535
TEST.EXPECTED:EEPROM.WriteWord.return:0
TEST.END

-- Test Case: SwUFn_2106.005
TEST.UNIT:EEPROM
TEST.SUBPROGRAM:WriteWord
TEST.NEW
TEST.NAME:SwUFn_2106.005
TEST.NOTES:
REQ/FI
TEST.END_NOTES:
TEST.STUB:EEPROM.BackupSector
TEST.STUB:EEPROM.WriteBlock
TEST.STUB:EEPROM.SetupFCCOB
TEST.STUB:EEPROM.EraseSectorInternal
TEST.STUB:EEPROM.EEPROM_SetByte
TEST.STUB:EEPROM.EEPROM_GetByte
TEST.STUB:EEPROM.EEPROM_Init
TEST.VALUE:EEPROM.<<GLOBAL>>._FSTAT.Byte:256
TEST.VALUE:EEPROM.<<GLOBAL>>._FSTAT.Bits.CCIF:2
TEST.VALUE:EEPROM.<<GLOBAL>>._FSTAT.MergedBits.grpMGSTAT:4
TEST.VALUE:EEPROM.WriteWord.AddrRow:<<malloc 1>>
TEST.VALUE:EEPROM.WriteWord.AddrRow[0]:4294967296
TEST.VALUE:EEPROM.WriteWord.Data16:65536
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FCCOBIX.Byte:0
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FSTAT.Byte:0
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FCCOB0.Overlap_STR.FCCOB0HISTR.Byte:0
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FCCOB0.Overlap_STR.FCCOB0LOSTR.Byte:0
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FCCOB1.Word:0
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FCCOB2.Word:0
TEST.EXPECTED:EEPROM.WriteWord.return:8
TEST.END

-- Test Case: SwUFn_2106.006
TEST.UNIT:EEPROM
TEST.SUBPROGRAM:WriteWord
TEST.NEW
TEST.NAME:SwUFn_2106.006
TEST.NOTES:
REQ/FI
TEST.END_NOTES:
TEST.STUB:EEPROM.BackupSector
TEST.STUB:EEPROM.WriteBlock
TEST.STUB:EEPROM.SetupFCCOB
TEST.STUB:EEPROM.EraseSectorInternal
TEST.STUB:EEPROM.EEPROM_SetByte
TEST.STUB:EEPROM.EEPROM_GetByte
TEST.STUB:EEPROM.EEPROM_Init
TEST.VALUE:EEPROM.<<GLOBAL>>._FSTAT.Byte:340
TEST.VALUE:EEPROM.<<GLOBAL>>._FSTAT.Bits.CCIF:100
TEST.VALUE:EEPROM.<<GLOBAL>>._FSTAT.MergedBits.grpMGSTAT:150
TEST.VALUE:EEPROM.WriteWord.AddrRow:<<malloc 1>>
TEST.VALUE:EEPROM.WriteWord.AddrRow[0]:5201478035
TEST.VALUE:EEPROM.WriteWord.Data16:72503
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FCCOBIX.Byte:0
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FSTAT.Byte:86
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FCCOB0.Overlap_STR.FCCOB0HISTR.Byte:0
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FCCOB0.Overlap_STR.FCCOB0LOSTR.Byte:0
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FCCOB1.Word:0
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FCCOB2.Word:0
TEST.EXPECTED:EEPROM.WriteWord.return:8
TEST.END

-- Test Case: SwUFn_2106.007
TEST.UNIT:EEPROM
TEST.SUBPROGRAM:WriteWord
TEST.NEW
TEST.NAME:SwUFn_2106.007
TEST.NOTES:
REQ/FI
TEST.END_NOTES:
TEST.STUB:EEPROM.BackupSector
TEST.STUB:EEPROM.WriteBlock
TEST.STUB:EEPROM.SetupFCCOB
TEST.STUB:EEPROM.EraseSectorInternal
TEST.STUB:EEPROM.EEPROM_SetByte
TEST.STUB:EEPROM.EEPROM_GetByte
TEST.STUB:EEPROM.EEPROM_Init
TEST.VALUE:EEPROM.<<GLOBAL>>._FSTAT.Byte:312
TEST.VALUE:EEPROM.<<GLOBAL>>._FSTAT.Bits.CCIF:99
TEST.VALUE:EEPROM.<<GLOBAL>>._FSTAT.MergedBits.grpMGSTAT:99
TEST.VALUE:EEPROM.WriteWord.AddrRow:<<malloc 1>>
TEST.VALUE:EEPROM.WriteWord.AddrRow[0]:5001472305
TEST.VALUE:EEPROM.WriteWord.Data16:70065
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FCCOBIX.Byte:2
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FSTAT.Byte:128
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FCCOB0.Overlap_STR.FCCOB0HISTR.Byte:17
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FCCOB0.Overlap_STR.FCCOB0LOSTR.Byte:0
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FCCOB1.Word:7352
TEST.EXPECTED:EEPROM.<<GLOBAL>>._FCCOB2.Word:4529
TEST.EXPECTED:EEPROM.WriteWord.return:0
TEST.END
