"""Backward-compatible re-export of all helper functions.

All routers import from ``backend.helpers``, which now delegates to
domain-specific submodules for better organization.
"""
# --- common ---
from backend.helpers.common import (  # noqa: F401
    SETTINGS_FILE,
    _api_logger,
    _build_excel_artifact_payload,
    _build_excel_artifact_summary,
    _compact_symbol_simple,
    _extract_param_name_simple,
    _get_progress,
    _has_meaningful_value,
    _has_trace_token,
    _infer_related_id_simple,
    _is_allowed_req_doc,
    _is_relative_to,
    _is_trusted_source_for_field,
    _mtime_or_zero,
    _normalize_asil_simple,
    _normalize_field_source,
    _normalize_symbol_simple,
    _parse_component_map_file,
    _parse_path_list,
    _parse_signature_outputs_simple,
    _parse_signature_params_simple,
    _progress_key,
    _read_json,
    _read_excel_artifact_sidecar,
    _run_report_with_timeout,
    _safe_extract_zip,
    _safe_int,
    _set_progress,
    _split_csv,
    _split_signature_params,
    _write_json,
    _write_excel_artifact_sidecar,
    _write_upload_to_temp,
    repo_root,
)

# --- uds ---
from backend.helpers.uds import (  # noqa: F401
    _apply_uds_view_filters,
    _build_quality_action_hints,
    _build_quality_evaluation,
    _build_test_cases_for_signature,
    _compute_uds_mapping_summary,
    _compute_quick_quality_gate,
    _write_residual_tbd_report,
    _derive_quality_reason_codes,
    _enrich_function_quality_fields,
    _extract_call_graph_payload,
    _extract_dependency_map_payload,
    _generate_docx_with_retry,
    _get_source_sections_cached,
    _get_uds_view_payload_cached,
    _parse_accuracy_report,
    _parse_quality_gate_report,
    _parse_signature_params,
    _run_impact_analysis_for_uds,
    _slice_page,
    _to_swcom_from_fn,
    _uds_generate_from_paths,
    _validate_docx_template_bytes,
)

# --- jenkins ---
from backend.helpers.jenkins import (  # noqa: F401
    _create_jenkins_zip_file,
    _jenkins_exports_dir,
    _jenkins_logic_dir,
    _jenkins_report_publish_impl,
    _jenkins_sts_dir,
    _jenkins_suts_dir,
    _jenkins_templates_dir,
    _load_uds_meta,
    _matches_filters,
    _normalize_filter_tokens,
    _normalize_jenkins_cache_root,
    _resolve_cached_build_root,
    _save_uds_meta,
    _uds_meta_path,
)

# --- session ---
from backend.helpers.session import (  # noqa: F401
    _augment_path,
    _build_preflight,
    _collect_tool_paths,
    _create_zip_file,
    _default_base_report_dir,
    _exports_dir,
    _invalidate_session_cache,
    _load_raw_profiles,
    _load_session_meta,
    _load_vectorcast_rag,
    _local_reports_dir,
    _local_sits_dir,
    _local_sts_dir,
    _local_suts_dir,
    _local_uds_dir,
    _normalize_profile,
    _open_local_path,
    _resolve_base_dir,
    _resolve_export_path,
    _resolve_local_report_path,
    _resolve_local_sits_path,
    _resolve_local_sts_path,
    _resolve_local_suts_path,
    _resolve_local_uds_path,
    _resolve_report_dir,
    _resolve_source_root_from_cfg,
    _save_raw_profiles,
    _save_session_meta,
    _session_dir,
    _session_meta_path,
    _track_process,
)

# --- vectorcast ---
from backend.helpers.vectorcast import (  # noqa: F401
    VECTORCAST_CONFIG_DIR,
    build_vectorcast_metadata,
    evaluate_vectorcast_readiness,
    load_vectorcast_project_config,
)
