typedef int VECTORCAST_MARKER__UNIT_APPENDIX_END;
typedef int VECTORCAST_MARKER__USER_GLOBALS_START;
  extern int VECTORCAST_INT1;
  extern int VECTORCAST_INT2;
  extern int VECTORCAST_INT3;
  extern char VECTORCAST_STR1[8];
  extern int  VECTORCAST_BUFFER[4];
