/* Undefine all class, enum, field, namespace, struct, stubbed function,
   testable function, and union names (disable by setting
   VCAST_DO_NOT_UNDEF_FIELDS) */
#undef u16g_SysOptCtrl_OverOpenDeg
#undef s16g_SysOptCtrl_OverPos
#undef s_progress_callback
#undef k
#undef u8g_Lib_Sha256_Hash
#undef s_nb_ctx
#undef s_nb_state
#undef s_nb_p_data
#undef s_nb_data_len
#undef s_nb_processed_len
#undef s_nb_process_count
#undef u16g_Sha256_Hash_Update_Count
#undef u8t_Data
#undef u8t_DataInit
#undef u8t_MaxCount
#undef u16t_Data
#undef u16tDataInit
#undef u8t_MaxCount
#undef u8t_Data
#undef u8t_DataMin
#undef u8t_DataMax
#undef u16t_Data
#undef u16t_DataMin
#undef u16t_DataMax
#undef s16t_Data
#undef s16t_DataMin
#undef s16t_DataMax
#undef u16t_Angle
#undef value
#undef bits
#undef ctx
#undef data
#undef ctx
#undef ctx
#undef data
#undef len
#undef ctx
#undef hash
#undef __T381389256
#undef s_safe_rotr
#undef s_sha256_transform
#undef s_sha256_init
#undef s_sha256_update
#undef s_sha256_final
#undef s_Sha256_Hash_Init
#undef g_Lib_Sha256_Nb_Start
#undef g_Lib_Sha256_Nb_Process
#undef g_Lib_Sha256_Nb_GetState
#undef g_Lib_Sha256_Nb_Reset
#undef state
#undef bitcount
#undef buffer
#undef E_LIB_SHA256_NB_STATE
#undef E_LIB_SHA256_NB_STATE_IDLE
#undef E_LIB_SHA256_NB_STATE_ERROR
