"""CodeSonar PDF 파서 단위 테스트 (parse_codesonar_text — PDF 비의존).

실데이터 PDS64_RD analysis 106 (CodeSonar_PDS64_RD_1.01_23.10.12.pdf) 레이아웃 기준.
"""
from backend.services.codesonar_pdf_parser import parse_codesonar_text

# pdfplumber extract_text()가 뽑는 실제 텍스트 형태(표 셀 공백 병합)를 모사.
_REAL = """CodeSonar Analysis Report
generated by Anonymous on Thu Oct 12 12:06:41 2023
for analysis PDS64_RD analysis 106
Table 1: PDS64_RD analysis 106 Summary
Summary
Active Warnings File Count Project Name Time Started Time Finished Machine
50 93 PDS64_RD Tue Oct 10 16:57:10 2023 Tue Oct 10 16:59:02 2023 LAPTOP-5R26MBFO
Figure 1: PDS64_RD analysis 106, Warnings by Class
Table 2: PDS64_RD analysis 106, Warnings by Class
Warning Class Active Warnings
Useless Assignment 25
Potential Unbounded Loop 10
Redundant Condition 7
Empty while Statement 5
Unreachable Data Flow 1
Unused Value 1
Uninitialized Variable 1
Table 3: PDS64_RD analysis 106, Warnings by File
File Active Warnings Total Lines Language
ApiOut_LinTxComp_PDS.c 20 192 C
Ap_DoorCtrl_PDS.c 5 1815 C
Monitor_ADC.c 5 353 C
EEPROM.c 5 294 C
"""


def test_summary_extracted():
    d = parse_codesonar_text(_REAL)
    assert d["summary"]["active_warnings"] == 50
    assert d["summary"]["file_count"] == 93
    assert d["summary"]["project_name"] == "PDS64_RD"
    assert d["summary"]["analysis_id"] == "106"
    assert d["summary"]["machine"] == "LAPTOP-5R26MBFO"


def test_by_class_all_rows_and_order():
    d = parse_codesonar_text(_REAL)
    assert len(d["by_class"]) == 7
    assert d["by_class"][0] == {"warning_class": "Useless Assignment", "count": 25}
    assert d["by_class"][1]["warning_class"] == "Potential Unbounded Loop"
    # 공백이 있는 클래스명도 카운트만 분리되어야 한다
    assert d["by_class"][3] == {"warning_class": "Empty while Statement", "count": 5}


def test_by_file_parsed():
    d = parse_codesonar_text(_REAL)
    assert len(d["by_file"]) == 4
    assert d["by_file"][0] == {
        "file": "ApiOut_LinTxComp_PDS.c",
        "warnings": 20,
        "lines": 192,
        "language": "C",
    }
    assert d["by_file"][1]["lines"] == 1815


def test_class_sum_matches_active_warnings_no_warning():
    d = parse_codesonar_text(_REAL)
    # 25+10+7+5+1+1+1 = 50 == active_warnings → 정합성 경고 없어야 함
    assert sum(c["count"] for c in d["by_class"]) == d["summary"]["active_warnings"]
    assert d["parse_warnings"] == []
    assert d["summary"]["distinct_classes"] == 7


def test_class_sum_mismatch_emits_warning():
    # 합 불일치(페이지 누락 시나리오) → parse_warnings에 기록
    txt = (
        "Active Warnings File Count Project Name Time Started Time Finished Machine\n"
        "99 10 P Tue\n"
        "Warning Class Active Warnings\nUseless Assignment 25\n"
    )
    d = parse_codesonar_text(txt)
    assert any("by_class 합" in w for w in d["parse_warnings"])


def test_empty_text_graceful():
    d = parse_codesonar_text("")
    assert d["by_class"] == []
    assert d["by_file"] == []
    assert d["summary"].get("active_warnings") is None
    assert d["parse_warnings"]  # 미발견 경고 기록
