"""report_gen package - split from report_generator.py

All public and private symbols are re-exported here so that
``from report_gen import X`` works for any function previously
defined in the monolithic ``report_generator.py``.
"""

# --- source_parser (leaf) ---
# --- docx_builder ---
from report_gen.docx_builder import (
    _add_blank_table,
    _add_docx_bullets,
    _add_docx_lines,
    _add_docx_text_block,
    _add_docx_toc,
    _clear_docx_body,
    _extract_template_blocks,
    _extract_template_section_map,
    _fill_function_info_table,
    _insert_logic_image_in_table,
    _iter_template_blocks,
    _merge_function_info_table,
    _normalize_function_info_tables,
    _remove_docx_paragraphs,
    _render_call_graph_image,
    _render_logic_flow_diagram,
    _render_logic_text_image,
    _render_swcom_overview_image,
    _render_unit_structure_image,
    _replace_docx_text,
    _template_has_placeholders,
    generate_uds_docx,
)

# --- function_analyzer ---
from report_gen.function_analyzer import (
    _build_function_info_rows,
    _classify_description_quality,
    _classify_param_direction,
    _collect_var_usage,
    _enhance_description_text,
    _enhance_function_description,
    _extract_condition_branch_calls,
    _extract_logic_flow,
    _extract_logic_terminal_paths,
    _extract_param_symbol,
    _extract_primary_condition,
    _extract_return_type,
    _fallback_function_description,
    _finalize_function_fields,
    _format_param_entry,
    _infer_precondition_from_body,
    _is_exact_generic,
    _is_generic_description,
    _is_static_var,
    _normalize_bracket_expr,
    _normalize_symbol_name,
    _parse_signature_outputs,
    _parse_signature_params,
    _safe_eval_int,
    _split_func_name_words,
    _split_param,
    _split_signature_param_chunks,
    _strip_comments_and_strings,
)

# --- requirements ---
from report_gen.requirements import (
    _build_req_map_from_doc_paths,
    _build_req_map_from_texts,
    _collect_section_lines,
    _docx_to_text,
    _extract_doc_function_names,
    _extract_doc_section,
    _extract_function_blocks,
    _extract_function_info_from_docx,
    _extract_requirement_blocks,
    _extract_requirements_fallback,
    _extract_requirements_from_comments,
    _extract_requirements_from_doc,
    _extract_sds_partition_map,
    _extract_state_tokens,
    _extract_table_section,
    _load_component_map,
    _normalize_table_row,
    _normalize_trace_mapping_entry,
    _normalize_vcast_rows,
    _parse_traceability_csv,
    _parse_traceability_json,
    _parse_traceability_text,
    _split_doc_function_blocks,
    enrich_function_details_with_docs,
    generate_uds_function_mapping,
    generate_uds_requirements_compare,
    generate_uds_requirements_from_docs,
    generate_uds_requirements_mapping,
    generate_uds_requirements_preview,
    generate_uds_traceability_mapping,
    generate_uds_traceability_matrix,
)
from report_gen.source_parser import (
    _extract_c_definitions,
    _extract_c_function_bodies,
    _extract_c_global_candidates,
    _extract_c_macro_defs,
    _extract_c_macros,
    _extract_c_prototypes,
    _extract_comment_lines,
    _read_text_limited,
    _scan_source_comment_patterns,
    _scan_source_function_names,
    _scan_source_requirement_ids,
    _strip_c_comments,
)

# --- uds_generator ---
from report_gen.uds_generator import (
    _format_function_block_lines,
    _group_function_blocks_by_swcom,
    generate_uds_logic_items,
    generate_uds_preview_html,
    generate_uds_preview_markdown,
    generate_uds_source_sections,
    parse_uds_preview_html,
)

# --- uds_text (leaf) ---
from report_gen.uds_text import (
    _ai_document_text,
    _ai_evidence_lines,
    _ai_quality_warnings,
    _ai_section_text,
    _apply_sentence_rules,
    _apply_uds_rules,
    _merge_logic_ai_items,
    _merge_section_text,
    _split_sentences,
    _title_case_line,
    _trim_sentence_words,
    _uds_lines_to_html,
    _uds_logic_html,
)

# --- utils ---
from report_gen.utils import (
    _build_global_rows,
    _dedupe_multiline_text,
    _extract_call_names,
    _extract_issue_counts,
    _extract_simple_call_names,
    _fmt_bool,
    _infer_type_from_decl,
    _infer_type_from_file,
    _normalize_asil_value,
    _normalize_call_field,
    _normalize_related_ids,
    _normalize_swcom_label,
    _normalize_swufn_id,
    _safe_dict,
    _safe_list,
    _table_rows_from_texts,
    generate_markdown_summary,
    generate_pdf_report,
)

# --- validation ---
from report_gen.validation import (
    _clean_param_lines,
    _parse_accuracy_summary,
    _parse_quality_gate_summary,
    _split_csvish,
    build_uds_view_payload,
    generate_asil_related_confidence_report,
    generate_called_calling_accuracy_report,
    generate_swcom_context_diff_report,
    generate_swcom_context_report,
    generate_uds_constraints_report,
    generate_uds_delta_report,
    generate_uds_field_quality_gate_report,
    generate_uds_validation_report,
    validate_uds_docx_structure,
)

__all__ = [
    # Public functions
    "generate_markdown_summary",
    "generate_pdf_report",
    "generate_uds_logic_items",
    "parse_uds_preview_html",
    "generate_uds_source_sections",
    "generate_uds_preview_markdown",
    "generate_uds_preview_html",
    "generate_uds_docx",
    "generate_uds_requirements_preview",
    "generate_uds_requirements_mapping",
    "generate_uds_function_mapping",
    "generate_uds_traceability_mapping",
    "generate_uds_traceability_matrix",
    "generate_uds_requirements_compare",
    "generate_uds_requirements_from_docs",
    "validate_uds_docx_structure",
    "generate_uds_validation_report",
    "generate_called_calling_accuracy_report",
    "generate_swcom_context_report",
    "generate_swcom_context_diff_report",
    "generate_uds_field_quality_gate_report",
    "generate_uds_delta_report",
    "build_uds_view_payload",
    "generate_uds_constraints_report",
    "generate_asil_related_confidence_report",
]
